apiVersion: apps/v1
kind: Deployment
metadata:
  name: ziti-testclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ziti-testclient
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ziti-testclient
    spec:
      containers:
      - image: centos
        name: testclient
        command: ["sh","-c"]
        args: [
          "while true; do 
            set +x;
            curl -sSf http://100.128.0.2/ip 2>&1; 
            sleep 5; 
          done"
        ]
#        command: ["sh", "-c", "while true; do sleep infinity; done"]
      restartPolicy: Always
      dnsPolicy: Default
