/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5170
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2021ConfigIdByConfigTypeId {
    #[serde(rename = "6fa5c2bc-b7f7-47f8-9229-e927722adb27", skip_serializing_if = "Option::is_none")]
    pub var_6fa5c2bc_b7f7_47f8_9229_e927722adb27: Option<String>,
    #[serde(rename = "b1582680-ab7b-45d0-ac36-b00f82df8e79", skip_serializing_if = "Option::is_none")]
    pub b1582680_ab7b_45d0_ac36_b00f82df8e79: Option<String>,
}

impl InlineResponse2021ConfigIdByConfigTypeId {
    pub fn new() -> InlineResponse2021ConfigIdByConfigTypeId {
        InlineResponse2021ConfigIdByConfigTypeId {
            var_6fa5c2bc_b7f7_47f8_9229_e927722adb27: None,
            b1582680_ab7b_45d0_ac36_b00f82df8e79: None,
        }
    }
}


