/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5227
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2004Embedded {
    #[serde(rename = "edgeRouterPolicyList")]
    pub edge_router_policy_list: Vec<crate::models::InlineResponse2004EmbeddedEdgeRouterPolicyList>,
}

impl InlineResponse2004Embedded {
    pub fn new(edge_router_policy_list: Vec<crate::models::InlineResponse2004EmbeddedEdgeRouterPolicyList>) -> InlineResponse2004Embedded {
        InlineResponse2004Embedded {
            edge_router_policy_list,
        }
    }
}


