/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 5170
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineObject2 struct for InlineObject2
type InlineObject2 struct {
	EdgeRouterAttributes []string `json:"edgeRouterAttributes"`
	EndpointAttributes []string `json:"endpointAttributes"`
	Name string `json:"name"`
	NetworkId string `json:"networkId"`
}
