/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 5170
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2004 struct for InlineResponse2004
type InlineResponse2004 struct {
	Embedded InlineResponse2004Embedded `json:"_embedded,omitempty"`
	Links InlineResponse2002EmbeddedLinks `json:"_links"`
	Page InlineResponse2001Page `json:"page"`
}
