/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 5170
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse20014UpdatedAt struct for InlineResponse20014UpdatedAt
type InlineResponse20014UpdatedAt struct {
	EpochSecond float32 `json:"epochSecond"`
	Nano float32 `json:"nano"`
}
