/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 5229
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse200LinksSelf struct for InlineResponse200LinksSelf
type InlineResponse200LinksSelf struct {
	Href string `json:"href"`
}
