/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 5227
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2024NetworkController struct for InlineResponse2024NetworkController
type InlineResponse2024NetworkController struct {
	DeletedAt interface{} `json:"deletedAt"`
	NetworkId string `json:"networkId"`
	Name string `json:"name"`
	UpdatedAt string `json:"updatedAt"`
	Provider string `json:"provider"`
	UserData interface{} `json:"userData"`
	OwnerIdentityId interface{} `json:"ownerIdentityId"`
	DomainName string `json:"domainName"`
	ProviderId string `json:"providerId"`
	Id string `json:"id"`
	Port float32 `json:"port"`
	IpAddress string `json:"ipAddress"`
	Status string `json:"status"`
	HostId string `json:"hostId"`
	CreatedAt string `json:"createdAt"`
	DeletedBy interface{} `json:"deletedBy"`
	LocationMetadataId string `json:"locationMetadataId"`
	DataCenterId string `json:"dataCenterId"`
}
