/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 5227
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2023ModelClientIngress struct for InlineResponse2023ModelClientIngress
type InlineResponse2023ModelClientIngress struct {
	Addresses []string `json:"addresses"`
	Ports []InlineResponse2003EmbeddedModelClientIngressPorts `json:"ports"`
	Protocols []string `json:"protocols"`
}
