/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 5227
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse20011Links struct for InlineResponse20011Links
type InlineResponse20011Links struct {
	AzureSubscription InlineResponse200LinksSelf `json:"azureSubscription"`
	Networks InlineResponse200LinksSelf `json:"networks"`
	Self InlineResponse200LinksSelf `json:"self"`
}
