/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 5170
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CoreV2ServicesServiceIdModelServerEgress struct for CoreV2ServicesServiceIdModelServerEgress
type CoreV2ServicesServiceIdModelServerEgress struct {
	DialInterceptAddress interface{} `json:"dialInterceptAddress"`
	DialInterceptPort interface{} `json:"dialInterceptPort"`
	Port float32 `json:"port"`
	DialInterceptProtocol bool `json:"dialInterceptProtocol"`
	Address string `json:"address"`
	Protocol interface{} `json:"protocol"`
}
