/*
 * untitled API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5170
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.InlineResponse2003EmbeddedServiceList;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2003Embedded
 */
public class InlineResponse2003EmbeddedTest {
    private final InlineResponse2003Embedded model = new InlineResponse2003Embedded();

    /**
     * Model tests for InlineResponse2003Embedded
     */
    @Test
    public void testInlineResponse2003Embedded() {
        // TODO: test InlineResponse2003Embedded
    }

    /**
     * Test the property 'serviceList'
     */
    @Test
    public void serviceListTest() {
        // TODO: test serviceList
    }

}
