/*
 * untitled API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5170
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2021ConfigIdByConfigTypeId
 */
public class InlineResponse2021ConfigIdByConfigTypeIdTest {
    private final InlineResponse2021ConfigIdByConfigTypeId model = new InlineResponse2021ConfigIdByConfigTypeId();

    /**
     * Model tests for InlineResponse2021ConfigIdByConfigTypeId
     */
    @Test
    public void testInlineResponse2021ConfigIdByConfigTypeId() {
        // TODO: test InlineResponse2021ConfigIdByConfigTypeId
    }

    /**
     * Test the property '_6fa5c2bcB7f747f89229E927722adb27'
     */
    @Test
    public void _6fa5c2bcB7f747f89229E927722adb27Test() {
        // TODO: test _6fa5c2bcB7f747f89229E927722adb27
    }

    /**
     * Test the property 'b1582680Ab7b45d0Ac36B00f82df8e79'
     */
    @Test
    public void b1582680Ab7b45d0Ac36B00f82df8e79Test() {
        // TODO: test b1582680Ab7b45d0Ac36B00f82df8e79
    }

}
