=begin
#untitled API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5170

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'date'

module OpenapiClient
  class InlineResponse20013
    attr_accessor :deleted_at

    attr_accessor :name

    attr_accessor :updated_at

    attr_accessor :size

    attr_accessor :location_code

    attr_accessor :owner_identity_id

    attr_accessor :product_version

    attr_accessor :network_group_id

    attr_accessor :id

    attr_accessor :status

    attr_accessor :sds_password

    attr_accessor :created_at

    attr_accessor :created_by

    attr_accessor :deleted_by

    attr_accessor :network_controller

    attr_accessor :o365_breakout_category

    attr_accessor :_links

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'deleted_at' => :'deletedAt',
        :'name' => :'name',
        :'updated_at' => :'updatedAt',
        :'size' => :'size',
        :'location_code' => :'locationCode',
        :'owner_identity_id' => :'ownerIdentityId',
        :'product_version' => :'productVersion',
        :'network_group_id' => :'networkGroupId',
        :'id' => :'id',
        :'status' => :'status',
        :'sds_password' => :'sdsPassword',
        :'created_at' => :'createdAt',
        :'created_by' => :'createdBy',
        :'deleted_by' => :'deletedBy',
        :'network_controller' => :'networkController',
        :'o365_breakout_category' => :'o365BreakoutCategory',
        :'_links' => :'_links'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'deleted_at' => :'AnyType',
        :'name' => :'String',
        :'updated_at' => :'String',
        :'size' => :'String',
        :'location_code' => :'String',
        :'owner_identity_id' => :'String',
        :'product_version' => :'String',
        :'network_group_id' => :'String',
        :'id' => :'String',
        :'status' => :'String',
        :'sds_password' => :'String',
        :'created_at' => :'String',
        :'created_by' => :'String',
        :'deleted_by' => :'AnyType',
        :'network_controller' => :'AnyType',
        :'o365_breakout_category' => :'String',
        :'_links' => :'InlineResponse2001EmbeddedLinks'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::InlineResponse20013` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::InlineResponse20013`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'deleted_at')
        self.deleted_at = attributes[:'deleted_at']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'size')
        self.size = attributes[:'size']
      end

      if attributes.key?(:'location_code')
        self.location_code = attributes[:'location_code']
      end

      if attributes.key?(:'owner_identity_id')
        self.owner_identity_id = attributes[:'owner_identity_id']
      end

      if attributes.key?(:'product_version')
        self.product_version = attributes[:'product_version']
      end

      if attributes.key?(:'network_group_id')
        self.network_group_id = attributes[:'network_group_id']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'sds_password')
        self.sds_password = attributes[:'sds_password']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'created_by')
        self.created_by = attributes[:'created_by']
      end

      if attributes.key?(:'deleted_by')
        self.deleted_by = attributes[:'deleted_by']
      end

      if attributes.key?(:'network_controller')
        self.network_controller = attributes[:'network_controller']
      end

      if attributes.key?(:'o365_breakout_category')
        self.o365_breakout_category = attributes[:'o365_breakout_category']
      end

      if attributes.key?(:'_links')
        self._links = attributes[:'_links']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @deleted_at.nil?
        invalid_properties.push('invalid value for "deleted_at", deleted_at cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      if @size.nil?
        invalid_properties.push('invalid value for "size", size cannot be nil.')
      end

      if @owner_identity_id.nil?
        invalid_properties.push('invalid value for "owner_identity_id", owner_identity_id cannot be nil.')
      end

      if @product_version.nil?
        invalid_properties.push('invalid value for "product_version", product_version cannot be nil.')
      end

      if @network_group_id.nil?
        invalid_properties.push('invalid value for "network_group_id", network_group_id cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @created_by.nil?
        invalid_properties.push('invalid value for "created_by", created_by cannot be nil.')
      end

      if @deleted_by.nil?
        invalid_properties.push('invalid value for "deleted_by", deleted_by cannot be nil.')
      end

      if @o365_breakout_category.nil?
        invalid_properties.push('invalid value for "o365_breakout_category", o365_breakout_category cannot be nil.')
      end

      if @_links.nil?
        invalid_properties.push('invalid value for "_links", _links cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @deleted_at.nil?
      return false if @name.nil?
      return false if @updated_at.nil?
      return false if @size.nil?
      return false if @owner_identity_id.nil?
      return false if @product_version.nil?
      return false if @network_group_id.nil?
      return false if @id.nil?
      return false if @status.nil?
      return false if @created_at.nil?
      return false if @created_by.nil?
      return false if @deleted_by.nil?
      return false if @o365_breakout_category.nil?
      return false if @_links.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          deleted_at == o.deleted_at &&
          name == o.name &&
          updated_at == o.updated_at &&
          size == o.size &&
          location_code == o.location_code &&
          owner_identity_id == o.owner_identity_id &&
          product_version == o.product_version &&
          network_group_id == o.network_group_id &&
          id == o.id &&
          status == o.status &&
          sds_password == o.sds_password &&
          created_at == o.created_at &&
          created_by == o.created_by &&
          deleted_by == o.deleted_by &&
          network_controller == o.network_controller &&
          o365_breakout_category == o.o365_breakout_category &&
          _links == o._links
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [deleted_at, name, updated_at, size, location_code, owner_identity_id, product_version, network_group_id, id, status, sds_password, created_at, created_by, deleted_by, network_controller, o365_breakout_category, _links].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        OpenapiClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end
        
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
