/*
 * untitled API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5227
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.InlineResponse2003EmbeddedModelClientIngress;
import org.openapitools.client.model.InlineResponse2003EmbeddedModelEdgeRouterHosts;
import org.openapitools.client.model.InlineResponse2003EmbeddedModelServerEgress;

/**
 * InlineResponse2003EmbeddedModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-04-13T16:26:28.927973-04:00[America/New_York]")
public class InlineResponse2003EmbeddedModel {
  public static final String SERIALIZED_NAME_EDGE_ROUTER_ATTRIBUTES = "edgeRouterAttributes";
  @SerializedName(SERIALIZED_NAME_EDGE_ROUTER_ATTRIBUTES)
  private List<String> edgeRouterAttributes = new ArrayList<String>();

  public static final String SERIALIZED_NAME_SERVER_EGRESS = "serverEgress";
  @SerializedName(SERIALIZED_NAME_SERVER_EGRESS)
  private InlineResponse2003EmbeddedModelServerEgress serverEgress;

  public static final String SERIALIZED_NAME_BIND_ENDPOINT_ATTRIBUTES = "bindEndpointAttributes";
  @SerializedName(SERIALIZED_NAME_BIND_ENDPOINT_ATTRIBUTES)
  private List<String> bindEndpointAttributes = null;

  public static final String SERIALIZED_NAME_CLIENT_INGRESS = "clientIngress";
  @SerializedName(SERIALIZED_NAME_CLIENT_INGRESS)
  private InlineResponse2003EmbeddedModelClientIngress clientIngress;

  public static final String SERIALIZED_NAME_EDGE_ROUTER_HOSTS = "edgeRouterHosts";
  @SerializedName(SERIALIZED_NAME_EDGE_ROUTER_HOSTS)
  private List<InlineResponse2003EmbeddedModelEdgeRouterHosts> edgeRouterHosts = null;


  public InlineResponse2003EmbeddedModel edgeRouterAttributes(List<String> edgeRouterAttributes) {
    
    this.edgeRouterAttributes = edgeRouterAttributes;
    return this;
  }

  public InlineResponse2003EmbeddedModel addEdgeRouterAttributesItem(String edgeRouterAttributesItem) {
    this.edgeRouterAttributes.add(edgeRouterAttributesItem);
    return this;
  }

   /**
   * Get edgeRouterAttributes
   * @return edgeRouterAttributes
  **/
  @ApiModelProperty(required = true, value = "")

  public List<String> getEdgeRouterAttributes() {
    return edgeRouterAttributes;
  }


  public void setEdgeRouterAttributes(List<String> edgeRouterAttributes) {
    this.edgeRouterAttributes = edgeRouterAttributes;
  }


  public InlineResponse2003EmbeddedModel serverEgress(InlineResponse2003EmbeddedModelServerEgress serverEgress) {
    
    this.serverEgress = serverEgress;
    return this;
  }

   /**
   * Get serverEgress
   * @return serverEgress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public InlineResponse2003EmbeddedModelServerEgress getServerEgress() {
    return serverEgress;
  }


  public void setServerEgress(InlineResponse2003EmbeddedModelServerEgress serverEgress) {
    this.serverEgress = serverEgress;
  }


  public InlineResponse2003EmbeddedModel bindEndpointAttributes(List<String> bindEndpointAttributes) {
    
    this.bindEndpointAttributes = bindEndpointAttributes;
    return this;
  }

  public InlineResponse2003EmbeddedModel addBindEndpointAttributesItem(String bindEndpointAttributesItem) {
    if (this.bindEndpointAttributes == null) {
      this.bindEndpointAttributes = new ArrayList<String>();
    }
    this.bindEndpointAttributes.add(bindEndpointAttributesItem);
    return this;
  }

   /**
   * Get bindEndpointAttributes
   * @return bindEndpointAttributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getBindEndpointAttributes() {
    return bindEndpointAttributes;
  }


  public void setBindEndpointAttributes(List<String> bindEndpointAttributes) {
    this.bindEndpointAttributes = bindEndpointAttributes;
  }


  public InlineResponse2003EmbeddedModel clientIngress(InlineResponse2003EmbeddedModelClientIngress clientIngress) {
    
    this.clientIngress = clientIngress;
    return this;
  }

   /**
   * Get clientIngress
   * @return clientIngress
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse2003EmbeddedModelClientIngress getClientIngress() {
    return clientIngress;
  }


  public void setClientIngress(InlineResponse2003EmbeddedModelClientIngress clientIngress) {
    this.clientIngress = clientIngress;
  }


  public InlineResponse2003EmbeddedModel edgeRouterHosts(List<InlineResponse2003EmbeddedModelEdgeRouterHosts> edgeRouterHosts) {
    
    this.edgeRouterHosts = edgeRouterHosts;
    return this;
  }

  public InlineResponse2003EmbeddedModel addEdgeRouterHostsItem(InlineResponse2003EmbeddedModelEdgeRouterHosts edgeRouterHostsItem) {
    if (this.edgeRouterHosts == null) {
      this.edgeRouterHosts = new ArrayList<InlineResponse2003EmbeddedModelEdgeRouterHosts>();
    }
    this.edgeRouterHosts.add(edgeRouterHostsItem);
    return this;
  }

   /**
   * Get edgeRouterHosts
   * @return edgeRouterHosts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<InlineResponse2003EmbeddedModelEdgeRouterHosts> getEdgeRouterHosts() {
    return edgeRouterHosts;
  }


  public void setEdgeRouterHosts(List<InlineResponse2003EmbeddedModelEdgeRouterHosts> edgeRouterHosts) {
    this.edgeRouterHosts = edgeRouterHosts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2003EmbeddedModel inlineResponse2003EmbeddedModel = (InlineResponse2003EmbeddedModel) o;
    return Objects.equals(this.edgeRouterAttributes, inlineResponse2003EmbeddedModel.edgeRouterAttributes) &&
        Objects.equals(this.serverEgress, inlineResponse2003EmbeddedModel.serverEgress) &&
        Objects.equals(this.bindEndpointAttributes, inlineResponse2003EmbeddedModel.bindEndpointAttributes) &&
        Objects.equals(this.clientIngress, inlineResponse2003EmbeddedModel.clientIngress) &&
        Objects.equals(this.edgeRouterHosts, inlineResponse2003EmbeddedModel.edgeRouterHosts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(edgeRouterAttributes, serverEgress, bindEndpointAttributes, clientIngress, edgeRouterHosts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2003EmbeddedModel {\n");
    sb.append("    edgeRouterAttributes: ").append(toIndentedString(edgeRouterAttributes)).append("\n");
    sb.append("    serverEgress: ").append(toIndentedString(serverEgress)).append("\n");
    sb.append("    bindEndpointAttributes: ").append(toIndentedString(bindEndpointAttributes)).append("\n");
    sb.append("    clientIngress: ").append(toIndentedString(clientIngress)).append("\n");
    sb.append("    edgeRouterHosts: ").append(toIndentedString(edgeRouterHosts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

