/*
 * untitled API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.InlineResponse2003EmbeddedModel;
import org.openapitools.client.model.InlineResponse2021ConfigIdByConfigTypeId;
import org.openapitools.client.model.InlineResponse2021Links;
import org.openapitools.client.model.oas_any_type_not_mapped;

/**
 * InlineResponse2021
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-03T11:59:07.273777-04:00[America/New_York]")
public class InlineResponse2021 {
  public static final String SERIALIZED_NAME_DELETED_AT = "deletedAt";
  @SerializedName(SERIALIZED_NAME_DELETED_AT)
  private oas_any_type_not_mapped deletedAt = null;

  public static final String SERIALIZED_NAME_NETWORK_ID = "networkId";
  @SerializedName(SERIALIZED_NAME_NETWORK_ID)
  private String networkId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public static final String SERIALIZED_NAME_MODEL = "model";
  @SerializedName(SERIALIZED_NAME_MODEL)
  private InlineResponse2003EmbeddedModel model;

  public static final String SERIALIZED_NAME_ZITI_ID = "zitiId";
  @SerializedName(SERIALIZED_NAME_ZITI_ID)
  private oas_any_type_not_mapped zitiId = null;

  public static final String SERIALIZED_NAME_OWNER_IDENTITY_ID = "ownerIdentityId";
  @SerializedName(SERIALIZED_NAME_OWNER_IDENTITY_ID)
  private String ownerIdentityId;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private List<String> attributes = new ArrayList<String>();

  public static final String SERIALIZED_NAME_MODEL_TYPE = "modelType";
  @SerializedName(SERIALIZED_NAME_MODEL_TYPE)
  private String modelType;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_CONFIG_ID_BY_CONFIG_TYPE_ID = "configIdByConfigTypeId";
  @SerializedName(SERIALIZED_NAME_CONFIG_ID_BY_CONFIG_TYPE_ID)
  private InlineResponse2021ConfigIdByConfigTypeId configIdByConfigTypeId;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_CREATED_BY = "createdBy";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  private String createdBy;

  public static final String SERIALIZED_NAME_DELETED_BY = "deletedBy";
  @SerializedName(SERIALIZED_NAME_DELETED_BY)
  private oas_any_type_not_mapped deletedBy = null;

  public static final String SERIALIZED_NAME_ENCRYPTION_REQUIRED = "encryptionRequired";
  @SerializedName(SERIALIZED_NAME_ENCRYPTION_REQUIRED)
  private Boolean encryptionRequired;

  public static final String SERIALIZED_NAME_AUTHORITY = "authority";
  @SerializedName(SERIALIZED_NAME_AUTHORITY)
  private oas_any_type_not_mapped authority = null;

  public static final String SERIALIZED_NAME_LINKS = "_links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private InlineResponse2021Links links;


  public InlineResponse2021 deletedAt(oas_any_type_not_mapped deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

   /**
   * Get deletedAt
   * @return deletedAt
  **/
  @ApiModelProperty(required = true, value = "")

  public oas_any_type_not_mapped getDeletedAt() {
    return deletedAt;
  }


  public void setDeletedAt(oas_any_type_not_mapped deletedAt) {
    this.deletedAt = deletedAt;
  }


  public InlineResponse2021 networkId(String networkId) {
    
    this.networkId = networkId;
    return this;
  }

   /**
   * Get networkId
   * @return networkId
  **/
  @ApiModelProperty(required = true, value = "")

  public String getNetworkId() {
    return networkId;
  }


  public void setNetworkId(String networkId) {
    this.networkId = networkId;
  }


  public InlineResponse2021 name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public InlineResponse2021 updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(required = true, value = "")

  public String getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public InlineResponse2021 model(InlineResponse2003EmbeddedModel model) {
    
    this.model = model;
    return this;
  }

   /**
   * Get model
   * @return model
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse2003EmbeddedModel getModel() {
    return model;
  }


  public void setModel(InlineResponse2003EmbeddedModel model) {
    this.model = model;
  }


  public InlineResponse2021 zitiId(oas_any_type_not_mapped zitiId) {
    
    this.zitiId = zitiId;
    return this;
  }

   /**
   * Get zitiId
   * @return zitiId
  **/
  @ApiModelProperty(required = true, value = "")

  public oas_any_type_not_mapped getZitiId() {
    return zitiId;
  }


  public void setZitiId(oas_any_type_not_mapped zitiId) {
    this.zitiId = zitiId;
  }


  public InlineResponse2021 ownerIdentityId(String ownerIdentityId) {
    
    this.ownerIdentityId = ownerIdentityId;
    return this;
  }

   /**
   * Get ownerIdentityId
   * @return ownerIdentityId
  **/
  @ApiModelProperty(required = true, value = "")

  public String getOwnerIdentityId() {
    return ownerIdentityId;
  }


  public void setOwnerIdentityId(String ownerIdentityId) {
    this.ownerIdentityId = ownerIdentityId;
  }


  public InlineResponse2021 attributes(List<String> attributes) {
    
    this.attributes = attributes;
    return this;
  }

  public InlineResponse2021 addAttributesItem(String attributesItem) {
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @ApiModelProperty(required = true, value = "")

  public List<String> getAttributes() {
    return attributes;
  }


  public void setAttributes(List<String> attributes) {
    this.attributes = attributes;
  }


  public InlineResponse2021 modelType(String modelType) {
    
    this.modelType = modelType;
    return this;
  }

   /**
   * Get modelType
   * @return modelType
  **/
  @ApiModelProperty(required = true, value = "")

  public String getModelType() {
    return modelType;
  }


  public void setModelType(String modelType) {
    this.modelType = modelType;
  }


  public InlineResponse2021 id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public InlineResponse2021 configIdByConfigTypeId(InlineResponse2021ConfigIdByConfigTypeId configIdByConfigTypeId) {
    
    this.configIdByConfigTypeId = configIdByConfigTypeId;
    return this;
  }

   /**
   * Get configIdByConfigTypeId
   * @return configIdByConfigTypeId
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse2021ConfigIdByConfigTypeId getConfigIdByConfigTypeId() {
    return configIdByConfigTypeId;
  }


  public void setConfigIdByConfigTypeId(InlineResponse2021ConfigIdByConfigTypeId configIdByConfigTypeId) {
    this.configIdByConfigTypeId = configIdByConfigTypeId;
  }


  public InlineResponse2021 createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(required = true, value = "")

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public InlineResponse2021 createdBy(String createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(required = true, value = "")

  public String getCreatedBy() {
    return createdBy;
  }


  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }


  public InlineResponse2021 deletedBy(oas_any_type_not_mapped deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

   /**
   * Get deletedBy
   * @return deletedBy
  **/
  @ApiModelProperty(required = true, value = "")

  public oas_any_type_not_mapped getDeletedBy() {
    return deletedBy;
  }


  public void setDeletedBy(oas_any_type_not_mapped deletedBy) {
    this.deletedBy = deletedBy;
  }


  public InlineResponse2021 encryptionRequired(Boolean encryptionRequired) {
    
    this.encryptionRequired = encryptionRequired;
    return this;
  }

   /**
   * Get encryptionRequired
   * @return encryptionRequired
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getEncryptionRequired() {
    return encryptionRequired;
  }


  public void setEncryptionRequired(Boolean encryptionRequired) {
    this.encryptionRequired = encryptionRequired;
  }


  public InlineResponse2021 authority(oas_any_type_not_mapped authority) {
    
    this.authority = authority;
    return this;
  }

   /**
   * Get authority
   * @return authority
  **/
  @ApiModelProperty(required = true, value = "")

  public oas_any_type_not_mapped getAuthority() {
    return authority;
  }


  public void setAuthority(oas_any_type_not_mapped authority) {
    this.authority = authority;
  }


  public InlineResponse2021 links(InlineResponse2021Links links) {
    
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse2021Links getLinks() {
    return links;
  }


  public void setLinks(InlineResponse2021Links links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2021 inlineResponse2021 = (InlineResponse2021) o;
    return Objects.equals(this.deletedAt, inlineResponse2021.deletedAt) &&
        Objects.equals(this.networkId, inlineResponse2021.networkId) &&
        Objects.equals(this.name, inlineResponse2021.name) &&
        Objects.equals(this.updatedAt, inlineResponse2021.updatedAt) &&
        Objects.equals(this.model, inlineResponse2021.model) &&
        Objects.equals(this.zitiId, inlineResponse2021.zitiId) &&
        Objects.equals(this.ownerIdentityId, inlineResponse2021.ownerIdentityId) &&
        Objects.equals(this.attributes, inlineResponse2021.attributes) &&
        Objects.equals(this.modelType, inlineResponse2021.modelType) &&
        Objects.equals(this.id, inlineResponse2021.id) &&
        Objects.equals(this.configIdByConfigTypeId, inlineResponse2021.configIdByConfigTypeId) &&
        Objects.equals(this.createdAt, inlineResponse2021.createdAt) &&
        Objects.equals(this.createdBy, inlineResponse2021.createdBy) &&
        Objects.equals(this.deletedBy, inlineResponse2021.deletedBy) &&
        Objects.equals(this.encryptionRequired, inlineResponse2021.encryptionRequired) &&
        Objects.equals(this.authority, inlineResponse2021.authority) &&
        Objects.equals(this.links, inlineResponse2021.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deletedAt, networkId, name, updatedAt, model, zitiId, ownerIdentityId, attributes, modelType, id, configIdByConfigTypeId, createdAt, createdBy, deletedBy, encryptionRequired, authority, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2021 {\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    networkId: ").append(toIndentedString(networkId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    zitiId: ").append(toIndentedString(zitiId)).append("\n");
    sb.append("    ownerIdentityId: ").append(toIndentedString(ownerIdentityId)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    modelType: ").append(toIndentedString(modelType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    configIdByConfigTypeId: ").append(toIndentedString(configIdByConfigTypeId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("    encryptionRequired: ").append(toIndentedString(encryptionRequired)).append("\n");
    sb.append("    authority: ").append(toIndentedString(authority)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

