/*
 * untitled API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5170
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.InlineResponse20019710;
import org.openapitools.client.model.InlineResponse200197316;
import org.openapitools.client.model.InlineResponse20019734;

/**
 * InlineResponse20019
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-04-12T16:43:17.497575-04:00[America/New_York]")
public class InlineResponse20019 {
  public static final String SERIALIZED_NAME_734 = "7.3.4";
  @SerializedName(SERIALIZED_NAME_734)
  private InlineResponse20019734 _7_3_4;

  public static final String SERIALIZED_NAME_7311 = "7.3.11";
  @SerializedName(SERIALIZED_NAME_7311)
  private InlineResponse20019734 _7_3_11;

  public static final String SERIALIZED_NAME_7316 = "7.3.16";
  @SerializedName(SERIALIZED_NAME_7316)
  private InlineResponse200197316 _7_3_16;

  public static final String SERIALIZED_NAME_710 = "7.1.0";
  @SerializedName(SERIALIZED_NAME_710)
  private InlineResponse20019710 _7_1_0;

  public static final String SERIALIZED_NAME_7322 = "7.3.22";
  @SerializedName(SERIALIZED_NAME_7322)
  private InlineResponse200197316 _7_3_22;

  public static final String SERIALIZED_NAME_7323 = "7.3.23";
  @SerializedName(SERIALIZED_NAME_7323)
  private InlineResponse200197316 _7_3_23;

  public static final String SERIALIZED_NAME_738 = "7.3.8";
  @SerializedName(SERIALIZED_NAME_738)
  private InlineResponse20019734 _7_3_8;

  public static final String SERIALIZED_NAME_7312 = "7.3.12";
  @SerializedName(SERIALIZED_NAME_7312)
  private InlineResponse20019734 _7_3_12;

  public static final String SERIALIZED_NAME_721 = "7.2.1";
  @SerializedName(SERIALIZED_NAME_721)
  private InlineResponse20019710 _7_2_1;

  public static final String SERIALIZED_NAME_7313 = "7.3.13";
  @SerializedName(SERIALIZED_NAME_7313)
  private InlineResponse20019734 _7_3_13;

  public static final String SERIALIZED_NAME_700 = "7.0.0";
  @SerializedName(SERIALIZED_NAME_700)
  private InlineResponse20019710 _7_0_0;

  public static final String SERIALIZED_NAME_7317 = "7.3.17";
  @SerializedName(SERIALIZED_NAME_7317)
  private InlineResponse200197316 _7_3_17;

  public static final String SERIALIZED_NAME_735 = "7.3.5";
  @SerializedName(SERIALIZED_NAME_735)
  private InlineResponse20019734 _7_3_5;

  public static final String SERIALIZED_NAME_7320 = "7.3.20";
  @SerializedName(SERIALIZED_NAME_7320)
  private InlineResponse200197316 _7_3_20;

  public static final String SERIALIZED_NAME_732 = "7.3.2";
  @SerializedName(SERIALIZED_NAME_732)
  private InlineResponse20019710 _7_3_2;

  public static final String SERIALIZED_NAME_739 = "7.3.9";
  @SerializedName(SERIALIZED_NAME_739)
  private InlineResponse20019734 _7_3_9;

  public static final String SERIALIZED_NAME_7324 = "7.3.24";
  @SerializedName(SERIALIZED_NAME_7324)
  private InlineResponse200197316 _7_3_24;

  public static final String SERIALIZED_NAME_720 = "7.2.0";
  @SerializedName(SERIALIZED_NAME_720)
  private InlineResponse20019710 _7_2_0;

  public static final String SERIALIZED_NAME_730 = "7.3.0";
  @SerializedName(SERIALIZED_NAME_730)
  private InlineResponse20019710 _7_3_0;

  public static final String SERIALIZED_NAME_7314 = "7.3.14";
  @SerializedName(SERIALIZED_NAME_7314)
  private InlineResponse200197316 _7_3_14;

  public static final String SERIALIZED_NAME_736 = "7.3.6";
  @SerializedName(SERIALIZED_NAME_736)
  private InlineResponse20019734 _7_3_6;

  public static final String SERIALIZED_NAME_731 = "7.3.1";
  @SerializedName(SERIALIZED_NAME_731)
  private InlineResponse20019710 _7_3_1;

  public static final String SERIALIZED_NAME_7319 = "7.3.19";
  @SerializedName(SERIALIZED_NAME_7319)
  private InlineResponse200197316 _7_3_19;

  public static final String SERIALIZED_NAME_7315 = "7.3.15";
  @SerializedName(SERIALIZED_NAME_7315)
  private InlineResponse200197316 _7_3_15;

  public static final String SERIALIZED_NAME_7310 = "7.3.10";
  @SerializedName(SERIALIZED_NAME_7310)
  private InlineResponse20019734 _7_3_10;

  public static final String SERIALIZED_NAME_737 = "7.3.7";
  @SerializedName(SERIALIZED_NAME_737)
  private InlineResponse20019734 _7_3_7;

  public static final String SERIALIZED_NAME_7321 = "7.3.21";
  @SerializedName(SERIALIZED_NAME_7321)
  private InlineResponse200197316 _7_3_21;

  public static final String SERIALIZED_NAME_733 = "7.3.3";
  @SerializedName(SERIALIZED_NAME_733)
  private InlineResponse20019710 _7_3_3;

  public static final String SERIALIZED_NAME_7318 = "7.3.18";
  @SerializedName(SERIALIZED_NAME_7318)
  private InlineResponse200197316 _7_3_18;


  public InlineResponse20019 _7_3_4(InlineResponse20019734 _7_3_4) {
    
    this._7_3_4 = _7_3_4;
    return this;
  }

   /**
   * Get _7_3_4
   * @return _7_3_4
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse20019734 get734() {
    return _7_3_4;
  }


  public void set734(InlineResponse20019734 _7_3_4) {
    this._7_3_4 = _7_3_4;
  }


  public InlineResponse20019 _7_3_11(InlineResponse20019734 _7_3_11) {
    
    this._7_3_11 = _7_3_11;
    return this;
  }

   /**
   * Get _7_3_11
   * @return _7_3_11
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse20019734 get7311() {
    return _7_3_11;
  }


  public void set7311(InlineResponse20019734 _7_3_11) {
    this._7_3_11 = _7_3_11;
  }


  public InlineResponse20019 _7_3_16(InlineResponse200197316 _7_3_16) {
    
    this._7_3_16 = _7_3_16;
    return this;
  }

   /**
   * Get _7_3_16
   * @return _7_3_16
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse200197316 get7316() {
    return _7_3_16;
  }


  public void set7316(InlineResponse200197316 _7_3_16) {
    this._7_3_16 = _7_3_16;
  }


  public InlineResponse20019 _7_1_0(InlineResponse20019710 _7_1_0) {
    
    this._7_1_0 = _7_1_0;
    return this;
  }

   /**
   * Get _7_1_0
   * @return _7_1_0
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse20019710 get710() {
    return _7_1_0;
  }


  public void set710(InlineResponse20019710 _7_1_0) {
    this._7_1_0 = _7_1_0;
  }


  public InlineResponse20019 _7_3_22(InlineResponse200197316 _7_3_22) {
    
    this._7_3_22 = _7_3_22;
    return this;
  }

   /**
   * Get _7_3_22
   * @return _7_3_22
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse200197316 get7322() {
    return _7_3_22;
  }


  public void set7322(InlineResponse200197316 _7_3_22) {
    this._7_3_22 = _7_3_22;
  }


  public InlineResponse20019 _7_3_23(InlineResponse200197316 _7_3_23) {
    
    this._7_3_23 = _7_3_23;
    return this;
  }

   /**
   * Get _7_3_23
   * @return _7_3_23
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse200197316 get7323() {
    return _7_3_23;
  }


  public void set7323(InlineResponse200197316 _7_3_23) {
    this._7_3_23 = _7_3_23;
  }


  public InlineResponse20019 _7_3_8(InlineResponse20019734 _7_3_8) {
    
    this._7_3_8 = _7_3_8;
    return this;
  }

   /**
   * Get _7_3_8
   * @return _7_3_8
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse20019734 get738() {
    return _7_3_8;
  }


  public void set738(InlineResponse20019734 _7_3_8) {
    this._7_3_8 = _7_3_8;
  }


  public InlineResponse20019 _7_3_12(InlineResponse20019734 _7_3_12) {
    
    this._7_3_12 = _7_3_12;
    return this;
  }

   /**
   * Get _7_3_12
   * @return _7_3_12
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse20019734 get7312() {
    return _7_3_12;
  }


  public void set7312(InlineResponse20019734 _7_3_12) {
    this._7_3_12 = _7_3_12;
  }


  public InlineResponse20019 _7_2_1(InlineResponse20019710 _7_2_1) {
    
    this._7_2_1 = _7_2_1;
    return this;
  }

   /**
   * Get _7_2_1
   * @return _7_2_1
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse20019710 get721() {
    return _7_2_1;
  }


  public void set721(InlineResponse20019710 _7_2_1) {
    this._7_2_1 = _7_2_1;
  }


  public InlineResponse20019 _7_3_13(InlineResponse20019734 _7_3_13) {
    
    this._7_3_13 = _7_3_13;
    return this;
  }

   /**
   * Get _7_3_13
   * @return _7_3_13
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse20019734 get7313() {
    return _7_3_13;
  }


  public void set7313(InlineResponse20019734 _7_3_13) {
    this._7_3_13 = _7_3_13;
  }


  public InlineResponse20019 _7_0_0(InlineResponse20019710 _7_0_0) {
    
    this._7_0_0 = _7_0_0;
    return this;
  }

   /**
   * Get _7_0_0
   * @return _7_0_0
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse20019710 get700() {
    return _7_0_0;
  }


  public void set700(InlineResponse20019710 _7_0_0) {
    this._7_0_0 = _7_0_0;
  }


  public InlineResponse20019 _7_3_17(InlineResponse200197316 _7_3_17) {
    
    this._7_3_17 = _7_3_17;
    return this;
  }

   /**
   * Get _7_3_17
   * @return _7_3_17
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse200197316 get7317() {
    return _7_3_17;
  }


  public void set7317(InlineResponse200197316 _7_3_17) {
    this._7_3_17 = _7_3_17;
  }


  public InlineResponse20019 _7_3_5(InlineResponse20019734 _7_3_5) {
    
    this._7_3_5 = _7_3_5;
    return this;
  }

   /**
   * Get _7_3_5
   * @return _7_3_5
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse20019734 get735() {
    return _7_3_5;
  }


  public void set735(InlineResponse20019734 _7_3_5) {
    this._7_3_5 = _7_3_5;
  }


  public InlineResponse20019 _7_3_20(InlineResponse200197316 _7_3_20) {
    
    this._7_3_20 = _7_3_20;
    return this;
  }

   /**
   * Get _7_3_20
   * @return _7_3_20
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse200197316 get7320() {
    return _7_3_20;
  }


  public void set7320(InlineResponse200197316 _7_3_20) {
    this._7_3_20 = _7_3_20;
  }


  public InlineResponse20019 _7_3_2(InlineResponse20019710 _7_3_2) {
    
    this._7_3_2 = _7_3_2;
    return this;
  }

   /**
   * Get _7_3_2
   * @return _7_3_2
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse20019710 get732() {
    return _7_3_2;
  }


  public void set732(InlineResponse20019710 _7_3_2) {
    this._7_3_2 = _7_3_2;
  }


  public InlineResponse20019 _7_3_9(InlineResponse20019734 _7_3_9) {
    
    this._7_3_9 = _7_3_9;
    return this;
  }

   /**
   * Get _7_3_9
   * @return _7_3_9
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse20019734 get739() {
    return _7_3_9;
  }


  public void set739(InlineResponse20019734 _7_3_9) {
    this._7_3_9 = _7_3_9;
  }


  public InlineResponse20019 _7_3_24(InlineResponse200197316 _7_3_24) {
    
    this._7_3_24 = _7_3_24;
    return this;
  }

   /**
   * Get _7_3_24
   * @return _7_3_24
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse200197316 get7324() {
    return _7_3_24;
  }


  public void set7324(InlineResponse200197316 _7_3_24) {
    this._7_3_24 = _7_3_24;
  }


  public InlineResponse20019 _7_2_0(InlineResponse20019710 _7_2_0) {
    
    this._7_2_0 = _7_2_0;
    return this;
  }

   /**
   * Get _7_2_0
   * @return _7_2_0
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse20019710 get720() {
    return _7_2_0;
  }


  public void set720(InlineResponse20019710 _7_2_0) {
    this._7_2_0 = _7_2_0;
  }


  public InlineResponse20019 _7_3_0(InlineResponse20019710 _7_3_0) {
    
    this._7_3_0 = _7_3_0;
    return this;
  }

   /**
   * Get _7_3_0
   * @return _7_3_0
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse20019710 get730() {
    return _7_3_0;
  }


  public void set730(InlineResponse20019710 _7_3_0) {
    this._7_3_0 = _7_3_0;
  }


  public InlineResponse20019 _7_3_14(InlineResponse200197316 _7_3_14) {
    
    this._7_3_14 = _7_3_14;
    return this;
  }

   /**
   * Get _7_3_14
   * @return _7_3_14
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse200197316 get7314() {
    return _7_3_14;
  }


  public void set7314(InlineResponse200197316 _7_3_14) {
    this._7_3_14 = _7_3_14;
  }


  public InlineResponse20019 _7_3_6(InlineResponse20019734 _7_3_6) {
    
    this._7_3_6 = _7_3_6;
    return this;
  }

   /**
   * Get _7_3_6
   * @return _7_3_6
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse20019734 get736() {
    return _7_3_6;
  }


  public void set736(InlineResponse20019734 _7_3_6) {
    this._7_3_6 = _7_3_6;
  }


  public InlineResponse20019 _7_3_1(InlineResponse20019710 _7_3_1) {
    
    this._7_3_1 = _7_3_1;
    return this;
  }

   /**
   * Get _7_3_1
   * @return _7_3_1
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse20019710 get731() {
    return _7_3_1;
  }


  public void set731(InlineResponse20019710 _7_3_1) {
    this._7_3_1 = _7_3_1;
  }


  public InlineResponse20019 _7_3_19(InlineResponse200197316 _7_3_19) {
    
    this._7_3_19 = _7_3_19;
    return this;
  }

   /**
   * Get _7_3_19
   * @return _7_3_19
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse200197316 get7319() {
    return _7_3_19;
  }


  public void set7319(InlineResponse200197316 _7_3_19) {
    this._7_3_19 = _7_3_19;
  }


  public InlineResponse20019 _7_3_15(InlineResponse200197316 _7_3_15) {
    
    this._7_3_15 = _7_3_15;
    return this;
  }

   /**
   * Get _7_3_15
   * @return _7_3_15
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse200197316 get7315() {
    return _7_3_15;
  }


  public void set7315(InlineResponse200197316 _7_3_15) {
    this._7_3_15 = _7_3_15;
  }


  public InlineResponse20019 _7_3_10(InlineResponse20019734 _7_3_10) {
    
    this._7_3_10 = _7_3_10;
    return this;
  }

   /**
   * Get _7_3_10
   * @return _7_3_10
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse20019734 get7310() {
    return _7_3_10;
  }


  public void set7310(InlineResponse20019734 _7_3_10) {
    this._7_3_10 = _7_3_10;
  }


  public InlineResponse20019 _7_3_7(InlineResponse20019734 _7_3_7) {
    
    this._7_3_7 = _7_3_7;
    return this;
  }

   /**
   * Get _7_3_7
   * @return _7_3_7
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse20019734 get737() {
    return _7_3_7;
  }


  public void set737(InlineResponse20019734 _7_3_7) {
    this._7_3_7 = _7_3_7;
  }


  public InlineResponse20019 _7_3_21(InlineResponse200197316 _7_3_21) {
    
    this._7_3_21 = _7_3_21;
    return this;
  }

   /**
   * Get _7_3_21
   * @return _7_3_21
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse200197316 get7321() {
    return _7_3_21;
  }


  public void set7321(InlineResponse200197316 _7_3_21) {
    this._7_3_21 = _7_3_21;
  }


  public InlineResponse20019 _7_3_3(InlineResponse20019710 _7_3_3) {
    
    this._7_3_3 = _7_3_3;
    return this;
  }

   /**
   * Get _7_3_3
   * @return _7_3_3
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse20019710 get733() {
    return _7_3_3;
  }


  public void set733(InlineResponse20019710 _7_3_3) {
    this._7_3_3 = _7_3_3;
  }


  public InlineResponse20019 _7_3_18(InlineResponse200197316 _7_3_18) {
    
    this._7_3_18 = _7_3_18;
    return this;
  }

   /**
   * Get _7_3_18
   * @return _7_3_18
  **/
  @ApiModelProperty(required = true, value = "")

  public InlineResponse200197316 get7318() {
    return _7_3_18;
  }


  public void set7318(InlineResponse200197316 _7_3_18) {
    this._7_3_18 = _7_3_18;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20019 inlineResponse20019 = (InlineResponse20019) o;
    return Objects.equals(this._7_3_4, inlineResponse20019._7_3_4) &&
        Objects.equals(this._7_3_11, inlineResponse20019._7_3_11) &&
        Objects.equals(this._7_3_16, inlineResponse20019._7_3_16) &&
        Objects.equals(this._7_1_0, inlineResponse20019._7_1_0) &&
        Objects.equals(this._7_3_22, inlineResponse20019._7_3_22) &&
        Objects.equals(this._7_3_23, inlineResponse20019._7_3_23) &&
        Objects.equals(this._7_3_8, inlineResponse20019._7_3_8) &&
        Objects.equals(this._7_3_12, inlineResponse20019._7_3_12) &&
        Objects.equals(this._7_2_1, inlineResponse20019._7_2_1) &&
        Objects.equals(this._7_3_13, inlineResponse20019._7_3_13) &&
        Objects.equals(this._7_0_0, inlineResponse20019._7_0_0) &&
        Objects.equals(this._7_3_17, inlineResponse20019._7_3_17) &&
        Objects.equals(this._7_3_5, inlineResponse20019._7_3_5) &&
        Objects.equals(this._7_3_20, inlineResponse20019._7_3_20) &&
        Objects.equals(this._7_3_2, inlineResponse20019._7_3_2) &&
        Objects.equals(this._7_3_9, inlineResponse20019._7_3_9) &&
        Objects.equals(this._7_3_24, inlineResponse20019._7_3_24) &&
        Objects.equals(this._7_2_0, inlineResponse20019._7_2_0) &&
        Objects.equals(this._7_3_0, inlineResponse20019._7_3_0) &&
        Objects.equals(this._7_3_14, inlineResponse20019._7_3_14) &&
        Objects.equals(this._7_3_6, inlineResponse20019._7_3_6) &&
        Objects.equals(this._7_3_1, inlineResponse20019._7_3_1) &&
        Objects.equals(this._7_3_19, inlineResponse20019._7_3_19) &&
        Objects.equals(this._7_3_15, inlineResponse20019._7_3_15) &&
        Objects.equals(this._7_3_10, inlineResponse20019._7_3_10) &&
        Objects.equals(this._7_3_7, inlineResponse20019._7_3_7) &&
        Objects.equals(this._7_3_21, inlineResponse20019._7_3_21) &&
        Objects.equals(this._7_3_3, inlineResponse20019._7_3_3) &&
        Objects.equals(this._7_3_18, inlineResponse20019._7_3_18);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_7_3_4, _7_3_11, _7_3_16, _7_1_0, _7_3_22, _7_3_23, _7_3_8, _7_3_12, _7_2_1, _7_3_13, _7_0_0, _7_3_17, _7_3_5, _7_3_20, _7_3_2, _7_3_9, _7_3_24, _7_2_0, _7_3_0, _7_3_14, _7_3_6, _7_3_1, _7_3_19, _7_3_15, _7_3_10, _7_3_7, _7_3_21, _7_3_3, _7_3_18);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20019 {\n");
    sb.append("    _7_3_4: ").append(toIndentedString(_7_3_4)).append("\n");
    sb.append("    _7_3_11: ").append(toIndentedString(_7_3_11)).append("\n");
    sb.append("    _7_3_16: ").append(toIndentedString(_7_3_16)).append("\n");
    sb.append("    _7_1_0: ").append(toIndentedString(_7_1_0)).append("\n");
    sb.append("    _7_3_22: ").append(toIndentedString(_7_3_22)).append("\n");
    sb.append("    _7_3_23: ").append(toIndentedString(_7_3_23)).append("\n");
    sb.append("    _7_3_8: ").append(toIndentedString(_7_3_8)).append("\n");
    sb.append("    _7_3_12: ").append(toIndentedString(_7_3_12)).append("\n");
    sb.append("    _7_2_1: ").append(toIndentedString(_7_2_1)).append("\n");
    sb.append("    _7_3_13: ").append(toIndentedString(_7_3_13)).append("\n");
    sb.append("    _7_0_0: ").append(toIndentedString(_7_0_0)).append("\n");
    sb.append("    _7_3_17: ").append(toIndentedString(_7_3_17)).append("\n");
    sb.append("    _7_3_5: ").append(toIndentedString(_7_3_5)).append("\n");
    sb.append("    _7_3_20: ").append(toIndentedString(_7_3_20)).append("\n");
    sb.append("    _7_3_2: ").append(toIndentedString(_7_3_2)).append("\n");
    sb.append("    _7_3_9: ").append(toIndentedString(_7_3_9)).append("\n");
    sb.append("    _7_3_24: ").append(toIndentedString(_7_3_24)).append("\n");
    sb.append("    _7_2_0: ").append(toIndentedString(_7_2_0)).append("\n");
    sb.append("    _7_3_0: ").append(toIndentedString(_7_3_0)).append("\n");
    sb.append("    _7_3_14: ").append(toIndentedString(_7_3_14)).append("\n");
    sb.append("    _7_3_6: ").append(toIndentedString(_7_3_6)).append("\n");
    sb.append("    _7_3_1: ").append(toIndentedString(_7_3_1)).append("\n");
    sb.append("    _7_3_19: ").append(toIndentedString(_7_3_19)).append("\n");
    sb.append("    _7_3_15: ").append(toIndentedString(_7_3_15)).append("\n");
    sb.append("    _7_3_10: ").append(toIndentedString(_7_3_10)).append("\n");
    sb.append("    _7_3_7: ").append(toIndentedString(_7_3_7)).append("\n");
    sb.append("    _7_3_21: ").append(toIndentedString(_7_3_21)).append("\n");
    sb.append("    _7_3_3: ").append(toIndentedString(_7_3_3)).append("\n");
    sb.append("    _7_3_18: ").append(toIndentedString(_7_3_18)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

