=begin
#untitled API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5170

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DefaultApi)
    end
  end

  # unit tests for request4_q1q_u3c4dk
  # Get an Edge Router
  # @param edge_router_id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20012]
  describe 'request4_q1q_u3c4dk test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request9s_du_piz_ciu
  # Create an Endpoint
  # @param [Hash] opts the optional parameters
  # @option opts [InlineObject5] :inline_object5 
  # @return [InlineResponse2008]
  describe 'request9s_du_piz_ciu test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_a8syya_p_znw
  # Get the list of Network product versions
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20019]
  describe 'request_a8syya_p_znw test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_auar_cs_ihk_j
  # Get the registration information for an Edge Router
  # @param edge_router_id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2009]
  describe 'request_auar_cs_ihk_j test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_ay_fh_a_qd5pn
  # Get an Endpoint
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2007]
  describe 'request_ay_fh_a_qd5pn test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_btgg9_zl_c0e
  # Get an Edge Router Policy
  # @param edge_router_policy_id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2004EmbeddedEdgeRouterPolicyList]
  describe 'request_btgg9_zl_c0e test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_e1_iex_rfv_zg
  # Get the list of Services
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2003]
  describe 'request_e1_iex_rfv_zg test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_f_wl_fmqidpx
  # Create a Network
  # @param [Hash] opts the optional parameters
  # @option opts [InlineObject] :inline_object 
  # @return [InlineResponse202]
  describe 'request_f_wl_fmqidpx test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_gij_vc_eo_ml_m
  # Get the list of AppWANs
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2006]
  describe 'request_gij_vc_eo_ml_m test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_hp1b9_gi_lax
  # Get an Edge Router Policy
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2004]
  describe 'request_hp1b9_gi_lax test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_iaj_vi_y_lviu
  # Delete a Network
  # @param network_id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2024]
  describe 'request_iaj_vi_y_lviu test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_k9aj_dj8v_us
  # Get the list of Network Groups
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20017]
  describe 'request_k9aj_dj8v_us test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_kke_r9g_ny25
  # Get an AppWAN
  # @param app_wan_id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse200]
  describe 'request_kke_r9g_ny25 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_lg_kx_u4ph9t
  # Create an Edge Router Policy
  # @param [Hash] opts the optional parameters
  # @option opts [InlineObject2] :inline_object2 
  # @return [InlineResponse2004EmbeddedEdgeRouterPolicyList]
  describe 'request_lg_kx_u4ph9t test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_lo_xf_q_ss8_ge
  # Get a Network Configuration profile
  # e.g. small, medium, large
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20015]
  describe 'request_lo_xf_q_ss8_ge test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_lopo_ftq4ih
  # Create a Service
  # @param [Hash] opts the optional parameters
  # @option opts [InlineObject1] :inline_object1 
  # @return [InlineResponse2021]
  describe 'request_lopo_ftq4ih test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_mpy_yt_ii_s6x
  # Get the identity of the caller&#39;s API account
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20016]
  describe 'request_mpy_yt_ii_s6x test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_n6_gjg_plo4v
  # Get an Organization
  # @param organization_id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20014]
  describe 'request_n6_gjg_plo4v test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_n_xo_v6_k2f0_q
  # Create an AppWAN
  # @param [Hash] opts the optional parameters
  # @option opts [InlineObject4] :inline_object4 
  # @return [InlineResponse200]
  describe 'request_n_xo_v6_k2f0_q test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_oi_i_af_x2_v_us
  # Get the list of Networks
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2001]
  describe 'request_oi_i_af_x2_v_us test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_p_baai_o3_b0d
  # Delete a Service
  # @param service_id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2022]
  describe 'request_p_baai_o3_b0d test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_py_r6a_up5mi
  # Create an Edge Router
  # @param [Hash] opts the optional parameters
  # @option opts [InlineObject6] :inline_object6 
  # @return [InlineResponse2025]
  describe 'request_py_r6a_up5mi test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_q0b3cb_dw8_s
  # Get the list of Posture Checks
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20010]
  describe 'request_q0b3cb_dw8_s test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_teq_m_ge_er5_f
  # Get a Network
  # @param network_id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20013]
  describe 'request_teq_m_ge_er5_f test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_tsyuwl_aej_k
  # Get an Endpoint
  # @param endpoint_id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2007EmbeddedEndpointList]
  describe 'request_tsyuwl_aej_k test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_v_iz_b1k6_uqb
  # Change some properties of a Service
  # @param service_id 
  # @param [Hash] opts the optional parameters
  # @option opts [InlineObject3] :inline_object3 
  # @return [InlineResponse2023]
  describe 'request_v_iz_b1k6_uqb test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_ve_jcbur9i_o
  # Get a Network Group
  # @param network_group_id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20011]
  describe 'request_ve_jcbur9i_o test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_vfua_d_me_trp
  # Get the list of data centers
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2002]
  describe 'request_vfua_d_me_trp test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_y_lsf4m9_ttt
  # Get a Service
  # @param service_id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2005]
  describe 'request_y_lsf4m9_ttt test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_yhz_d_aw1_ks4
  # Get an Edge Router
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20018]
  describe 'request_yhz_d_aw1_ks4 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
