# builds netfoundry/ansible
FROM netfoundry/python:latest

RUN pip install ansible yq
RUN ansible-galaxy collection install --collections-path /usr/share/ansible/collections netfoundry.platform
CMD ["bash"]
