FROM netfoundry/python:demo

#RUN pip install --index-url https://test.pypi.org/simple/ --no-deps --upgrade netfoundry
COPY ./entrypoint-test.sh .
ENTRYPOINT [ "./entrypoint-test.sh" ]
CMD python3 -m netfoundry.demo ${NETWORK_NAME} privateServices
