# coding: utf-8

"""
    untitled API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5170
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response20018 import InlineResponse20018  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse20018(unittest.TestCase):
    """InlineResponse20018 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse20018
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response20018.InlineResponse20018()  # noqa: E501
        if include_optional :
            return InlineResponse20018(
                embedded = openapi_client.models.inline_response_200_18__embedded.inline_response_200_18__embedded(
                    edge_router_list = [
                        openapi_client.models.inline_response_200_12.inline_response_200_12(
                            deleted_at = null, 
                            network_id = '0', 
                            name = '0', 
                            updated_at = '0', 
                            provider = null, 
                            online = True, 
                            ziti_id = '0', 
                            user_data = null, 
                            owner_identity_id = '0', 
                            attributes = [
                                '0'
                                ], 
                            provider_id = null, 
                            jwt = null, 
                            id = '0', 
                            ip_address = null, 
                            status = '0', 
                            host_id = null, 
                            created_at = '0', 
                            created_by = '0', 
                            deleted_by = null, 
                            location_metadata_id = null, 
                            link_listener = True, 
                            data_center_id = null, 
                            verified = True, 
                            _links = openapi_client.models.inline_response_200__links.inline_response_200__links(
                                network = openapi_client.models.inline_response_200__links_network.inline_response_200__links_network(
                                    href = '0', 
                                    profile = '0', ), 
                                self = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                                    href = '0', ), ), )
                        ], ), 
                links = openapi_client.models.inline_response_200_2__embedded__links.inline_response_200_2__embedded__links(
                    self = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), ), 
                page = openapi_client.models.inline_response_200_1_page.inline_response_200_1_page(
                    number = 1.337, 
                    size = 1.337, 
                    total_elements = 1.337, 
                    total_pages = 1.337, )
            )
        else :
            return InlineResponse20018(
                links = openapi_client.models.inline_response_200_2__embedded__links.inline_response_200_2__embedded__links(
                    self = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), ),
                page = openapi_client.models.inline_response_200_1_page.inline_response_200_1_page(
                    number = 1.337, 
                    size = 1.337, 
                    total_elements = 1.337, 
                    total_pages = 1.337, ),
        )

    def testInlineResponse20018(self):
        """Test InlineResponse20018"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
