# coding: utf-8

"""
    untitled API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5170
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response2001_embedded_network_list import InlineResponse2001EmbeddedNetworkList  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse2001EmbeddedNetworkList(unittest.TestCase):
    """InlineResponse2001EmbeddedNetworkList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse2001EmbeddedNetworkList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response2001_embedded_network_list.InlineResponse2001EmbeddedNetworkList()  # noqa: E501
        if include_optional :
            return InlineResponse2001EmbeddedNetworkList(
                deleted_at = null, 
                name = '0', 
                updated_at = '0', 
                size = '0', 
                owner_identity_id = '0', 
                product_version = '0', 
                network_group_id = '0', 
                id = '0', 
                status = '0', 
                created_at = '0', 
                created_by = '0', 
                deleted_by = null, 
                network_controller = null, 
                o365_breakout_category = '0', 
                links = openapi_client.models.inline_response_200_1__embedded__links.inline_response_200_1__embedded__links(
                    services = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), 
                    networks = openapi_client.models.inline_response_200__links_network.inline_response_200__links_network(
                        href = '0', 
                        profile = '0', ), 
                    app_wans = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), 
                    endpoints = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), 
                    certificate_authorities = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), 
                    self = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), 
                    process_executions = openapi_client.models.inline_response_200__links_network.inline_response_200__links_network(
                        href = '0', 
                        profile = '0', ), 
                    network_controllers = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), 
                    posture_checks = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), 
                    edge_routers = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), 
                    edge_router_policies = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), )
            )
        else :
            return InlineResponse2001EmbeddedNetworkList(
                deleted_at = null,
                name = '0',
                updated_at = '0',
                size = '0',
                owner_identity_id = '0',
                product_version = '0',
                network_group_id = '0',
                id = '0',
                status = '0',
                created_at = '0',
                created_by = '0',
                deleted_by = null,
                o365_breakout_category = '0',
                links = openapi_client.models.inline_response_200_1__embedded__links.inline_response_200_1__embedded__links(
                    services = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), 
                    networks = openapi_client.models.inline_response_200__links_network.inline_response_200__links_network(
                        href = '0', 
                        profile = '0', ), 
                    app_wans = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), 
                    endpoints = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), 
                    certificate_authorities = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), 
                    self = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), 
                    process_executions = openapi_client.models.inline_response_200__links_network.inline_response_200__links_network(
                        href = '0', 
                        profile = '0', ), 
                    network_controllers = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), 
                    posture_checks = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), 
                    edge_routers = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), 
                    edge_router_policies = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), ),
        )

    def testInlineResponse2001EmbeddedNetworkList(self):
        """Test InlineResponse2001EmbeddedNetworkList"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
