# coding: utf-8

"""
    untitled API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5170
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response2007 import InlineResponse2007  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse2007(unittest.TestCase):
    """InlineResponse2007 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse2007
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response2007.InlineResponse2007()  # noqa: E501
        if include_optional :
            return InlineResponse2007(
                embedded = openapi_client.models.inline_response_200_7__embedded.inline_response_200_7__embedded(
                    endpoint_list = [
                        openapi_client.models.inline_response_200_7__embedded_endpoint_list.inline_response_200_7__embedded_endpointList(
                            mfa_enabled = True, 
                            deleted_at = null, 
                            network_id = '0', 
                            name = '0', 
                            updated_at = '0', 
                            sync_id = null, 
                            session_identity_id = null, 
                            os_release = null, 
                            sync_resource_id = null, 
                            ziti_id = '0', 
                            app_version = null, 
                            branch = null, 
                            os = null, 
                            owner_identity_id = '0', 
                            has_edge_router_connection = True, 
                            attributes = [
                                '0'
                                ], 
                            has_api_session = True, 
                            revision = null, 
                            version = null, 
                            jwt = null, 
                            id = '0', 
                            session_active = True, 
                            jwt_expires_at = null, 
                            created_at = '0', 
                            arch = null, 
                            created_by = '0', 
                            deleted_by = null, 
                            type = null, 
                            os_version = null, 
                            app_id = null, 
                            _links = openapi_client.models.inline_response_200__links.inline_response_200__links(
                                network = openapi_client.models.inline_response_200__links_network.inline_response_200__links_network(
                                    href = '0', 
                                    profile = '0', ), 
                                self = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                                    href = '0', ), ), )
                        ], ), 
                links = openapi_client.models.inline_response_200_2__embedded__links.inline_response_200_2__embedded__links(
                    self = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), ), 
                page = openapi_client.models.inline_response_200_1_page.inline_response_200_1_page(
                    number = 1.337, 
                    size = 1.337, 
                    total_elements = 1.337, 
                    total_pages = 1.337, )
            )
        else :
            return InlineResponse2007(
                links = openapi_client.models.inline_response_200_2__embedded__links.inline_response_200_2__embedded__links(
                    self = openapi_client.models.inline_response_200__links_self.inline_response_200__links_self(
                        href = '0', ), ),
                page = openapi_client.models.inline_response_200_1_page.inline_response_200_1_page(
                    number = 1.337, 
                    size = 1.337, 
                    total_elements = 1.337, 
                    total_pages = 1.337, ),
        )

    def testInlineResponse2007(self):
        """Test InlineResponse2007"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
