/**
 * untitled API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5227
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2001Page model module.
 * @module model/InlineResponse2001Page
 * @version 5227
 */
class InlineResponse2001Page {
    /**
     * Constructs a new <code>InlineResponse2001Page</code>.
     * @alias module:model/InlineResponse2001Page
     * @param _number {Number} 
     * @param size {Number} 
     * @param totalElements {Number} 
     * @param totalPages {Number} 
     */
    constructor(_number, size, totalElements, totalPages) { 
        
        InlineResponse2001Page.initialize(this, _number, size, totalElements, totalPages);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, _number, size, totalElements, totalPages) { 
        obj['number'] = _number;
        obj['size'] = size;
        obj['totalElements'] = totalElements;
        obj['totalPages'] = totalPages;
    }

    /**
     * Constructs a <code>InlineResponse2001Page</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2001Page} obj Optional instance to populate.
     * @return {module:model/InlineResponse2001Page} The populated <code>InlineResponse2001Page</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2001Page();

            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'Number');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('totalElements')) {
                obj['totalElements'] = ApiClient.convertToType(data['totalElements'], 'Number');
            }
            if (data.hasOwnProperty('totalPages')) {
                obj['totalPages'] = ApiClient.convertToType(data['totalPages'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} number
 */
InlineResponse2001Page.prototype['number'] = undefined;

/**
 * @member {Number} size
 */
InlineResponse2001Page.prototype['size'] = undefined;

/**
 * @member {Number} totalElements
 */
InlineResponse2001Page.prototype['totalElements'] = undefined;

/**
 * @member {Number} totalPages
 */
InlineResponse2001Page.prototype['totalPages'] = undefined;






export default InlineResponse2001Page;

