# untitled API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 5229
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Default operations
#' @description openapi.Default
#' @format An \code{R6Class} generator object
#' @field apiClient Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ Request4Q1qU3c4dk } \emph{ Get an Edge Router }
#' 
#'
#' \itemize{
#' \item \emph{ @param } edge.router.id character
#' \item \emph{ @returnType } \link{InlineResponse20012} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse20012 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ Request9sDuPizCiu } \emph{ Create an Endpoint }
#' 
#'
#' \itemize{
#' \item \emph{ @param } inline.object5 \link{InlineObject5}
#' \item \emph{ @returnType } \link{InlineResponse2008} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse2008 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestA8syyaPZnw } \emph{ Get the list of Network product versions }
#' 
#'
#' \itemize{
#' \item \emph{ @returnType } \link{InlineResponse20019} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse20019 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestAYFhAQd5pn } \emph{ Get an Endpoint }
#' 
#'
#' \itemize{
#' \item \emph{ @returnType } \link{InlineResponse2007} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse2007 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestAuarCsIhkJ } \emph{ Get the registration information for an Edge Router }
#' 
#'
#' \itemize{
#' \item \emph{ @param } edge.router.id character
#' \item \emph{ @returnType } \link{InlineResponse2009} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse2009 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestBtgg9ZlC0e } \emph{ Get an Edge Router Policy }
#' 
#'
#' \itemize{
#' \item \emph{ @param } edge.router.policy.id character
#' \item \emph{ @returnType } \link{InlineResponse2004EmbeddedEdgeRouterPolicyList} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse2004EmbeddedEdgeRouterPolicyList 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestE1IexRfvZg } \emph{ Get the list of Services }
#' 
#'
#' \itemize{
#' \item \emph{ @returnType } \link{InlineResponse2003} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse2003 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestFWlFMQIDPX } \emph{ Create a Network }
#' 
#'
#' \itemize{
#' \item \emph{ @param } inline.object \link{InlineObject}
#' \item \emph{ @returnType } \link{InlineResponse202} \cr
#'
#'
#' \item status code : 202 | 
#'
#' \item return type : InlineResponse202 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestGijVCEoMlM } \emph{ Get the list of AppWANs }
#' 
#'
#' \itemize{
#' \item \emph{ @returnType } \link{InlineResponse2006} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse2006 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestHp1b9GiLax } \emph{ Get an Edge Router Policy }
#' 
#'
#' \itemize{
#' \item \emph{ @returnType } \link{InlineResponse2004} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse2004 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestIAJViYLviu } \emph{ Delete a Network }
#' 
#'
#' \itemize{
#' \item \emph{ @param } network.id character
#' \item \emph{ @returnType } \link{InlineResponse2024} \cr
#'
#'
#' \item status code : 202 | 
#'
#' \item return type : InlineResponse2024 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestK9ajDJ8vUS } \emph{ Get the list of Network Groups }
#' 
#'
#' \itemize{
#' \item \emph{ @returnType } \link{InlineResponse20017} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse20017 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestKkeR9gNy25 } \emph{ Get an AppWAN }
#' 
#'
#' \itemize{
#' \item \emph{ @param } app.wan.id character
#' \item \emph{ @returnType } \link{InlineResponse200} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse200 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestLOXfQSs8GE } \emph{ Get a Network Configuration profile }
#' e.g. small, medium, large
#'
#' \itemize{
#' \item \emph{ @returnType } \link{InlineResponse20015} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse20015 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestLgKxU4ph9t } \emph{ Create an Edge Router Policy }
#' 
#'
#' \itemize{
#' \item \emph{ @param } inline.object2 \link{InlineObject2}
#' \item \emph{ @returnType } \link{InlineResponse2004EmbeddedEdgeRouterPolicyList} \cr
#'
#'
#' \item status code : 202 | 
#'
#' \item return type : InlineResponse2004EmbeddedEdgeRouterPolicyList 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestLopoFtq4ih } \emph{ Create a Service }
#' 
#'
#' \itemize{
#' \item \emph{ @param } inline.object1 \link{InlineObject1}
#' \item \emph{ @returnType } \link{InlineResponse2021} \cr
#'
#'
#' \item status code : 202 | 
#'
#' \item return type : InlineResponse2021 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestMpyYtIiS6x } \emph{ Get the identity of the caller&#39;s API account }
#' 
#'
#' \itemize{
#' \item \emph{ @returnType } \link{InlineResponse20016} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse20016 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestN6GjgPLO4v } \emph{ Get an Organization }
#' 
#'
#' \itemize{
#' \item \emph{ @param } organization.id character
#' \item \emph{ @returnType } \link{InlineResponse20014} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse20014 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 502 | 
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestNXoV6K2f0Q } \emph{ Create an AppWAN }
#' 
#'
#' \itemize{
#' \item \emph{ @param } inline.object4 \link{InlineObject4}
#' \item \emph{ @returnType } \link{InlineResponse200} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse200 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestOiIAfX2VUs } \emph{ Get the list of Networks }
#' 
#'
#' \itemize{
#' \item \emph{ @returnType } \link{InlineResponse2001} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse2001 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestPBaaiO3B0d } \emph{ Delete a Service }
#' 
#'
#' \itemize{
#' \item \emph{ @param } service.id character
#' \item \emph{ @returnType } \link{InlineResponse2022} \cr
#'
#'
#' \item status code : 202 | 
#'
#' \item return type : InlineResponse2022 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | 
#'
#' \item return type : InlineResponse500 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestPyR6aUP5mi } \emph{ Create an Edge Router }
#' 
#'
#' \itemize{
#' \item \emph{ @param } inline.object6 \link{InlineObject6}
#' \item \emph{ @returnType } \link{InlineResponse2025} \cr
#'
#'
#' \item status code : 202 | 
#'
#' \item return type : InlineResponse2025 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestQ0b3cbDW8S } \emph{ Get the list of Posture Checks }
#' 
#'
#' \itemize{
#' \item \emph{ @returnType } \link{InlineResponse20010} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse20010 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestTeqMGeER5F } \emph{ Get a Network }
#' 
#'
#' \itemize{
#' \item \emph{ @param } network.id character
#' \item \emph{ @returnType } \link{InlineResponse20013} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse20013 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | 
#'
#' \item return type : InlineResponse5001 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestTsyuwlAejK } \emph{ Get an Endpoint }
#' 
#'
#' \itemize{
#' \item \emph{ @param } endpoint.id character
#' \item \emph{ @returnType } \link{InlineResponse2007EmbeddedEndpointList} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse2007EmbeddedEndpointList 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestVIzB1k6Uqb } \emph{ Change some properties of a Service }
#' 
#'
#' \itemize{
#' \item \emph{ @param } service.id character
#' \item \emph{ @param } inline.object3 \link{InlineObject3}
#' \item \emph{ @returnType } \link{InlineResponse2023} \cr
#'
#'
#' \item status code : 202 | 
#'
#' \item return type : InlineResponse2023 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestVeJCBUR9iO } \emph{ Get a Network Group }
#' 
#'
#' \itemize{
#' \item \emph{ @param } network.group.id character
#' \item \emph{ @returnType } \link{InlineResponse20011} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse20011 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestVfuaDMeTRP } \emph{ Get the list of data centers }
#' 
#'
#' \itemize{
#' \item \emph{ @returnType } \link{InlineResponse2002} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse2002 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestYLsf4m9TTT } \emph{ Get a Service }
#' 
#'
#' \itemize{
#' \item \emph{ @param } service.id character
#' \item \emph{ @returnType } \link{InlineResponse2005} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse2005 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RequestYhzDAw1Ks4 } \emph{ Get an Edge Router }
#' 
#'
#' \itemize{
#' \item \emph{ @returnType } \link{InlineResponse20018} \cr
#'
#'
#' \item status code : 200 | 
#'
#' \item return type : InlineResponse20018 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  Request4Q1qU3c4dk  ####################
#'
#' library(openapi)
#' var.edge.router.id <- 'edge.router.id_example' # character | 
#'
#' #Get an Edge Router
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$Request4Q1qU3c4dk(var.edge.router.id)
#'
#'
#' ####################  Request9sDuPizCiu  ####################
#'
#' library(openapi)
#' var.inline.object5 <- InlineObject5$new() # InlineObject5 | 
#'
#' #Create an Endpoint
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$Request9sDuPizCiu(inline.object5=var.inline.object5)
#'
#'
#' ####################  RequestA8syyaPZnw  ####################
#'
#' library(openapi)
#'
#' #Get the list of Network product versions
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestA8syyaPZnw()
#'
#'
#' ####################  RequestAYFhAQd5pn  ####################
#'
#' library(openapi)
#'
#' #Get an Endpoint
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestAYFhAQd5pn()
#'
#'
#' ####################  RequestAuarCsIhkJ  ####################
#'
#' library(openapi)
#' var.edge.router.id <- 'edge.router.id_example' # character | 
#'
#' #Get the registration information for an Edge Router
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestAuarCsIhkJ(var.edge.router.id)
#'
#'
#' ####################  RequestBtgg9ZlC0e  ####################
#'
#' library(openapi)
#' var.edge.router.policy.id <- 'edge.router.policy.id_example' # character | 
#'
#' #Get an Edge Router Policy
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestBtgg9ZlC0e(var.edge.router.policy.id)
#'
#'
#' ####################  RequestE1IexRfvZg  ####################
#'
#' library(openapi)
#'
#' #Get the list of Services
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestE1IexRfvZg()
#'
#'
#' ####################  RequestFWlFMQIDPX  ####################
#'
#' library(openapi)
#' var.inline.object <- InlineObject$new() # InlineObject | 
#'
#' #Create a Network
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestFWlFMQIDPX(inline.object=var.inline.object)
#'
#'
#' ####################  RequestGijVCEoMlM  ####################
#'
#' library(openapi)
#'
#' #Get the list of AppWANs
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestGijVCEoMlM()
#'
#'
#' ####################  RequestHp1b9GiLax  ####################
#'
#' library(openapi)
#'
#' #Get an Edge Router Policy
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestHp1b9GiLax()
#'
#'
#' ####################  RequestIAJViYLviu  ####################
#'
#' library(openapi)
#' var.network.id <- 'network.id_example' # character | 
#'
#' #Delete a Network
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestIAJViYLviu(var.network.id)
#'
#'
#' ####################  RequestK9ajDJ8vUS  ####################
#'
#' library(openapi)
#'
#' #Get the list of Network Groups
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestK9ajDJ8vUS()
#'
#'
#' ####################  RequestKkeR9gNy25  ####################
#'
#' library(openapi)
#' var.app.wan.id <- 'app.wan.id_example' # character | 
#'
#' #Get an AppWAN
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestKkeR9gNy25(var.app.wan.id)
#'
#'
#' ####################  RequestLOXfQSs8GE  ####################
#'
#' library(openapi)
#'
#' #Get a Network Configuration profile
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestLOXfQSs8GE()
#'
#'
#' ####################  RequestLgKxU4ph9t  ####################
#'
#' library(openapi)
#' var.inline.object2 <- InlineObject2$new() # InlineObject2 | 
#'
#' #Create an Edge Router Policy
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestLgKxU4ph9t(inline.object2=var.inline.object2)
#'
#'
#' ####################  RequestLopoFtq4ih  ####################
#'
#' library(openapi)
#' var.inline.object1 <- InlineObject1$new() # InlineObject1 | 
#'
#' #Create a Service
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestLopoFtq4ih(inline.object1=var.inline.object1)
#'
#'
#' ####################  RequestMpyYtIiS6x  ####################
#'
#' library(openapi)
#'
#' #Get the identity of the caller's API account
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestMpyYtIiS6x()
#'
#'
#' ####################  RequestN6GjgPLO4v  ####################
#'
#' library(openapi)
#' var.organization.id <- 'organization.id_example' # character | 
#'
#' #Get an Organization
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestN6GjgPLO4v(var.organization.id)
#'
#'
#' ####################  RequestNXoV6K2f0Q  ####################
#'
#' library(openapi)
#' var.inline.object4 <- InlineObject4$new() # InlineObject4 | 
#'
#' #Create an AppWAN
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestNXoV6K2f0Q(inline.object4=var.inline.object4)
#'
#'
#' ####################  RequestOiIAfX2VUs  ####################
#'
#' library(openapi)
#'
#' #Get the list of Networks
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestOiIAfX2VUs()
#'
#'
#' ####################  RequestPBaaiO3B0d  ####################
#'
#' library(openapi)
#' var.service.id <- 'service.id_example' # character | 
#'
#' #Delete a Service
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestPBaaiO3B0d(var.service.id)
#'
#'
#' ####################  RequestPyR6aUP5mi  ####################
#'
#' library(openapi)
#' var.inline.object6 <- InlineObject6$new() # InlineObject6 | 
#'
#' #Create an Edge Router
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestPyR6aUP5mi(inline.object6=var.inline.object6)
#'
#'
#' ####################  RequestQ0b3cbDW8S  ####################
#'
#' library(openapi)
#'
#' #Get the list of Posture Checks
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestQ0b3cbDW8S()
#'
#'
#' ####################  RequestTeqMGeER5F  ####################
#'
#' library(openapi)
#' var.network.id <- 'network.id_example' # character | 
#'
#' #Get a Network
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestTeqMGeER5F(var.network.id)
#'
#'
#' ####################  RequestTsyuwlAejK  ####################
#'
#' library(openapi)
#' var.endpoint.id <- 'endpoint.id_example' # character | 
#'
#' #Get an Endpoint
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestTsyuwlAejK(var.endpoint.id)
#'
#'
#' ####################  RequestVIzB1k6Uqb  ####################
#'
#' library(openapi)
#' var.service.id <- 'service.id_example' # character | 
#' var.inline.object3 <- InlineObject3$new() # InlineObject3 | 
#'
#' #Change some properties of a Service
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestVIzB1k6Uqb(var.service.id, inline.object3=var.inline.object3)
#'
#'
#' ####################  RequestVeJCBUR9iO  ####################
#'
#' library(openapi)
#' var.network.group.id <- 'network.group.id_example' # character | 
#'
#' #Get a Network Group
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestVeJCBUR9iO(var.network.group.id)
#'
#'
#' ####################  RequestVfuaDMeTRP  ####################
#'
#' library(openapi)
#'
#' #Get the list of data centers
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestVfuaDMeTRP()
#'
#'
#' ####################  RequestYLsf4m9TTT  ####################
#'
#' library(openapi)
#' var.service.id <- 'service.id_example' # character | 
#'
#' #Get a Service
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestYLsf4m9TTT(var.service.id)
#'
#'
#' ####################  RequestYhzDAw1Ks4  ####################
#'
#' library(openapi)
#'
#' #Get an Edge Router
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$RequestYhzDAw1Ks4()
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom caTools base64encode
#' @export
DefaultApi <- R6::R6Class(
  'DefaultApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    Request4Q1qU3c4dk = function(edge.router.id, ...){
      apiResponse <- self$Request4Q1qU3c4dkWithHttpInfo(edge.router.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    Request4Q1qU3c4dkWithHttpInfo = function(edge.router.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`edge.router.id`)) {
        stop("Missing required parameter `edge.router.id`.")
      }

      urlPath <- "/core/v2/edge-routers/{edgeRouterId}"
      if (!missing(`edge.router.id`)) {
        urlPath <- gsub(paste0("\\{", "edgeRouterId", "\\}"), URLencode(as.character(`edge.router.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse20012", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    Request9sDuPizCiu = function(inline.object5=NULL, ...){
      apiResponse <- self$Request9sDuPizCiuWithHttpInfo(inline.object5, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    Request9sDuPizCiuWithHttpInfo = function(inline.object5=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (!missing(`inline.object5`)) {
        body <- `inline.object5`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/core/v2/endpoints"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse2008", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestA8syyaPZnw = function(...){
      apiResponse <- self$RequestA8syyaPZnwWithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestA8syyaPZnwWithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      urlPath <- "/product-metadata/v2/download-urls.json"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse20019", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestAYFhAQd5pn = function(...){
      apiResponse <- self$RequestAYFhAQd5pnWithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestAYFhAQd5pnWithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      urlPath <- "/core/v2/endpoints"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse2007", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestAuarCsIhkJ = function(edge.router.id, ...){
      apiResponse <- self$RequestAuarCsIhkJWithHttpInfo(edge.router.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestAuarCsIhkJWithHttpInfo = function(edge.router.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`edge.router.id`)) {
        stop("Missing required parameter `edge.router.id`.")
      }

      urlPath <- "/core/v2/edge-routers/{edgeRouterId}/registration-key"
      if (!missing(`edge.router.id`)) {
        urlPath <- gsub(paste0("\\{", "edgeRouterId", "\\}"), URLencode(as.character(`edge.router.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse2009", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestBtgg9ZlC0e = function(edge.router.policy.id, ...){
      apiResponse <- self$RequestBtgg9ZlC0eWithHttpInfo(edge.router.policy.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestBtgg9ZlC0eWithHttpInfo = function(edge.router.policy.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`edge.router.policy.id`)) {
        stop("Missing required parameter `edge.router.policy.id`.")
      }

      urlPath <- "/core/v2/edge-router-policies/{edgeRouterPolicyId}"
      if (!missing(`edge.router.policy.id`)) {
        urlPath <- gsub(paste0("\\{", "edgeRouterPolicyId", "\\}"), URLencode(as.character(`edge.router.policy.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse2004EmbeddedEdgeRouterPolicyList", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestE1IexRfvZg = function(...){
      apiResponse <- self$RequestE1IexRfvZgWithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestE1IexRfvZgWithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      urlPath <- "/core/v2/services"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse2003", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestFWlFMQIDPX = function(inline.object=NULL, ...){
      apiResponse <- self$RequestFWlFMQIDPXWithHttpInfo(inline.object, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestFWlFMQIDPXWithHttpInfo = function(inline.object=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (!missing(`inline.object`)) {
        body <- `inline.object`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/core/v2/networks"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse202", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestGijVCEoMlM = function(...){
      apiResponse <- self$RequestGijVCEoMlMWithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestGijVCEoMlMWithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      urlPath <- "/core/v2/app-wans"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse2006", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestHp1b9GiLax = function(...){
      apiResponse <- self$RequestHp1b9GiLaxWithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestHp1b9GiLaxWithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      urlPath <- "/core/v2/edge-router-policies"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse2004", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestIAJViYLviu = function(network.id, ...){
      apiResponse <- self$RequestIAJViYLviuWithHttpInfo(network.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestIAJViYLviuWithHttpInfo = function(network.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`network.id`)) {
        stop("Missing required parameter `network.id`.")
      }

      urlPath <- "/core/v2/networks/{networkId}"
      if (!missing(`network.id`)) {
        urlPath <- gsub(paste0("\\{", "networkId", "\\}"), URLencode(as.character(`network.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse2024", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestK9ajDJ8vUS = function(...){
      apiResponse <- self$RequestK9ajDJ8vUSWithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestK9ajDJ8vUSWithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      urlPath <- "/rest/v1/network-groups"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse20017", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestKkeR9gNy25 = function(app.wan.id, ...){
      apiResponse <- self$RequestKkeR9gNy25WithHttpInfo(app.wan.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestKkeR9gNy25WithHttpInfo = function(app.wan.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`app.wan.id`)) {
        stop("Missing required parameter `app.wan.id`.")
      }

      urlPath <- "/core/v2/app-wans/{appWanId}"
      if (!missing(`app.wan.id`)) {
        urlPath <- gsub(paste0("\\{", "appWanId", "\\}"), URLencode(as.character(`app.wan.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse200", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestLOXfQSs8GE = function(...){
      apiResponse <- self$RequestLOXfQSs8GEWithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestLOXfQSs8GEWithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      urlPath <- "/core/v2/network-configs"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse20015", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestLgKxU4ph9t = function(inline.object2=NULL, ...){
      apiResponse <- self$RequestLgKxU4ph9tWithHttpInfo(inline.object2, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestLgKxU4ph9tWithHttpInfo = function(inline.object2=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (!missing(`inline.object2`)) {
        body <- `inline.object2`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/core/v2/edge-router-policies"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse2004EmbeddedEdgeRouterPolicyList", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestLopoFtq4ih = function(inline.object1=NULL, ...){
      apiResponse <- self$RequestLopoFtq4ihWithHttpInfo(inline.object1, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestLopoFtq4ihWithHttpInfo = function(inline.object1=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (!missing(`inline.object1`)) {
        body <- `inline.object1`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/core/v2/services"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse2021", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestMpyYtIiS6x = function(...){
      apiResponse <- self$RequestMpyYtIiS6xWithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestMpyYtIiS6xWithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      urlPath <- "/identity/v1/api-account-identities/self"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse20016", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestN6GjgPLO4v = function(organization.id, ...){
      apiResponse <- self$RequestN6GjgPLO4vWithHttpInfo(organization.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestN6GjgPLO4vWithHttpInfo = function(organization.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`organization.id`)) {
        stop("Missing required parameter `organization.id`.")
      }

      urlPath <- "/identity/v1/organizations/{organizationId}"
      if (!missing(`organization.id`)) {
        urlPath <- gsub(paste0("\\{", "organizationId", "\\}"), URLencode(as.character(`organization.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse20014", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestNXoV6K2f0Q = function(inline.object4=NULL, ...){
      apiResponse <- self$RequestNXoV6K2f0QWithHttpInfo(inline.object4, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestNXoV6K2f0QWithHttpInfo = function(inline.object4=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (!missing(`inline.object4`)) {
        body <- `inline.object4`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/core/v2/app-wans"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse200", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestOiIAfX2VUs = function(...){
      apiResponse <- self$RequestOiIAfX2VUsWithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestOiIAfX2VUsWithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      urlPath <- "/core/v2/networks"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse2001", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestPBaaiO3B0d = function(service.id, ...){
      apiResponse <- self$RequestPBaaiO3B0dWithHttpInfo(service.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestPBaaiO3B0dWithHttpInfo = function(service.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`service.id`)) {
        stop("Missing required parameter `service.id`.")
      }

      urlPath <- "/core/v2/services/{serviceId}"
      if (!missing(`service.id`)) {
        urlPath <- gsub(paste0("\\{", "serviceId", "\\}"), URLencode(as.character(`service.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse2022", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestPyR6aUP5mi = function(inline.object6=NULL, ...){
      apiResponse <- self$RequestPyR6aUP5miWithHttpInfo(inline.object6, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestPyR6aUP5miWithHttpInfo = function(inline.object6=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (!missing(`inline.object6`)) {
        body <- `inline.object6`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/core/v2/edge-routers"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse2025", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestQ0b3cbDW8S = function(...){
      apiResponse <- self$RequestQ0b3cbDW8SWithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestQ0b3cbDW8SWithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      urlPath <- "/core/v2/posture-checks"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse20010", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestTeqMGeER5F = function(network.id, ...){
      apiResponse <- self$RequestTeqMGeER5FWithHttpInfo(network.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestTeqMGeER5FWithHttpInfo = function(network.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`network.id`)) {
        stop("Missing required parameter `network.id`.")
      }

      urlPath <- "/core/v2/networks/{networkId}"
      if (!missing(`network.id`)) {
        urlPath <- gsub(paste0("\\{", "networkId", "\\}"), URLencode(as.character(`network.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse20013", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestTsyuwlAejK = function(endpoint.id, ...){
      apiResponse <- self$RequestTsyuwlAejKWithHttpInfo(endpoint.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestTsyuwlAejKWithHttpInfo = function(endpoint.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`endpoint.id`)) {
        stop("Missing required parameter `endpoint.id`.")
      }

      urlPath <- "/core/v2/endpoints/{endpointId}"
      if (!missing(`endpoint.id`)) {
        urlPath <- gsub(paste0("\\{", "endpointId", "\\}"), URLencode(as.character(`endpoint.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse2007EmbeddedEndpointList", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestVIzB1k6Uqb = function(service.id, inline.object3=NULL, ...){
      apiResponse <- self$RequestVIzB1k6UqbWithHttpInfo(service.id, inline.object3, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestVIzB1k6UqbWithHttpInfo = function(service.id, inline.object3=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`service.id`)) {
        stop("Missing required parameter `service.id`.")
      }

      if (!missing(`inline.object3`)) {
        body <- `inline.object3`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/core/v2/services/{serviceId}"
      if (!missing(`service.id`)) {
        urlPath <- gsub(paste0("\\{", "serviceId", "\\}"), URLencode(as.character(`service.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "PATCH",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse2023", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestVeJCBUR9iO = function(network.group.id, ...){
      apiResponse <- self$RequestVeJCBUR9iOWithHttpInfo(network.group.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestVeJCBUR9iOWithHttpInfo = function(network.group.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`network.group.id`)) {
        stop("Missing required parameter `network.group.id`.")
      }

      urlPath <- "/rest/v1/network-groups/{networkGroupId}"
      if (!missing(`network.group.id`)) {
        urlPath <- gsub(paste0("\\{", "networkGroupId", "\\}"), URLencode(as.character(`network.group.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse20011", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestVfuaDMeTRP = function(...){
      apiResponse <- self$RequestVfuaDMeTRPWithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestVfuaDMeTRPWithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      urlPath <- "/core/v2/data-centers"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse2002", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestYLsf4m9TTT = function(service.id, ...){
      apiResponse <- self$RequestYLsf4m9TTTWithHttpInfo(service.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestYLsf4m9TTTWithHttpInfo = function(service.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`service.id`)) {
        stop("Missing required parameter `service.id`.")
      }

      urlPath <- "/core/v2/services/{serviceId}"
      if (!missing(`service.id`)) {
        urlPath <- gsub(paste0("\\{", "serviceId", "\\}"), URLencode(as.character(`service.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse2005", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RequestYhzDAw1Ks4 = function(...){
      apiResponse <- self$RequestYhzDAw1Ks4WithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RequestYhzDAw1Ks4WithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      urlPath <- "/core/v2/edge-routers"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse20018", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    }
  )
)
