# untitled API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 5170
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse2002Embedded
#' @description InlineResponse2002Embedded Class
#' @format An \code{R6Class} generator object
#' @field dataCenters  list( \link{InlineResponse2002EmbeddedDataCenters} ) 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse2002Embedded <- R6::R6Class(
  'InlineResponse2002Embedded',
  public = list(
    `dataCenters` = NULL,
    initialize = function(`dataCenters`, ...){
      local.optional.var <- list(...)
      if (!missing(`dataCenters`)) {
        stopifnot(is.vector(`dataCenters`), length(`dataCenters`) != 0)
        sapply(`dataCenters`, function(x) stopifnot(R6::is.R6(x)))
        self$`dataCenters` <- `dataCenters`
      }
    },
    toJSON = function() {
      InlineResponse2002EmbeddedObject <- list()
      if (!is.null(self$`dataCenters`)) {
        InlineResponse2002EmbeddedObject[['dataCenters']] <-
          lapply(self$`dataCenters`, function(x) x$toJSON())
      }

      InlineResponse2002EmbeddedObject
    },
    fromJSON = function(InlineResponse2002EmbeddedJson) {
      InlineResponse2002EmbeddedObject <- jsonlite::fromJSON(InlineResponse2002EmbeddedJson)
      if (!is.null(InlineResponse2002EmbeddedObject$`dataCenters`)) {
        self$`dataCenters` <- ApiClient$new()$deserializeObj(InlineResponse2002EmbeddedObject$`dataCenters`, "array[InlineResponse2002EmbeddedDataCenters]", loadNamespace("openapi"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`dataCenters`)) {
        sprintf(
        '"dataCenters":
        [%s]
',
        paste(sapply(self$`dataCenters`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse2002EmbeddedJson) {
      InlineResponse2002EmbeddedObject <- jsonlite::fromJSON(InlineResponse2002EmbeddedJson)
      self$`dataCenters` <- ApiClient$new()$deserializeObj(InlineResponse2002EmbeddedObject$`dataCenters`, "array[InlineResponse2002EmbeddedDataCenters]", loadNamespace("openapi"))
      self
    }
  )
)
