# untitled API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 5170
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineObject5
#' @description InlineObject5 Class
#' @format An \code{R6Class} generator object
#' @field attributes  list( character ) 
#'
#' @field enrollmentMethod  \link{CoreV2EndpointsEnrollmentMethod} 
#'
#' @field name  character 
#'
#' @field networkId  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineObject5 <- R6::R6Class(
  'InlineObject5',
  public = list(
    `attributes` = NULL,
    `enrollmentMethod` = NULL,
    `name` = NULL,
    `networkId` = NULL,
    initialize = function(`attributes`, `enrollmentMethod`, `name`, `networkId`, ...){
      local.optional.var <- list(...)
      if (!missing(`attributes`)) {
        stopifnot(is.vector(`attributes`), length(`attributes`) != 0)
        sapply(`attributes`, function(x) stopifnot(is.character(x)))
        self$`attributes` <- `attributes`
      }
      if (!missing(`enrollmentMethod`)) {
        stopifnot(R6::is.R6(`enrollmentMethod`))
        self$`enrollmentMethod` <- `enrollmentMethod`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`networkId`)) {
        stopifnot(is.character(`networkId`), length(`networkId`) == 1)
        self$`networkId` <- `networkId`
      }
    },
    toJSON = function() {
      InlineObject5Object <- list()
      if (!is.null(self$`attributes`)) {
        InlineObject5Object[['attributes']] <-
          self$`attributes`
      }
      if (!is.null(self$`enrollmentMethod`)) {
        InlineObject5Object[['enrollmentMethod']] <-
          self$`enrollmentMethod`$toJSON()
      }
      if (!is.null(self$`name`)) {
        InlineObject5Object[['name']] <-
          self$`name`
      }
      if (!is.null(self$`networkId`)) {
        InlineObject5Object[['networkId']] <-
          self$`networkId`
      }

      InlineObject5Object
    },
    fromJSON = function(InlineObject5Json) {
      InlineObject5Object <- jsonlite::fromJSON(InlineObject5Json)
      if (!is.null(InlineObject5Object$`attributes`)) {
        self$`attributes` <- ApiClient$new()$deserializeObj(InlineObject5Object$`attributes`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(InlineObject5Object$`enrollmentMethod`)) {
        enrollmentMethodObject <- CoreV2EndpointsEnrollmentMethod$new()
        enrollmentMethodObject$fromJSON(jsonlite::toJSON(InlineObject5Object$enrollmentMethod, auto_unbox = TRUE, digits = NA))
        self$`enrollmentMethod` <- enrollmentMethodObject
      }
      if (!is.null(InlineObject5Object$`name`)) {
        self$`name` <- InlineObject5Object$`name`
      }
      if (!is.null(InlineObject5Object$`networkId`)) {
        self$`networkId` <- InlineObject5Object$`networkId`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`attributes`)) {
        sprintf(
        '"attributes":
           [%s]
        ',
        paste(unlist(lapply(self$`attributes`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`enrollmentMethod`)) {
        sprintf(
        '"enrollmentMethod":
        %s
        ',
        jsonlite::toJSON(self$`enrollmentMethod`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`networkId`)) {
        sprintf(
        '"networkId":
          "%s"
                ',
        self$`networkId`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineObject5Json) {
      InlineObject5Object <- jsonlite::fromJSON(InlineObject5Json)
      self$`attributes` <- ApiClient$new()$deserializeObj(InlineObject5Object$`attributes`, "array[character]", loadNamespace("openapi"))
      self$`enrollmentMethod` <- CoreV2EndpointsEnrollmentMethod$new()$fromJSON(jsonlite::toJSON(InlineObject5Object$enrollmentMethod, auto_unbox = TRUE, digits = NA))
      self$`name` <- InlineObject5Object$`name`
      self$`networkId` <- InlineObject5Object$`networkId`
      self
    }
  )
)
