# untitled API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 5229
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse20017Embedded
#' @description InlineResponse20017Embedded Class
#' @format An \code{R6Class} generator object
#' @field organizations  list( \link{InlineResponse20017EmbeddedOrganizations} ) 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse20017Embedded <- R6::R6Class(
  'InlineResponse20017Embedded',
  public = list(
    `organizations` = NULL,
    initialize = function(`organizations`, ...){
      local.optional.var <- list(...)
      if (!missing(`organizations`)) {
        stopifnot(is.vector(`organizations`), length(`organizations`) != 0)
        sapply(`organizations`, function(x) stopifnot(R6::is.R6(x)))
        self$`organizations` <- `organizations`
      }
    },
    toJSON = function() {
      InlineResponse20017EmbeddedObject <- list()
      if (!is.null(self$`organizations`)) {
        InlineResponse20017EmbeddedObject[['organizations']] <-
          lapply(self$`organizations`, function(x) x$toJSON())
      }

      InlineResponse20017EmbeddedObject
    },
    fromJSON = function(InlineResponse20017EmbeddedJson) {
      InlineResponse20017EmbeddedObject <- jsonlite::fromJSON(InlineResponse20017EmbeddedJson)
      if (!is.null(InlineResponse20017EmbeddedObject$`organizations`)) {
        self$`organizations` <- ApiClient$new()$deserializeObj(InlineResponse20017EmbeddedObject$`organizations`, "array[InlineResponse20017EmbeddedOrganizations]", loadNamespace("openapi"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`organizations`)) {
        sprintf(
        '"organizations":
        [%s]
',
        paste(sapply(self$`organizations`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse20017EmbeddedJson) {
      InlineResponse20017EmbeddedObject <- jsonlite::fromJSON(InlineResponse20017EmbeddedJson)
      self$`organizations` <- ApiClient$new()$deserializeObj(InlineResponse20017EmbeddedObject$`organizations`, "array[InlineResponse20017EmbeddedOrganizations]", loadNamespace("openapi"))
      self
    }
  )
)
