# untitled API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 5227
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse20012
#' @description InlineResponse20012 Class
#' @format An \code{R6Class} generator object
#' @field deletedAt  \link{AnyType} 
#'
#' @field networkId  character 
#'
#' @field name  character 
#'
#' @field updatedAt  character 
#'
#' @field provider  \link{AnyType} 
#'
#' @field online  character 
#'
#' @field zitiId  character 
#'
#' @field userData  \link{AnyType} 
#'
#' @field ownerIdentityId  character 
#'
#' @field attributes  list( character ) 
#'
#' @field providerId  \link{AnyType} 
#'
#' @field jwt  \link{AnyType} 
#'
#' @field id  character 
#'
#' @field ipAddress  \link{AnyType} 
#'
#' @field status  character 
#'
#' @field hostId  \link{AnyType} 
#'
#' @field createdAt  character 
#'
#' @field createdBy  character 
#'
#' @field deletedBy  \link{AnyType} 
#'
#' @field locationMetadataId  \link{AnyType} 
#'
#' @field linkListener  character 
#'
#' @field dataCenterId  \link{AnyType} 
#'
#' @field verified  character 
#'
#' @field _links  \link{InlineResponse200Links} 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse20012 <- R6::R6Class(
  'InlineResponse20012',
  public = list(
    `deletedAt` = NULL,
    `networkId` = NULL,
    `name` = NULL,
    `updatedAt` = NULL,
    `provider` = NULL,
    `online` = NULL,
    `zitiId` = NULL,
    `userData` = NULL,
    `ownerIdentityId` = NULL,
    `attributes` = NULL,
    `providerId` = NULL,
    `jwt` = NULL,
    `id` = NULL,
    `ipAddress` = NULL,
    `status` = NULL,
    `hostId` = NULL,
    `createdAt` = NULL,
    `createdBy` = NULL,
    `deletedBy` = NULL,
    `locationMetadataId` = NULL,
    `linkListener` = NULL,
    `dataCenterId` = NULL,
    `verified` = NULL,
    `_links` = NULL,
    initialize = function(`deletedAt`, `networkId`, `name`, `updatedAt`, `provider`, `online`, `zitiId`, `userData`, `ownerIdentityId`, `attributes`, `providerId`, `jwt`, `id`, `ipAddress`, `status`, `hostId`, `createdAt`, `createdBy`, `deletedBy`, `locationMetadataId`, `linkListener`, `dataCenterId`, `verified`, `_links`, ...){
      local.optional.var <- list(...)
      if (!missing(`deletedAt`)) {
        stopifnot(R6::is.R6(`deletedAt`))
        self$`deletedAt` <- `deletedAt`
      }
      if (!missing(`networkId`)) {
        stopifnot(is.character(`networkId`), length(`networkId`) == 1)
        self$`networkId` <- `networkId`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`updatedAt`)) {
        stopifnot(is.character(`updatedAt`), length(`updatedAt`) == 1)
        self$`updatedAt` <- `updatedAt`
      }
      if (!missing(`provider`)) {
        stopifnot(R6::is.R6(`provider`))
        self$`provider` <- `provider`
      }
      if (!missing(`online`)) {
        self$`online` <- `online`
      }
      if (!missing(`zitiId`)) {
        stopifnot(is.character(`zitiId`), length(`zitiId`) == 1)
        self$`zitiId` <- `zitiId`
      }
      if (!missing(`userData`)) {
        stopifnot(R6::is.R6(`userData`))
        self$`userData` <- `userData`
      }
      if (!missing(`ownerIdentityId`)) {
        stopifnot(is.character(`ownerIdentityId`), length(`ownerIdentityId`) == 1)
        self$`ownerIdentityId` <- `ownerIdentityId`
      }
      if (!missing(`attributes`)) {
        stopifnot(is.vector(`attributes`), length(`attributes`) != 0)
        sapply(`attributes`, function(x) stopifnot(is.character(x)))
        self$`attributes` <- `attributes`
      }
      if (!missing(`providerId`)) {
        stopifnot(R6::is.R6(`providerId`))
        self$`providerId` <- `providerId`
      }
      if (!missing(`jwt`)) {
        stopifnot(R6::is.R6(`jwt`))
        self$`jwt` <- `jwt`
      }
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`ipAddress`)) {
        stopifnot(R6::is.R6(`ipAddress`))
        self$`ipAddress` <- `ipAddress`
      }
      if (!missing(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
      if (!missing(`hostId`)) {
        stopifnot(R6::is.R6(`hostId`))
        self$`hostId` <- `hostId`
      }
      if (!missing(`createdAt`)) {
        stopifnot(is.character(`createdAt`), length(`createdAt`) == 1)
        self$`createdAt` <- `createdAt`
      }
      if (!missing(`createdBy`)) {
        stopifnot(is.character(`createdBy`), length(`createdBy`) == 1)
        self$`createdBy` <- `createdBy`
      }
      if (!missing(`deletedBy`)) {
        stopifnot(R6::is.R6(`deletedBy`))
        self$`deletedBy` <- `deletedBy`
      }
      if (!missing(`locationMetadataId`)) {
        stopifnot(R6::is.R6(`locationMetadataId`))
        self$`locationMetadataId` <- `locationMetadataId`
      }
      if (!missing(`linkListener`)) {
        self$`linkListener` <- `linkListener`
      }
      if (!missing(`dataCenterId`)) {
        stopifnot(R6::is.R6(`dataCenterId`))
        self$`dataCenterId` <- `dataCenterId`
      }
      if (!missing(`verified`)) {
        self$`verified` <- `verified`
      }
      if (!missing(`_links`)) {
        stopifnot(R6::is.R6(`_links`))
        self$`_links` <- `_links`
      }
    },
    toJSON = function() {
      InlineResponse20012Object <- list()
      if (!is.null(self$`deletedAt`)) {
        InlineResponse20012Object[['deletedAt']] <-
          self$`deletedAt`$toJSON()
      }
      if (!is.null(self$`networkId`)) {
        InlineResponse20012Object[['networkId']] <-
          self$`networkId`
      }
      if (!is.null(self$`name`)) {
        InlineResponse20012Object[['name']] <-
          self$`name`
      }
      if (!is.null(self$`updatedAt`)) {
        InlineResponse20012Object[['updatedAt']] <-
          self$`updatedAt`
      }
      if (!is.null(self$`provider`)) {
        InlineResponse20012Object[['provider']] <-
          self$`provider`$toJSON()
      }
      if (!is.null(self$`online`)) {
        InlineResponse20012Object[['online']] <-
          self$`online`
      }
      if (!is.null(self$`zitiId`)) {
        InlineResponse20012Object[['zitiId']] <-
          self$`zitiId`
      }
      if (!is.null(self$`userData`)) {
        InlineResponse20012Object[['userData']] <-
          self$`userData`$toJSON()
      }
      if (!is.null(self$`ownerIdentityId`)) {
        InlineResponse20012Object[['ownerIdentityId']] <-
          self$`ownerIdentityId`
      }
      if (!is.null(self$`attributes`)) {
        InlineResponse20012Object[['attributes']] <-
          self$`attributes`
      }
      if (!is.null(self$`providerId`)) {
        InlineResponse20012Object[['providerId']] <-
          self$`providerId`$toJSON()
      }
      if (!is.null(self$`jwt`)) {
        InlineResponse20012Object[['jwt']] <-
          self$`jwt`$toJSON()
      }
      if (!is.null(self$`id`)) {
        InlineResponse20012Object[['id']] <-
          self$`id`
      }
      if (!is.null(self$`ipAddress`)) {
        InlineResponse20012Object[['ipAddress']] <-
          self$`ipAddress`$toJSON()
      }
      if (!is.null(self$`status`)) {
        InlineResponse20012Object[['status']] <-
          self$`status`
      }
      if (!is.null(self$`hostId`)) {
        InlineResponse20012Object[['hostId']] <-
          self$`hostId`$toJSON()
      }
      if (!is.null(self$`createdAt`)) {
        InlineResponse20012Object[['createdAt']] <-
          self$`createdAt`
      }
      if (!is.null(self$`createdBy`)) {
        InlineResponse20012Object[['createdBy']] <-
          self$`createdBy`
      }
      if (!is.null(self$`deletedBy`)) {
        InlineResponse20012Object[['deletedBy']] <-
          self$`deletedBy`$toJSON()
      }
      if (!is.null(self$`locationMetadataId`)) {
        InlineResponse20012Object[['locationMetadataId']] <-
          self$`locationMetadataId`$toJSON()
      }
      if (!is.null(self$`linkListener`)) {
        InlineResponse20012Object[['linkListener']] <-
          self$`linkListener`
      }
      if (!is.null(self$`dataCenterId`)) {
        InlineResponse20012Object[['dataCenterId']] <-
          self$`dataCenterId`$toJSON()
      }
      if (!is.null(self$`verified`)) {
        InlineResponse20012Object[['verified']] <-
          self$`verified`
      }
      if (!is.null(self$`_links`)) {
        InlineResponse20012Object[['_links']] <-
          self$`_links`$toJSON()
      }

      InlineResponse20012Object
    },
    fromJSON = function(InlineResponse20012Json) {
      InlineResponse20012Object <- jsonlite::fromJSON(InlineResponse20012Json)
      if (!is.null(InlineResponse20012Object$`deletedAt`)) {
        deletedAtObject <- AnyType$new()
        deletedAtObject$fromJSON(jsonlite::toJSON(InlineResponse20012Object$deletedAt, auto_unbox = TRUE, digits = NA))
        self$`deletedAt` <- deletedAtObject
      }
      if (!is.null(InlineResponse20012Object$`networkId`)) {
        self$`networkId` <- InlineResponse20012Object$`networkId`
      }
      if (!is.null(InlineResponse20012Object$`name`)) {
        self$`name` <- InlineResponse20012Object$`name`
      }
      if (!is.null(InlineResponse20012Object$`updatedAt`)) {
        self$`updatedAt` <- InlineResponse20012Object$`updatedAt`
      }
      if (!is.null(InlineResponse20012Object$`provider`)) {
        providerObject <- AnyType$new()
        providerObject$fromJSON(jsonlite::toJSON(InlineResponse20012Object$provider, auto_unbox = TRUE, digits = NA))
        self$`provider` <- providerObject
      }
      if (!is.null(InlineResponse20012Object$`online`)) {
        self$`online` <- InlineResponse20012Object$`online`
      }
      if (!is.null(InlineResponse20012Object$`zitiId`)) {
        self$`zitiId` <- InlineResponse20012Object$`zitiId`
      }
      if (!is.null(InlineResponse20012Object$`userData`)) {
        userDataObject <- AnyType$new()
        userDataObject$fromJSON(jsonlite::toJSON(InlineResponse20012Object$userData, auto_unbox = TRUE, digits = NA))
        self$`userData` <- userDataObject
      }
      if (!is.null(InlineResponse20012Object$`ownerIdentityId`)) {
        self$`ownerIdentityId` <- InlineResponse20012Object$`ownerIdentityId`
      }
      if (!is.null(InlineResponse20012Object$`attributes`)) {
        self$`attributes` <- ApiClient$new()$deserializeObj(InlineResponse20012Object$`attributes`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(InlineResponse20012Object$`providerId`)) {
        providerIdObject <- AnyType$new()
        providerIdObject$fromJSON(jsonlite::toJSON(InlineResponse20012Object$providerId, auto_unbox = TRUE, digits = NA))
        self$`providerId` <- providerIdObject
      }
      if (!is.null(InlineResponse20012Object$`jwt`)) {
        jwtObject <- AnyType$new()
        jwtObject$fromJSON(jsonlite::toJSON(InlineResponse20012Object$jwt, auto_unbox = TRUE, digits = NA))
        self$`jwt` <- jwtObject
      }
      if (!is.null(InlineResponse20012Object$`id`)) {
        self$`id` <- InlineResponse20012Object$`id`
      }
      if (!is.null(InlineResponse20012Object$`ipAddress`)) {
        ipAddressObject <- AnyType$new()
        ipAddressObject$fromJSON(jsonlite::toJSON(InlineResponse20012Object$ipAddress, auto_unbox = TRUE, digits = NA))
        self$`ipAddress` <- ipAddressObject
      }
      if (!is.null(InlineResponse20012Object$`status`)) {
        self$`status` <- InlineResponse20012Object$`status`
      }
      if (!is.null(InlineResponse20012Object$`hostId`)) {
        hostIdObject <- AnyType$new()
        hostIdObject$fromJSON(jsonlite::toJSON(InlineResponse20012Object$hostId, auto_unbox = TRUE, digits = NA))
        self$`hostId` <- hostIdObject
      }
      if (!is.null(InlineResponse20012Object$`createdAt`)) {
        self$`createdAt` <- InlineResponse20012Object$`createdAt`
      }
      if (!is.null(InlineResponse20012Object$`createdBy`)) {
        self$`createdBy` <- InlineResponse20012Object$`createdBy`
      }
      if (!is.null(InlineResponse20012Object$`deletedBy`)) {
        deletedByObject <- AnyType$new()
        deletedByObject$fromJSON(jsonlite::toJSON(InlineResponse20012Object$deletedBy, auto_unbox = TRUE, digits = NA))
        self$`deletedBy` <- deletedByObject
      }
      if (!is.null(InlineResponse20012Object$`locationMetadataId`)) {
        locationMetadataIdObject <- AnyType$new()
        locationMetadataIdObject$fromJSON(jsonlite::toJSON(InlineResponse20012Object$locationMetadataId, auto_unbox = TRUE, digits = NA))
        self$`locationMetadataId` <- locationMetadataIdObject
      }
      if (!is.null(InlineResponse20012Object$`linkListener`)) {
        self$`linkListener` <- InlineResponse20012Object$`linkListener`
      }
      if (!is.null(InlineResponse20012Object$`dataCenterId`)) {
        dataCenterIdObject <- AnyType$new()
        dataCenterIdObject$fromJSON(jsonlite::toJSON(InlineResponse20012Object$dataCenterId, auto_unbox = TRUE, digits = NA))
        self$`dataCenterId` <- dataCenterIdObject
      }
      if (!is.null(InlineResponse20012Object$`verified`)) {
        self$`verified` <- InlineResponse20012Object$`verified`
      }
      if (!is.null(InlineResponse20012Object$`_links`)) {
        _linksObject <- InlineResponse200Links$new()
        _linksObject$fromJSON(jsonlite::toJSON(InlineResponse20012Object$_links, auto_unbox = TRUE, digits = NA))
        self$`_links` <- _linksObject
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`deletedAt`)) {
        sprintf(
        '"deletedAt":
        %s
        ',
        jsonlite::toJSON(self$`deletedAt`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`networkId`)) {
        sprintf(
        '"networkId":
          "%s"
                ',
        self$`networkId`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`updatedAt`)) {
        sprintf(
        '"updatedAt":
          "%s"
                ',
        self$`updatedAt`
        )},
        if (!is.null(self$`provider`)) {
        sprintf(
        '"provider":
        %s
        ',
        jsonlite::toJSON(self$`provider`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`online`)) {
        sprintf(
        '"online":
          "%s"
                ',
        self$`online`
        )},
        if (!is.null(self$`zitiId`)) {
        sprintf(
        '"zitiId":
          "%s"
                ',
        self$`zitiId`
        )},
        if (!is.null(self$`userData`)) {
        sprintf(
        '"userData":
        %s
        ',
        jsonlite::toJSON(self$`userData`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`ownerIdentityId`)) {
        sprintf(
        '"ownerIdentityId":
          "%s"
                ',
        self$`ownerIdentityId`
        )},
        if (!is.null(self$`attributes`)) {
        sprintf(
        '"attributes":
           [%s]
        ',
        paste(unlist(lapply(self$`attributes`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`providerId`)) {
        sprintf(
        '"providerId":
        %s
        ',
        jsonlite::toJSON(self$`providerId`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`jwt`)) {
        sprintf(
        '"jwt":
        %s
        ',
        jsonlite::toJSON(self$`jwt`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`ipAddress`)) {
        sprintf(
        '"ipAddress":
        %s
        ',
        jsonlite::toJSON(self$`ipAddress`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
          "%s"
                ',
        self$`status`
        )},
        if (!is.null(self$`hostId`)) {
        sprintf(
        '"hostId":
        %s
        ',
        jsonlite::toJSON(self$`hostId`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`createdAt`)) {
        sprintf(
        '"createdAt":
          "%s"
                ',
        self$`createdAt`
        )},
        if (!is.null(self$`createdBy`)) {
        sprintf(
        '"createdBy":
          "%s"
                ',
        self$`createdBy`
        )},
        if (!is.null(self$`deletedBy`)) {
        sprintf(
        '"deletedBy":
        %s
        ',
        jsonlite::toJSON(self$`deletedBy`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`locationMetadataId`)) {
        sprintf(
        '"locationMetadataId":
        %s
        ',
        jsonlite::toJSON(self$`locationMetadataId`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`linkListener`)) {
        sprintf(
        '"linkListener":
          "%s"
                ',
        self$`linkListener`
        )},
        if (!is.null(self$`dataCenterId`)) {
        sprintf(
        '"dataCenterId":
        %s
        ',
        jsonlite::toJSON(self$`dataCenterId`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`verified`)) {
        sprintf(
        '"verified":
          "%s"
                ',
        self$`verified`
        )},
        if (!is.null(self$`_links`)) {
        sprintf(
        '"_links":
        %s
        ',
        jsonlite::toJSON(self$`_links`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse20012Json) {
      InlineResponse20012Object <- jsonlite::fromJSON(InlineResponse20012Json)
      self$`deletedAt` <- AnyType$new()$fromJSON(jsonlite::toJSON(InlineResponse20012Object$deletedAt, auto_unbox = TRUE, digits = NA))
      self$`networkId` <- InlineResponse20012Object$`networkId`
      self$`name` <- InlineResponse20012Object$`name`
      self$`updatedAt` <- InlineResponse20012Object$`updatedAt`
      self$`provider` <- AnyType$new()$fromJSON(jsonlite::toJSON(InlineResponse20012Object$provider, auto_unbox = TRUE, digits = NA))
      self$`online` <- InlineResponse20012Object$`online`
      self$`zitiId` <- InlineResponse20012Object$`zitiId`
      self$`userData` <- AnyType$new()$fromJSON(jsonlite::toJSON(InlineResponse20012Object$userData, auto_unbox = TRUE, digits = NA))
      self$`ownerIdentityId` <- InlineResponse20012Object$`ownerIdentityId`
      self$`attributes` <- ApiClient$new()$deserializeObj(InlineResponse20012Object$`attributes`, "array[character]", loadNamespace("openapi"))
      self$`providerId` <- AnyType$new()$fromJSON(jsonlite::toJSON(InlineResponse20012Object$providerId, auto_unbox = TRUE, digits = NA))
      self$`jwt` <- AnyType$new()$fromJSON(jsonlite::toJSON(InlineResponse20012Object$jwt, auto_unbox = TRUE, digits = NA))
      self$`id` <- InlineResponse20012Object$`id`
      self$`ipAddress` <- AnyType$new()$fromJSON(jsonlite::toJSON(InlineResponse20012Object$ipAddress, auto_unbox = TRUE, digits = NA))
      self$`status` <- InlineResponse20012Object$`status`
      self$`hostId` <- AnyType$new()$fromJSON(jsonlite::toJSON(InlineResponse20012Object$hostId, auto_unbox = TRUE, digits = NA))
      self$`createdAt` <- InlineResponse20012Object$`createdAt`
      self$`createdBy` <- InlineResponse20012Object$`createdBy`
      self$`deletedBy` <- AnyType$new()$fromJSON(jsonlite::toJSON(InlineResponse20012Object$deletedBy, auto_unbox = TRUE, digits = NA))
      self$`locationMetadataId` <- AnyType$new()$fromJSON(jsonlite::toJSON(InlineResponse20012Object$locationMetadataId, auto_unbox = TRUE, digits = NA))
      self$`linkListener` <- InlineResponse20012Object$`linkListener`
      self$`dataCenterId` <- AnyType$new()$fromJSON(jsonlite::toJSON(InlineResponse20012Object$dataCenterId, auto_unbox = TRUE, digits = NA))
      self$`verified` <- InlineResponse20012Object$`verified`
      self$`_links` <- InlineResponse200Links$new()$fromJSON(jsonlite::toJSON(InlineResponse20012Object$_links, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
