# untitled API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 5227
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse20016
#' @description InlineResponse20016 Class
#' @format An \code{R6Class} generator object
#' @field deletedAt  \link{AnyType} 
#'
#' @field name  character 
#'
#' @field updatedAt  \link{AnyType} 
#'
#' @field email  character 
#'
#' @field description  character 
#'
#' @field awsCognitoClientId  character 
#'
#' @field auth0ClientId  \link{AnyType} 
#'
#' @field id  character 
#'
#' @field contactEmail  character 
#'
#' @field createdAt  \link{InlineResponse20014UpdatedAt} 
#'
#' @field organizationId  character 
#'
#' @field tenantId  character 
#'
#' @field type  character 
#'
#' @field authenticationUrl  character 
#'
#' @field active  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse20016 <- R6::R6Class(
  'InlineResponse20016',
  public = list(
    `deletedAt` = NULL,
    `name` = NULL,
    `updatedAt` = NULL,
    `email` = NULL,
    `description` = NULL,
    `awsCognitoClientId` = NULL,
    `auth0ClientId` = NULL,
    `id` = NULL,
    `contactEmail` = NULL,
    `createdAt` = NULL,
    `organizationId` = NULL,
    `tenantId` = NULL,
    `type` = NULL,
    `authenticationUrl` = NULL,
    `active` = NULL,
    initialize = function(`deletedAt`, `name`, `updatedAt`, `email`, `description`, `awsCognitoClientId`, `auth0ClientId`, `id`, `contactEmail`, `createdAt`, `organizationId`, `tenantId`, `type`, `authenticationUrl`, `active`, ...){
      local.optional.var <- list(...)
      if (!missing(`deletedAt`)) {
        stopifnot(R6::is.R6(`deletedAt`))
        self$`deletedAt` <- `deletedAt`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`updatedAt`)) {
        stopifnot(R6::is.R6(`updatedAt`))
        self$`updatedAt` <- `updatedAt`
      }
      if (!missing(`email`)) {
        stopifnot(is.character(`email`), length(`email`) == 1)
        self$`email` <- `email`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`awsCognitoClientId`)) {
        stopifnot(is.character(`awsCognitoClientId`), length(`awsCognitoClientId`) == 1)
        self$`awsCognitoClientId` <- `awsCognitoClientId`
      }
      if (!missing(`auth0ClientId`)) {
        stopifnot(R6::is.R6(`auth0ClientId`))
        self$`auth0ClientId` <- `auth0ClientId`
      }
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`contactEmail`)) {
        stopifnot(is.character(`contactEmail`), length(`contactEmail`) == 1)
        self$`contactEmail` <- `contactEmail`
      }
      if (!missing(`createdAt`)) {
        stopifnot(R6::is.R6(`createdAt`))
        self$`createdAt` <- `createdAt`
      }
      if (!missing(`organizationId`)) {
        stopifnot(is.character(`organizationId`), length(`organizationId`) == 1)
        self$`organizationId` <- `organizationId`
      }
      if (!missing(`tenantId`)) {
        stopifnot(is.character(`tenantId`), length(`tenantId`) == 1)
        self$`tenantId` <- `tenantId`
      }
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`authenticationUrl`)) {
        stopifnot(is.character(`authenticationUrl`), length(`authenticationUrl`) == 1)
        self$`authenticationUrl` <- `authenticationUrl`
      }
      if (!missing(`active`)) {
        self$`active` <- `active`
      }
    },
    toJSON = function() {
      InlineResponse20016Object <- list()
      if (!is.null(self$`deletedAt`)) {
        InlineResponse20016Object[['deletedAt']] <-
          self$`deletedAt`$toJSON()
      }
      if (!is.null(self$`name`)) {
        InlineResponse20016Object[['name']] <-
          self$`name`
      }
      if (!is.null(self$`updatedAt`)) {
        InlineResponse20016Object[['updatedAt']] <-
          self$`updatedAt`$toJSON()
      }
      if (!is.null(self$`email`)) {
        InlineResponse20016Object[['email']] <-
          self$`email`
      }
      if (!is.null(self$`description`)) {
        InlineResponse20016Object[['description']] <-
          self$`description`
      }
      if (!is.null(self$`awsCognitoClientId`)) {
        InlineResponse20016Object[['awsCognitoClientId']] <-
          self$`awsCognitoClientId`
      }
      if (!is.null(self$`auth0ClientId`)) {
        InlineResponse20016Object[['auth0ClientId']] <-
          self$`auth0ClientId`$toJSON()
      }
      if (!is.null(self$`id`)) {
        InlineResponse20016Object[['id']] <-
          self$`id`
      }
      if (!is.null(self$`contactEmail`)) {
        InlineResponse20016Object[['contactEmail']] <-
          self$`contactEmail`
      }
      if (!is.null(self$`createdAt`)) {
        InlineResponse20016Object[['createdAt']] <-
          self$`createdAt`$toJSON()
      }
      if (!is.null(self$`organizationId`)) {
        InlineResponse20016Object[['organizationId']] <-
          self$`organizationId`
      }
      if (!is.null(self$`tenantId`)) {
        InlineResponse20016Object[['tenantId']] <-
          self$`tenantId`
      }
      if (!is.null(self$`type`)) {
        InlineResponse20016Object[['type']] <-
          self$`type`
      }
      if (!is.null(self$`authenticationUrl`)) {
        InlineResponse20016Object[['authenticationUrl']] <-
          self$`authenticationUrl`
      }
      if (!is.null(self$`active`)) {
        InlineResponse20016Object[['active']] <-
          self$`active`
      }

      InlineResponse20016Object
    },
    fromJSON = function(InlineResponse20016Json) {
      InlineResponse20016Object <- jsonlite::fromJSON(InlineResponse20016Json)
      if (!is.null(InlineResponse20016Object$`deletedAt`)) {
        deletedAtObject <- AnyType$new()
        deletedAtObject$fromJSON(jsonlite::toJSON(InlineResponse20016Object$deletedAt, auto_unbox = TRUE, digits = NA))
        self$`deletedAt` <- deletedAtObject
      }
      if (!is.null(InlineResponse20016Object$`name`)) {
        self$`name` <- InlineResponse20016Object$`name`
      }
      if (!is.null(InlineResponse20016Object$`updatedAt`)) {
        updatedAtObject <- AnyType$new()
        updatedAtObject$fromJSON(jsonlite::toJSON(InlineResponse20016Object$updatedAt, auto_unbox = TRUE, digits = NA))
        self$`updatedAt` <- updatedAtObject
      }
      if (!is.null(InlineResponse20016Object$`email`)) {
        self$`email` <- InlineResponse20016Object$`email`
      }
      if (!is.null(InlineResponse20016Object$`description`)) {
        self$`description` <- InlineResponse20016Object$`description`
      }
      if (!is.null(InlineResponse20016Object$`awsCognitoClientId`)) {
        self$`awsCognitoClientId` <- InlineResponse20016Object$`awsCognitoClientId`
      }
      if (!is.null(InlineResponse20016Object$`auth0ClientId`)) {
        auth0ClientIdObject <- AnyType$new()
        auth0ClientIdObject$fromJSON(jsonlite::toJSON(InlineResponse20016Object$auth0ClientId, auto_unbox = TRUE, digits = NA))
        self$`auth0ClientId` <- auth0ClientIdObject
      }
      if (!is.null(InlineResponse20016Object$`id`)) {
        self$`id` <- InlineResponse20016Object$`id`
      }
      if (!is.null(InlineResponse20016Object$`contactEmail`)) {
        self$`contactEmail` <- InlineResponse20016Object$`contactEmail`
      }
      if (!is.null(InlineResponse20016Object$`createdAt`)) {
        createdAtObject <- InlineResponse20014UpdatedAt$new()
        createdAtObject$fromJSON(jsonlite::toJSON(InlineResponse20016Object$createdAt, auto_unbox = TRUE, digits = NA))
        self$`createdAt` <- createdAtObject
      }
      if (!is.null(InlineResponse20016Object$`organizationId`)) {
        self$`organizationId` <- InlineResponse20016Object$`organizationId`
      }
      if (!is.null(InlineResponse20016Object$`tenantId`)) {
        self$`tenantId` <- InlineResponse20016Object$`tenantId`
      }
      if (!is.null(InlineResponse20016Object$`type`)) {
        self$`type` <- InlineResponse20016Object$`type`
      }
      if (!is.null(InlineResponse20016Object$`authenticationUrl`)) {
        self$`authenticationUrl` <- InlineResponse20016Object$`authenticationUrl`
      }
      if (!is.null(InlineResponse20016Object$`active`)) {
        self$`active` <- InlineResponse20016Object$`active`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`deletedAt`)) {
        sprintf(
        '"deletedAt":
        %s
        ',
        jsonlite::toJSON(self$`deletedAt`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`updatedAt`)) {
        sprintf(
        '"updatedAt":
        %s
        ',
        jsonlite::toJSON(self$`updatedAt`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`email`)) {
        sprintf(
        '"email":
          "%s"
                ',
        self$`email`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`awsCognitoClientId`)) {
        sprintf(
        '"awsCognitoClientId":
          "%s"
                ',
        self$`awsCognitoClientId`
        )},
        if (!is.null(self$`auth0ClientId`)) {
        sprintf(
        '"auth0ClientId":
        %s
        ',
        jsonlite::toJSON(self$`auth0ClientId`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`contactEmail`)) {
        sprintf(
        '"contactEmail":
          "%s"
                ',
        self$`contactEmail`
        )},
        if (!is.null(self$`createdAt`)) {
        sprintf(
        '"createdAt":
        %s
        ',
        jsonlite::toJSON(self$`createdAt`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`organizationId`)) {
        sprintf(
        '"organizationId":
          "%s"
                ',
        self$`organizationId`
        )},
        if (!is.null(self$`tenantId`)) {
        sprintf(
        '"tenantId":
          "%s"
                ',
        self$`tenantId`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          "%s"
                ',
        self$`type`
        )},
        if (!is.null(self$`authenticationUrl`)) {
        sprintf(
        '"authenticationUrl":
          "%s"
                ',
        self$`authenticationUrl`
        )},
        if (!is.null(self$`active`)) {
        sprintf(
        '"active":
          "%s"
                ',
        self$`active`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse20016Json) {
      InlineResponse20016Object <- jsonlite::fromJSON(InlineResponse20016Json)
      self$`deletedAt` <- AnyType$new()$fromJSON(jsonlite::toJSON(InlineResponse20016Object$deletedAt, auto_unbox = TRUE, digits = NA))
      self$`name` <- InlineResponse20016Object$`name`
      self$`updatedAt` <- AnyType$new()$fromJSON(jsonlite::toJSON(InlineResponse20016Object$updatedAt, auto_unbox = TRUE, digits = NA))
      self$`email` <- InlineResponse20016Object$`email`
      self$`description` <- InlineResponse20016Object$`description`
      self$`awsCognitoClientId` <- InlineResponse20016Object$`awsCognitoClientId`
      self$`auth0ClientId` <- AnyType$new()$fromJSON(jsonlite::toJSON(InlineResponse20016Object$auth0ClientId, auto_unbox = TRUE, digits = NA))
      self$`id` <- InlineResponse20016Object$`id`
      self$`contactEmail` <- InlineResponse20016Object$`contactEmail`
      self$`createdAt` <- InlineResponse20014UpdatedAt$new()$fromJSON(jsonlite::toJSON(InlineResponse20016Object$createdAt, auto_unbox = TRUE, digits = NA))
      self$`organizationId` <- InlineResponse20016Object$`organizationId`
      self$`tenantId` <- InlineResponse20016Object$`tenantId`
      self$`type` <- InlineResponse20016Object$`type`
      self$`authenticationUrl` <- InlineResponse20016Object$`authenticationUrl`
      self$`active` <- InlineResponse20016Object$`active`
      self
    }
  )
)
