# untitled API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 5170
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineObject3
#' @description InlineObject3 Class
#' @format An \code{R6Class} generator object
#' @field model  \link{CoreV2ServicesServiceIdModel} 
#'
#' @field modelType  character 
#'
#' @field name  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineObject3 <- R6::R6Class(
  'InlineObject3',
  public = list(
    `model` = NULL,
    `modelType` = NULL,
    `name` = NULL,
    initialize = function(`model`, `modelType`, `name`, ...){
      local.optional.var <- list(...)
      if (!missing(`model`)) {
        stopifnot(R6::is.R6(`model`))
        self$`model` <- `model`
      }
      if (!missing(`modelType`)) {
        stopifnot(is.character(`modelType`), length(`modelType`) == 1)
        self$`modelType` <- `modelType`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      InlineObject3Object <- list()
      if (!is.null(self$`model`)) {
        InlineObject3Object[['model']] <-
          self$`model`$toJSON()
      }
      if (!is.null(self$`modelType`)) {
        InlineObject3Object[['modelType']] <-
          self$`modelType`
      }
      if (!is.null(self$`name`)) {
        InlineObject3Object[['name']] <-
          self$`name`
      }

      InlineObject3Object
    },
    fromJSON = function(InlineObject3Json) {
      InlineObject3Object <- jsonlite::fromJSON(InlineObject3Json)
      if (!is.null(InlineObject3Object$`model`)) {
        modelObject <- CoreV2ServicesServiceIdModel$new()
        modelObject$fromJSON(jsonlite::toJSON(InlineObject3Object$model, auto_unbox = TRUE, digits = NA))
        self$`model` <- modelObject
      }
      if (!is.null(InlineObject3Object$`modelType`)) {
        self$`modelType` <- InlineObject3Object$`modelType`
      }
      if (!is.null(InlineObject3Object$`name`)) {
        self$`name` <- InlineObject3Object$`name`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`model`)) {
        sprintf(
        '"model":
        %s
        ',
        jsonlite::toJSON(self$`model`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`modelType`)) {
        sprintf(
        '"modelType":
          "%s"
                ',
        self$`modelType`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineObject3Json) {
      InlineObject3Object <- jsonlite::fromJSON(InlineObject3Json)
      self$`model` <- CoreV2ServicesServiceIdModel$new()$fromJSON(jsonlite::toJSON(InlineObject3Object$model, auto_unbox = TRUE, digits = NA))
      self$`modelType` <- InlineObject3Object$`modelType`
      self$`name` <- InlineObject3Object$`name`
      self
    }
  )
)
