# untitled API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 5229
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse2005ConfigIdByConfigTypeId
#' @description InlineResponse2005ConfigIdByConfigTypeId Class
#' @format An \code{R6Class} generator object
#' @field d75e27f0-ebab-4567-8440-c24f02f2eca5  character [optional]
#'
#' @field cf3962b1-a98e-4ade-ae25-cdc388e7feb3  character [optional]
#'
#' @field 2c1998a1-32e2-4084-b20a-b580570f4fbf  character [optional]
#'
#' @field 4c42c4db-f039-4a57-8264-5f57af512614  character [optional]
#'
#' @field 7cafedc5-17b8-4c1e-8b6f-0d9bc1b4b7bc  character [optional]
#'
#' @field 714a918a-7935-4b4f-82c3-afbadcd9e59b  character [optional]
#'
#' @field b1582680-ab7b-45d0-ac36-b00f82df8e79  character [optional]
#'
#' @field e7f6ef8d-da57-444c-b677-f03974f5d8be  character [optional]
#'
#' @field 6fa5c2bc-b7f7-47f8-9229-e927722adb27  character [optional]
#'
#' @field 64a39300-b672-413b-9d8c-42175f7e84dd  character [optional]
#'
#' @field ea6e632b-d8e1-420f-bd8f-ad50b067bad6  character [optional]
#'
#' @field 7491e52d-97e8-4759-8a63-c8ea8a75f822  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse2005ConfigIdByConfigTypeId <- R6::R6Class(
  'InlineResponse2005ConfigIdByConfigTypeId',
  public = list(
    `d75e27f0-ebab-4567-8440-c24f02f2eca5` = NULL,
    `cf3962b1-a98e-4ade-ae25-cdc388e7feb3` = NULL,
    `2c1998a1-32e2-4084-b20a-b580570f4fbf` = NULL,
    `4c42c4db-f039-4a57-8264-5f57af512614` = NULL,
    `7cafedc5-17b8-4c1e-8b6f-0d9bc1b4b7bc` = NULL,
    `714a918a-7935-4b4f-82c3-afbadcd9e59b` = NULL,
    `b1582680-ab7b-45d0-ac36-b00f82df8e79` = NULL,
    `e7f6ef8d-da57-444c-b677-f03974f5d8be` = NULL,
    `6fa5c2bc-b7f7-47f8-9229-e927722adb27` = NULL,
    `64a39300-b672-413b-9d8c-42175f7e84dd` = NULL,
    `ea6e632b-d8e1-420f-bd8f-ad50b067bad6` = NULL,
    `7491e52d-97e8-4759-8a63-c8ea8a75f822` = NULL,
    initialize = function(`d75e27f0-ebab-4567-8440-c24f02f2eca5`=NULL, `cf3962b1-a98e-4ade-ae25-cdc388e7feb3`=NULL, `2c1998a1-32e2-4084-b20a-b580570f4fbf`=NULL, `4c42c4db-f039-4a57-8264-5f57af512614`=NULL, `7cafedc5-17b8-4c1e-8b6f-0d9bc1b4b7bc`=NULL, `714a918a-7935-4b4f-82c3-afbadcd9e59b`=NULL, `b1582680-ab7b-45d0-ac36-b00f82df8e79`=NULL, `e7f6ef8d-da57-444c-b677-f03974f5d8be`=NULL, `6fa5c2bc-b7f7-47f8-9229-e927722adb27`=NULL, `64a39300-b672-413b-9d8c-42175f7e84dd`=NULL, `ea6e632b-d8e1-420f-bd8f-ad50b067bad6`=NULL, `7491e52d-97e8-4759-8a63-c8ea8a75f822`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`d75e27f0-ebab-4567-8440-c24f02f2eca5`)) {
        stopifnot(is.character(`d75e27f0-ebab-4567-8440-c24f02f2eca5`), length(`d75e27f0-ebab-4567-8440-c24f02f2eca5`) == 1)
        self$`d75e27f0-ebab-4567-8440-c24f02f2eca5` <- `d75e27f0-ebab-4567-8440-c24f02f2eca5`
      }
      if (!is.null(`cf3962b1-a98e-4ade-ae25-cdc388e7feb3`)) {
        stopifnot(is.character(`cf3962b1-a98e-4ade-ae25-cdc388e7feb3`), length(`cf3962b1-a98e-4ade-ae25-cdc388e7feb3`) == 1)
        self$`cf3962b1-a98e-4ade-ae25-cdc388e7feb3` <- `cf3962b1-a98e-4ade-ae25-cdc388e7feb3`
      }
      if (!is.null(`2c1998a1-32e2-4084-b20a-b580570f4fbf`)) {
        stopifnot(is.character(`2c1998a1-32e2-4084-b20a-b580570f4fbf`), length(`2c1998a1-32e2-4084-b20a-b580570f4fbf`) == 1)
        self$`2c1998a1-32e2-4084-b20a-b580570f4fbf` <- `2c1998a1-32e2-4084-b20a-b580570f4fbf`
      }
      if (!is.null(`4c42c4db-f039-4a57-8264-5f57af512614`)) {
        stopifnot(is.character(`4c42c4db-f039-4a57-8264-5f57af512614`), length(`4c42c4db-f039-4a57-8264-5f57af512614`) == 1)
        self$`4c42c4db-f039-4a57-8264-5f57af512614` <- `4c42c4db-f039-4a57-8264-5f57af512614`
      }
      if (!is.null(`7cafedc5-17b8-4c1e-8b6f-0d9bc1b4b7bc`)) {
        stopifnot(is.character(`7cafedc5-17b8-4c1e-8b6f-0d9bc1b4b7bc`), length(`7cafedc5-17b8-4c1e-8b6f-0d9bc1b4b7bc`) == 1)
        self$`7cafedc5-17b8-4c1e-8b6f-0d9bc1b4b7bc` <- `7cafedc5-17b8-4c1e-8b6f-0d9bc1b4b7bc`
      }
      if (!is.null(`714a918a-7935-4b4f-82c3-afbadcd9e59b`)) {
        stopifnot(is.character(`714a918a-7935-4b4f-82c3-afbadcd9e59b`), length(`714a918a-7935-4b4f-82c3-afbadcd9e59b`) == 1)
        self$`714a918a-7935-4b4f-82c3-afbadcd9e59b` <- `714a918a-7935-4b4f-82c3-afbadcd9e59b`
      }
      if (!is.null(`b1582680-ab7b-45d0-ac36-b00f82df8e79`)) {
        stopifnot(is.character(`b1582680-ab7b-45d0-ac36-b00f82df8e79`), length(`b1582680-ab7b-45d0-ac36-b00f82df8e79`) == 1)
        self$`b1582680-ab7b-45d0-ac36-b00f82df8e79` <- `b1582680-ab7b-45d0-ac36-b00f82df8e79`
      }
      if (!is.null(`e7f6ef8d-da57-444c-b677-f03974f5d8be`)) {
        stopifnot(is.character(`e7f6ef8d-da57-444c-b677-f03974f5d8be`), length(`e7f6ef8d-da57-444c-b677-f03974f5d8be`) == 1)
        self$`e7f6ef8d-da57-444c-b677-f03974f5d8be` <- `e7f6ef8d-da57-444c-b677-f03974f5d8be`
      }
      if (!is.null(`6fa5c2bc-b7f7-47f8-9229-e927722adb27`)) {
        stopifnot(is.character(`6fa5c2bc-b7f7-47f8-9229-e927722adb27`), length(`6fa5c2bc-b7f7-47f8-9229-e927722adb27`) == 1)
        self$`6fa5c2bc-b7f7-47f8-9229-e927722adb27` <- `6fa5c2bc-b7f7-47f8-9229-e927722adb27`
      }
      if (!is.null(`64a39300-b672-413b-9d8c-42175f7e84dd`)) {
        stopifnot(is.character(`64a39300-b672-413b-9d8c-42175f7e84dd`), length(`64a39300-b672-413b-9d8c-42175f7e84dd`) == 1)
        self$`64a39300-b672-413b-9d8c-42175f7e84dd` <- `64a39300-b672-413b-9d8c-42175f7e84dd`
      }
      if (!is.null(`ea6e632b-d8e1-420f-bd8f-ad50b067bad6`)) {
        stopifnot(is.character(`ea6e632b-d8e1-420f-bd8f-ad50b067bad6`), length(`ea6e632b-d8e1-420f-bd8f-ad50b067bad6`) == 1)
        self$`ea6e632b-d8e1-420f-bd8f-ad50b067bad6` <- `ea6e632b-d8e1-420f-bd8f-ad50b067bad6`
      }
      if (!is.null(`7491e52d-97e8-4759-8a63-c8ea8a75f822`)) {
        stopifnot(is.character(`7491e52d-97e8-4759-8a63-c8ea8a75f822`), length(`7491e52d-97e8-4759-8a63-c8ea8a75f822`) == 1)
        self$`7491e52d-97e8-4759-8a63-c8ea8a75f822` <- `7491e52d-97e8-4759-8a63-c8ea8a75f822`
      }
    },
    toJSON = function() {
      InlineResponse2005ConfigIdByConfigTypeIdObject <- list()
      if (!is.null(self$`d75e27f0-ebab-4567-8440-c24f02f2eca5`)) {
        InlineResponse2005ConfigIdByConfigTypeIdObject[['d75e27f0-ebab-4567-8440-c24f02f2eca5']] <-
          self$`d75e27f0-ebab-4567-8440-c24f02f2eca5`
      }
      if (!is.null(self$`cf3962b1-a98e-4ade-ae25-cdc388e7feb3`)) {
        InlineResponse2005ConfigIdByConfigTypeIdObject[['cf3962b1-a98e-4ade-ae25-cdc388e7feb3']] <-
          self$`cf3962b1-a98e-4ade-ae25-cdc388e7feb3`
      }
      if (!is.null(self$`2c1998a1-32e2-4084-b20a-b580570f4fbf`)) {
        InlineResponse2005ConfigIdByConfigTypeIdObject[['2c1998a1-32e2-4084-b20a-b580570f4fbf']] <-
          self$`2c1998a1-32e2-4084-b20a-b580570f4fbf`
      }
      if (!is.null(self$`4c42c4db-f039-4a57-8264-5f57af512614`)) {
        InlineResponse2005ConfigIdByConfigTypeIdObject[['4c42c4db-f039-4a57-8264-5f57af512614']] <-
          self$`4c42c4db-f039-4a57-8264-5f57af512614`
      }
      if (!is.null(self$`7cafedc5-17b8-4c1e-8b6f-0d9bc1b4b7bc`)) {
        InlineResponse2005ConfigIdByConfigTypeIdObject[['7cafedc5-17b8-4c1e-8b6f-0d9bc1b4b7bc']] <-
          self$`7cafedc5-17b8-4c1e-8b6f-0d9bc1b4b7bc`
      }
      if (!is.null(self$`714a918a-7935-4b4f-82c3-afbadcd9e59b`)) {
        InlineResponse2005ConfigIdByConfigTypeIdObject[['714a918a-7935-4b4f-82c3-afbadcd9e59b']] <-
          self$`714a918a-7935-4b4f-82c3-afbadcd9e59b`
      }
      if (!is.null(self$`b1582680-ab7b-45d0-ac36-b00f82df8e79`)) {
        InlineResponse2005ConfigIdByConfigTypeIdObject[['b1582680-ab7b-45d0-ac36-b00f82df8e79']] <-
          self$`b1582680-ab7b-45d0-ac36-b00f82df8e79`
      }
      if (!is.null(self$`e7f6ef8d-da57-444c-b677-f03974f5d8be`)) {
        InlineResponse2005ConfigIdByConfigTypeIdObject[['e7f6ef8d-da57-444c-b677-f03974f5d8be']] <-
          self$`e7f6ef8d-da57-444c-b677-f03974f5d8be`
      }
      if (!is.null(self$`6fa5c2bc-b7f7-47f8-9229-e927722adb27`)) {
        InlineResponse2005ConfigIdByConfigTypeIdObject[['6fa5c2bc-b7f7-47f8-9229-e927722adb27']] <-
          self$`6fa5c2bc-b7f7-47f8-9229-e927722adb27`
      }
      if (!is.null(self$`64a39300-b672-413b-9d8c-42175f7e84dd`)) {
        InlineResponse2005ConfigIdByConfigTypeIdObject[['64a39300-b672-413b-9d8c-42175f7e84dd']] <-
          self$`64a39300-b672-413b-9d8c-42175f7e84dd`
      }
      if (!is.null(self$`ea6e632b-d8e1-420f-bd8f-ad50b067bad6`)) {
        InlineResponse2005ConfigIdByConfigTypeIdObject[['ea6e632b-d8e1-420f-bd8f-ad50b067bad6']] <-
          self$`ea6e632b-d8e1-420f-bd8f-ad50b067bad6`
      }
      if (!is.null(self$`7491e52d-97e8-4759-8a63-c8ea8a75f822`)) {
        InlineResponse2005ConfigIdByConfigTypeIdObject[['7491e52d-97e8-4759-8a63-c8ea8a75f822']] <-
          self$`7491e52d-97e8-4759-8a63-c8ea8a75f822`
      }

      InlineResponse2005ConfigIdByConfigTypeIdObject
    },
    fromJSON = function(InlineResponse2005ConfigIdByConfigTypeIdJson) {
      InlineResponse2005ConfigIdByConfigTypeIdObject <- jsonlite::fromJSON(InlineResponse2005ConfigIdByConfigTypeIdJson)
      if (!is.null(InlineResponse2005ConfigIdByConfigTypeIdObject$`d75e27f0-ebab-4567-8440-c24f02f2eca5`)) {
        self$`d75e27f0-ebab-4567-8440-c24f02f2eca5` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`d75e27f0-ebab-4567-8440-c24f02f2eca5`
      }
      if (!is.null(InlineResponse2005ConfigIdByConfigTypeIdObject$`cf3962b1-a98e-4ade-ae25-cdc388e7feb3`)) {
        self$`cf3962b1-a98e-4ade-ae25-cdc388e7feb3` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`cf3962b1-a98e-4ade-ae25-cdc388e7feb3`
      }
      if (!is.null(InlineResponse2005ConfigIdByConfigTypeIdObject$`2c1998a1-32e2-4084-b20a-b580570f4fbf`)) {
        self$`2c1998a1-32e2-4084-b20a-b580570f4fbf` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`2c1998a1-32e2-4084-b20a-b580570f4fbf`
      }
      if (!is.null(InlineResponse2005ConfigIdByConfigTypeIdObject$`4c42c4db-f039-4a57-8264-5f57af512614`)) {
        self$`4c42c4db-f039-4a57-8264-5f57af512614` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`4c42c4db-f039-4a57-8264-5f57af512614`
      }
      if (!is.null(InlineResponse2005ConfigIdByConfigTypeIdObject$`7cafedc5-17b8-4c1e-8b6f-0d9bc1b4b7bc`)) {
        self$`7cafedc5-17b8-4c1e-8b6f-0d9bc1b4b7bc` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`7cafedc5-17b8-4c1e-8b6f-0d9bc1b4b7bc`
      }
      if (!is.null(InlineResponse2005ConfigIdByConfigTypeIdObject$`714a918a-7935-4b4f-82c3-afbadcd9e59b`)) {
        self$`714a918a-7935-4b4f-82c3-afbadcd9e59b` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`714a918a-7935-4b4f-82c3-afbadcd9e59b`
      }
      if (!is.null(InlineResponse2005ConfigIdByConfigTypeIdObject$`b1582680-ab7b-45d0-ac36-b00f82df8e79`)) {
        self$`b1582680-ab7b-45d0-ac36-b00f82df8e79` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`b1582680-ab7b-45d0-ac36-b00f82df8e79`
      }
      if (!is.null(InlineResponse2005ConfigIdByConfigTypeIdObject$`e7f6ef8d-da57-444c-b677-f03974f5d8be`)) {
        self$`e7f6ef8d-da57-444c-b677-f03974f5d8be` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`e7f6ef8d-da57-444c-b677-f03974f5d8be`
      }
      if (!is.null(InlineResponse2005ConfigIdByConfigTypeIdObject$`6fa5c2bc-b7f7-47f8-9229-e927722adb27`)) {
        self$`6fa5c2bc-b7f7-47f8-9229-e927722adb27` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`6fa5c2bc-b7f7-47f8-9229-e927722adb27`
      }
      if (!is.null(InlineResponse2005ConfigIdByConfigTypeIdObject$`64a39300-b672-413b-9d8c-42175f7e84dd`)) {
        self$`64a39300-b672-413b-9d8c-42175f7e84dd` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`64a39300-b672-413b-9d8c-42175f7e84dd`
      }
      if (!is.null(InlineResponse2005ConfigIdByConfigTypeIdObject$`ea6e632b-d8e1-420f-bd8f-ad50b067bad6`)) {
        self$`ea6e632b-d8e1-420f-bd8f-ad50b067bad6` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`ea6e632b-d8e1-420f-bd8f-ad50b067bad6`
      }
      if (!is.null(InlineResponse2005ConfigIdByConfigTypeIdObject$`7491e52d-97e8-4759-8a63-c8ea8a75f822`)) {
        self$`7491e52d-97e8-4759-8a63-c8ea8a75f822` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`7491e52d-97e8-4759-8a63-c8ea8a75f822`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`d75e27f0-ebab-4567-8440-c24f02f2eca5`)) {
        sprintf(
        '"d75e27f0-ebab-4567-8440-c24f02f2eca5":
          "%s"
                ',
        self$`d75e27f0-ebab-4567-8440-c24f02f2eca5`
        )},
        if (!is.null(self$`cf3962b1-a98e-4ade-ae25-cdc388e7feb3`)) {
        sprintf(
        '"cf3962b1-a98e-4ade-ae25-cdc388e7feb3":
          "%s"
                ',
        self$`cf3962b1-a98e-4ade-ae25-cdc388e7feb3`
        )},
        if (!is.null(self$`2c1998a1-32e2-4084-b20a-b580570f4fbf`)) {
        sprintf(
        '"2c1998a1-32e2-4084-b20a-b580570f4fbf":
          "%s"
                ',
        self$`2c1998a1-32e2-4084-b20a-b580570f4fbf`
        )},
        if (!is.null(self$`4c42c4db-f039-4a57-8264-5f57af512614`)) {
        sprintf(
        '"4c42c4db-f039-4a57-8264-5f57af512614":
          "%s"
                ',
        self$`4c42c4db-f039-4a57-8264-5f57af512614`
        )},
        if (!is.null(self$`7cafedc5-17b8-4c1e-8b6f-0d9bc1b4b7bc`)) {
        sprintf(
        '"7cafedc5-17b8-4c1e-8b6f-0d9bc1b4b7bc":
          "%s"
                ',
        self$`7cafedc5-17b8-4c1e-8b6f-0d9bc1b4b7bc`
        )},
        if (!is.null(self$`714a918a-7935-4b4f-82c3-afbadcd9e59b`)) {
        sprintf(
        '"714a918a-7935-4b4f-82c3-afbadcd9e59b":
          "%s"
                ',
        self$`714a918a-7935-4b4f-82c3-afbadcd9e59b`
        )},
        if (!is.null(self$`b1582680-ab7b-45d0-ac36-b00f82df8e79`)) {
        sprintf(
        '"b1582680-ab7b-45d0-ac36-b00f82df8e79":
          "%s"
                ',
        self$`b1582680-ab7b-45d0-ac36-b00f82df8e79`
        )},
        if (!is.null(self$`e7f6ef8d-da57-444c-b677-f03974f5d8be`)) {
        sprintf(
        '"e7f6ef8d-da57-444c-b677-f03974f5d8be":
          "%s"
                ',
        self$`e7f6ef8d-da57-444c-b677-f03974f5d8be`
        )},
        if (!is.null(self$`6fa5c2bc-b7f7-47f8-9229-e927722adb27`)) {
        sprintf(
        '"6fa5c2bc-b7f7-47f8-9229-e927722adb27":
          "%s"
                ',
        self$`6fa5c2bc-b7f7-47f8-9229-e927722adb27`
        )},
        if (!is.null(self$`64a39300-b672-413b-9d8c-42175f7e84dd`)) {
        sprintf(
        '"64a39300-b672-413b-9d8c-42175f7e84dd":
          "%s"
                ',
        self$`64a39300-b672-413b-9d8c-42175f7e84dd`
        )},
        if (!is.null(self$`ea6e632b-d8e1-420f-bd8f-ad50b067bad6`)) {
        sprintf(
        '"ea6e632b-d8e1-420f-bd8f-ad50b067bad6":
          "%s"
                ',
        self$`ea6e632b-d8e1-420f-bd8f-ad50b067bad6`
        )},
        if (!is.null(self$`7491e52d-97e8-4759-8a63-c8ea8a75f822`)) {
        sprintf(
        '"7491e52d-97e8-4759-8a63-c8ea8a75f822":
          "%s"
                ',
        self$`7491e52d-97e8-4759-8a63-c8ea8a75f822`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse2005ConfigIdByConfigTypeIdJson) {
      InlineResponse2005ConfigIdByConfigTypeIdObject <- jsonlite::fromJSON(InlineResponse2005ConfigIdByConfigTypeIdJson)
      self$`d75e27f0-ebab-4567-8440-c24f02f2eca5` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`d75e27f0-ebab-4567-8440-c24f02f2eca5`
      self$`cf3962b1-a98e-4ade-ae25-cdc388e7feb3` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`cf3962b1-a98e-4ade-ae25-cdc388e7feb3`
      self$`2c1998a1-32e2-4084-b20a-b580570f4fbf` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`2c1998a1-32e2-4084-b20a-b580570f4fbf`
      self$`4c42c4db-f039-4a57-8264-5f57af512614` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`4c42c4db-f039-4a57-8264-5f57af512614`
      self$`7cafedc5-17b8-4c1e-8b6f-0d9bc1b4b7bc` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`7cafedc5-17b8-4c1e-8b6f-0d9bc1b4b7bc`
      self$`714a918a-7935-4b4f-82c3-afbadcd9e59b` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`714a918a-7935-4b4f-82c3-afbadcd9e59b`
      self$`b1582680-ab7b-45d0-ac36-b00f82df8e79` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`b1582680-ab7b-45d0-ac36-b00f82df8e79`
      self$`e7f6ef8d-da57-444c-b677-f03974f5d8be` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`e7f6ef8d-da57-444c-b677-f03974f5d8be`
      self$`6fa5c2bc-b7f7-47f8-9229-e927722adb27` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`6fa5c2bc-b7f7-47f8-9229-e927722adb27`
      self$`64a39300-b672-413b-9d8c-42175f7e84dd` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`64a39300-b672-413b-9d8c-42175f7e84dd`
      self$`ea6e632b-d8e1-420f-bd8f-ad50b067bad6` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`ea6e632b-d8e1-420f-bd8f-ad50b067bad6`
      self$`7491e52d-97e8-4759-8a63-c8ea8a75f822` <- InlineResponse2005ConfigIdByConfigTypeIdObject$`7491e52d-97e8-4759-8a63-c8ea8a75f822`
      self
    }
  )
)
