# untitled API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 5229
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineObject
#' @description InlineObject Class
#' @format An \code{R6Class} generator object
#' @field name  character 
#'
#' @field size  character 
#'
#' @field locationCode  character 
#'
#' @field productVersion  character 
#'
#' @field networkGroupId  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineObject <- R6::R6Class(
  'InlineObject',
  public = list(
    `name` = NULL,
    `size` = NULL,
    `locationCode` = NULL,
    `productVersion` = NULL,
    `networkGroupId` = NULL,
    initialize = function(`name`, `size`, `locationCode`, `productVersion`, `networkGroupId`, ...){
      local.optional.var <- list(...)
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`size`)) {
        stopifnot(is.character(`size`), length(`size`) == 1)
        self$`size` <- `size`
      }
      if (!missing(`locationCode`)) {
        stopifnot(is.character(`locationCode`), length(`locationCode`) == 1)
        self$`locationCode` <- `locationCode`
      }
      if (!missing(`productVersion`)) {
        stopifnot(is.character(`productVersion`), length(`productVersion`) == 1)
        self$`productVersion` <- `productVersion`
      }
      if (!missing(`networkGroupId`)) {
        stopifnot(is.character(`networkGroupId`), length(`networkGroupId`) == 1)
        self$`networkGroupId` <- `networkGroupId`
      }
    },
    toJSON = function() {
      InlineObjectObject <- list()
      if (!is.null(self$`name`)) {
        InlineObjectObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`size`)) {
        InlineObjectObject[['size']] <-
          self$`size`
      }
      if (!is.null(self$`locationCode`)) {
        InlineObjectObject[['locationCode']] <-
          self$`locationCode`
      }
      if (!is.null(self$`productVersion`)) {
        InlineObjectObject[['productVersion']] <-
          self$`productVersion`
      }
      if (!is.null(self$`networkGroupId`)) {
        InlineObjectObject[['networkGroupId']] <-
          self$`networkGroupId`
      }

      InlineObjectObject
    },
    fromJSON = function(InlineObjectJson) {
      InlineObjectObject <- jsonlite::fromJSON(InlineObjectJson)
      if (!is.null(InlineObjectObject$`name`)) {
        self$`name` <- InlineObjectObject$`name`
      }
      if (!is.null(InlineObjectObject$`size`)) {
        self$`size` <- InlineObjectObject$`size`
      }
      if (!is.null(InlineObjectObject$`locationCode`)) {
        self$`locationCode` <- InlineObjectObject$`locationCode`
      }
      if (!is.null(InlineObjectObject$`productVersion`)) {
        self$`productVersion` <- InlineObjectObject$`productVersion`
      }
      if (!is.null(InlineObjectObject$`networkGroupId`)) {
        self$`networkGroupId` <- InlineObjectObject$`networkGroupId`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`size`)) {
        sprintf(
        '"size":
          "%s"
                ',
        self$`size`
        )},
        if (!is.null(self$`locationCode`)) {
        sprintf(
        '"locationCode":
          "%s"
                ',
        self$`locationCode`
        )},
        if (!is.null(self$`productVersion`)) {
        sprintf(
        '"productVersion":
          "%s"
                ',
        self$`productVersion`
        )},
        if (!is.null(self$`networkGroupId`)) {
        sprintf(
        '"networkGroupId":
          "%s"
                ',
        self$`networkGroupId`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineObjectJson) {
      InlineObjectObject <- jsonlite::fromJSON(InlineObjectJson)
      self$`name` <- InlineObjectObject$`name`
      self$`size` <- InlineObjectObject$`size`
      self$`locationCode` <- InlineObjectObject$`locationCode`
      self$`productVersion` <- InlineObjectObject$`productVersion`
      self$`networkGroupId` <- InlineObjectObject$`networkGroupId`
      self
    }
  )
)
