-module(openapi_inline_response_200_12).

-export([encode/1]).

-export_type([openapi_inline_response_200_12/0]).

-type openapi_inline_response_200_12() ::
    #{ 'deletedAt' := openapi_any_type:openapi_any_type(),
       'networkId' := binary(),
       'name' := binary(),
       'updatedAt' := binary(),
       'provider' := openapi_any_type:openapi_any_type(),
       'online' := boolean(),
       'zitiId' := binary(),
       'userData' := openapi_any_type:openapi_any_type(),
       'ownerIdentityId' := binary(),
       'attributes' := list(),
       'providerId' := openapi_any_type:openapi_any_type(),
       'jwt' := openapi_any_type:openapi_any_type(),
       'id' := binary(),
       'ipAddress' := openapi_any_type:openapi_any_type(),
       'status' := binary(),
       'hostId' := openapi_any_type:openapi_any_type(),
       'createdAt' := binary(),
       'createdBy' := binary(),
       'deletedBy' := openapi_any_type:openapi_any_type(),
       'locationMetadataId' := openapi_any_type:openapi_any_type(),
       'linkListener' := boolean(),
       'dataCenterId' := openapi_any_type:openapi_any_type(),
       'verified' := boolean(),
       '_links' := openapi_inline_response_200__links:openapi_inline_response_200__links()
     }.

encode(#{ 'deletedAt' := DeletedAt,
          'networkId' := NetworkId,
          'name' := Name,
          'updatedAt' := UpdatedAt,
          'provider' := Provider,
          'online' := Online,
          'zitiId' := ZitiId,
          'userData' := UserData,
          'ownerIdentityId' := OwnerIdentityId,
          'attributes' := Attributes,
          'providerId' := ProviderId,
          'jwt' := Jwt,
          'id' := Id,
          'ipAddress' := IpAddress,
          'status' := Status,
          'hostId' := HostId,
          'createdAt' := CreatedAt,
          'createdBy' := CreatedBy,
          'deletedBy' := DeletedBy,
          'locationMetadataId' := LocationMetadataId,
          'linkListener' := LinkListener,
          'dataCenterId' := DataCenterId,
          'verified' := Verified,
          '_links' := Links
        }) ->
    #{ 'deletedAt' => DeletedAt,
       'networkId' => NetworkId,
       'name' => Name,
       'updatedAt' => UpdatedAt,
       'provider' => Provider,
       'online' => Online,
       'zitiId' => ZitiId,
       'userData' => UserData,
       'ownerIdentityId' => OwnerIdentityId,
       'attributes' => Attributes,
       'providerId' => ProviderId,
       'jwt' => Jwt,
       'id' => Id,
       'ipAddress' => IpAddress,
       'status' => Status,
       'hostId' => HostId,
       'createdAt' => CreatedAt,
       'createdBy' => CreatedBy,
       'deletedBy' => DeletedBy,
       'locationMetadataId' => LocationMetadataId,
       'linkListener' => LinkListener,
       'dataCenterId' => DataCenterId,
       'verified' => Verified,
       '_links' => Links
     }.
