-module(openapi_inline_response_200_19_7_3_4).

-export([encode/1]).

-export_type([openapi_inline_response_200_19_7_3_4/0]).

-type openapi_inline_response_200_19_7_3_4() ::
    #{ 'zitiCliLinuxBinary_sha_1' := binary(),
       'zitiTunnelLinuxBinary' := binary(),
       'zitiTunnelLinuxBinary_sha_1' := binary(),
       'zitiControllerBinary' := binary(),
       'zitiCliLinuxBinary_md5' := binary(),
       'zitiRouterLinuxBinary_sha_1' := binary(),
       'zitiRouterLinuxArmBinary_md5' := binary(),
       'zitiRouterLinuxBinary_sha_256' := binary(),
       'zitiCliLinuxArmBinary' := binary(),
       'zitiRouterLinuxBinary_md5' := binary(),
       'zitiWindowsDesktopEdge' := binary(),
       'zitiRouterLinuxArmBinary_sha_256' := binary(),
       'zitiMacDesktopEdge' := binary(),
       'zitiControllerBinary_sha_1' := binary(),
       'zitiControllerBinary_md5' := binary(),
       'zitiControllerBinary_sha_256' := binary(),
       'zitiIosEdge' := binary(),
       'zitiCliLinuxBinary' := binary(),
       'zitiRouterLinuxArmBinary_sha_1' := binary(),
       'zitiVersion' := binary(),
       'zitiCliLinuxArmBinary_sha_1' := binary(),
       'zitiTunnelLinuxArmBinary_sha_1' := binary(),
       'zitiTunnelLinuxArmBinary' := binary(),
       'zitiCliLinuxArmBinary_sha_256' := binary(),
       'zitiRouterLinuxBinary' := binary(),
       'zitiTunnelLinuxBinary_sha_256' := binary(),
       'zitiAndroidEdge' := binary(),
       'zitiTunnelLinuxArmBinary_md5' := binary(),
       'zitiTunnelLinuxBinary_md5' := binary(),
       'zitiRouterLinuxArmBinary' := binary(),
       'zitiCliLinuxArmBinary_md5' := binary(),
       'zitiTunnelLinuxArmBinary_sha_256' := binary(),
       'zitiCliLinuxBinary_sha_256' := binary(),
       'active' := boolean()
     }.

encode(#{ 'zitiCliLinuxBinary_sha_1' := ZitiCliLinuxBinarySha1,
          'zitiTunnelLinuxBinary' := ZitiTunnelLinuxBinary,
          'zitiTunnelLinuxBinary_sha_1' := ZitiTunnelLinuxBinarySha1,
          'zitiControllerBinary' := ZitiControllerBinary,
          'zitiCliLinuxBinary_md5' := ZitiCliLinuxBinaryMd5,
          'zitiRouterLinuxBinary_sha_1' := ZitiRouterLinuxBinarySha1,
          'zitiRouterLinuxArmBinary_md5' := ZitiRouterLinuxArmBinaryMd5,
          'zitiRouterLinuxBinary_sha_256' := ZitiRouterLinuxBinarySha256,
          'zitiCliLinuxArmBinary' := ZitiCliLinuxArmBinary,
          'zitiRouterLinuxBinary_md5' := ZitiRouterLinuxBinaryMd5,
          'zitiWindowsDesktopEdge' := ZitiWindowsDesktopEdge,
          'zitiRouterLinuxArmBinary_sha_256' := ZitiRouterLinuxArmBinarySha256,
          'zitiMacDesktopEdge' := ZitiMacDesktopEdge,
          'zitiControllerBinary_sha_1' := ZitiControllerBinarySha1,
          'zitiControllerBinary_md5' := ZitiControllerBinaryMd5,
          'zitiControllerBinary_sha_256' := ZitiControllerBinarySha256,
          'zitiIosEdge' := ZitiIosEdge,
          'zitiCliLinuxBinary' := ZitiCliLinuxBinary,
          'zitiRouterLinuxArmBinary_sha_1' := ZitiRouterLinuxArmBinarySha1,
          'zitiVersion' := ZitiVersion,
          'zitiCliLinuxArmBinary_sha_1' := ZitiCliLinuxArmBinarySha1,
          'zitiTunnelLinuxArmBinary_sha_1' := ZitiTunnelLinuxArmBinarySha1,
          'zitiTunnelLinuxArmBinary' := ZitiTunnelLinuxArmBinary,
          'zitiCliLinuxArmBinary_sha_256' := ZitiCliLinuxArmBinarySha256,
          'zitiRouterLinuxBinary' := ZitiRouterLinuxBinary,
          'zitiTunnelLinuxBinary_sha_256' := ZitiTunnelLinuxBinarySha256,
          'zitiAndroidEdge' := ZitiAndroidEdge,
          'zitiTunnelLinuxArmBinary_md5' := ZitiTunnelLinuxArmBinaryMd5,
          'zitiTunnelLinuxBinary_md5' := ZitiTunnelLinuxBinaryMd5,
          'zitiRouterLinuxArmBinary' := ZitiRouterLinuxArmBinary,
          'zitiCliLinuxArmBinary_md5' := ZitiCliLinuxArmBinaryMd5,
          'zitiTunnelLinuxArmBinary_sha_256' := ZitiTunnelLinuxArmBinarySha256,
          'zitiCliLinuxBinary_sha_256' := ZitiCliLinuxBinarySha256,
          'active' := Active
        }) ->
    #{ 'zitiCliLinuxBinary.sha-1' => ZitiCliLinuxBinarySha1,
       'zitiTunnelLinuxBinary' => ZitiTunnelLinuxBinary,
       'zitiTunnelLinuxBinary.sha-1' => ZitiTunnelLinuxBinarySha1,
       'zitiControllerBinary' => ZitiControllerBinary,
       'zitiCliLinuxBinary.md5' => ZitiCliLinuxBinaryMd5,
       'zitiRouterLinuxBinary.sha-1' => ZitiRouterLinuxBinarySha1,
       'zitiRouterLinuxArmBinary.md5' => ZitiRouterLinuxArmBinaryMd5,
       'zitiRouterLinuxBinary.sha-256' => ZitiRouterLinuxBinarySha256,
       'zitiCliLinuxArmBinary' => ZitiCliLinuxArmBinary,
       'zitiRouterLinuxBinary.md5' => ZitiRouterLinuxBinaryMd5,
       'zitiWindowsDesktopEdge' => ZitiWindowsDesktopEdge,
       'zitiRouterLinuxArmBinary.sha-256' => ZitiRouterLinuxArmBinarySha256,
       'zitiMacDesktopEdge' => ZitiMacDesktopEdge,
       'zitiControllerBinary.sha-1' => ZitiControllerBinarySha1,
       'zitiControllerBinary.md5' => ZitiControllerBinaryMd5,
       'zitiControllerBinary.sha-256' => ZitiControllerBinarySha256,
       'zitiIosEdge' => ZitiIosEdge,
       'zitiCliLinuxBinary' => ZitiCliLinuxBinary,
       'zitiRouterLinuxArmBinary.sha-1' => ZitiRouterLinuxArmBinarySha1,
       'zitiVersion' => ZitiVersion,
       'zitiCliLinuxArmBinary.sha-1' => ZitiCliLinuxArmBinarySha1,
       'zitiTunnelLinuxArmBinary.sha-1' => ZitiTunnelLinuxArmBinarySha1,
       'zitiTunnelLinuxArmBinary' => ZitiTunnelLinuxArmBinary,
       'zitiCliLinuxArmBinary.sha-256' => ZitiCliLinuxArmBinarySha256,
       'zitiRouterLinuxBinary' => ZitiRouterLinuxBinary,
       'zitiTunnelLinuxBinary.sha-256' => ZitiTunnelLinuxBinarySha256,
       'zitiAndroidEdge' => ZitiAndroidEdge,
       'zitiTunnelLinuxArmBinary.md5' => ZitiTunnelLinuxArmBinaryMd5,
       'zitiTunnelLinuxBinary.md5' => ZitiTunnelLinuxBinaryMd5,
       'zitiRouterLinuxArmBinary' => ZitiRouterLinuxArmBinary,
       'zitiCliLinuxArmBinary.md5' => ZitiCliLinuxArmBinaryMd5,
       'zitiTunnelLinuxArmBinary.sha-256' => ZitiTunnelLinuxArmBinarySha256,
       'zitiCliLinuxBinary.sha-256' => ZitiCliLinuxBinarySha256,
       'active' => Active
     }.
