/**
 * untitled API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5227
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { InlineResponse200LinksNetwork } from './inlineResponse200LinksNetwork';
import { InlineResponse200LinksSelf } from './inlineResponse200LinksSelf';

export class InlineResponse2021Links {
    'network': InlineResponse200LinksNetwork;
    'process': InlineResponse200LinksNetwork;
    'self': InlineResponse200LinksSelf;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "network",
            "baseName": "network",
            "type": "InlineResponse200LinksNetwork"
        },
        {
            "name": "process",
            "baseName": "process",
            "type": "InlineResponse200LinksNetwork"
        },
        {
            "name": "self",
            "baseName": "self",
            "type": "InlineResponse200LinksSelf"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2021Links.attributeTypeMap;
    }
}

