/* 
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5170
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing CoreV2ServicesModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CoreV2ServicesModelTests
    {
        // TODO uncomment below to declare an instance variable for CoreV2ServicesModel
        //private CoreV2ServicesModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CoreV2ServicesModel
            //instance = new CoreV2ServicesModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CoreV2ServicesModel
        /// </summary>
        [Test]
        public void CoreV2ServicesModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CoreV2ServicesModel
            //Assert.IsInstanceOf(typeof(CoreV2ServicesModel), instance);
        }


        /// <summary>
        /// Test the property 'EdgeRouterAttributes'
        /// </summary>
        [Test]
        public void EdgeRouterAttributesTest()
        {
            // TODO unit test for the property 'EdgeRouterAttributes'
        }
        /// <summary>
        /// Test the property 'ServerEgress'
        /// </summary>
        [Test]
        public void ServerEgressTest()
        {
            // TODO unit test for the property 'ServerEgress'
        }
        /// <summary>
        /// Test the property 'BindEndpointAttributes'
        /// </summary>
        [Test]
        public void BindEndpointAttributesTest()
        {
            // TODO unit test for the property 'BindEndpointAttributes'
        }
        /// <summary>
        /// Test the property 'ClientIngress'
        /// </summary>
        [Test]
        public void ClientIngressTest()
        {
            // TODO unit test for the property 'ClientIngress'
        }
        /// <summary>
        /// Test the property 'EdgeRouterHosts'
        /// </summary>
        [Test]
        public void EdgeRouterHostsTest()
        {
            // TODO unit test for the property 'EdgeRouterHosts'
        }

    }

}
