/* 
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5170
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing CoreV2ServicesModelClientIngressPorts
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CoreV2ServicesModelClientIngressPortsTests
    {
        // TODO uncomment below to declare an instance variable for CoreV2ServicesModelClientIngressPorts
        //private CoreV2ServicesModelClientIngressPorts instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CoreV2ServicesModelClientIngressPorts
            //instance = new CoreV2ServicesModelClientIngressPorts();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CoreV2ServicesModelClientIngressPorts
        /// </summary>
        [Test]
        public void CoreV2ServicesModelClientIngressPortsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CoreV2ServicesModelClientIngressPorts
            //Assert.IsInstanceOf(typeof(CoreV2ServicesModelClientIngressPorts), instance);
        }


        /// <summary>
        /// Test the property 'High'
        /// </summary>
        [Test]
        public void HighTest()
        {
            // TODO unit test for the property 'High'
        }
        /// <summary>
        /// Test the property 'Low'
        /// </summary>
        [Test]
        public void LowTest()
        {
            // TODO unit test for the property 'Low'
        }

    }

}
