/* 
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5170
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20017Embedded
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse20017EmbeddedTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20017Embedded
        //private InlineResponse20017Embedded instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20017Embedded
            //instance = new InlineResponse20017Embedded();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20017Embedded
        /// </summary>
        [Test]
        public void InlineResponse20017EmbeddedInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineResponse20017Embedded
            //Assert.IsInstanceOf(typeof(InlineResponse20017Embedded), instance);
        }


        /// <summary>
        /// Test the property 'Organizations'
        /// </summary>
        [Test]
        public void OrganizationsTest()
        {
            // TODO unit test for the property 'Organizations'
        }

    }

}
