/* 
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5170
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObjectTests
    {
        // TODO uncomment below to declare an instance variable for InlineObject
        //private InlineObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineObject
            //instance = new InlineObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineObject
        /// </summary>
        [Test]
        public void InlineObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineObject
            //Assert.IsInstanceOf(typeof(InlineObject), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'LocationCode'
        /// </summary>
        [Test]
        public void LocationCodeTest()
        {
            // TODO unit test for the property 'LocationCode'
        }
        /// <summary>
        /// Test the property 'ProductVersion'
        /// </summary>
        [Test]
        public void ProductVersionTest()
        {
            // TODO unit test for the property 'ProductVersion'
        }
        /// <summary>
        /// Test the property 'NetworkGroupId'
        /// </summary>
        [Test]
        public void NetworkGroupIdTest()
        {
            // TODO unit test for the property 'NetworkGroupId'
        }

    }

}
