/* 
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5170
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2001LinksSelf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2001LinksSelfTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2001LinksSelf
        //private InlineResponse2001LinksSelf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2001LinksSelf
            //instance = new InlineResponse2001LinksSelf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2001LinksSelf
        /// </summary>
        [Test]
        public void InlineResponse2001LinksSelfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineResponse2001LinksSelf
            //Assert.IsInstanceOf(typeof(InlineResponse2001LinksSelf), instance);
        }


        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }
        /// <summary>
        /// Test the property 'Templated'
        /// </summary>
        [Test]
        public void TemplatedTest()
        {
            // TODO unit test for the property 'Templated'
        }

    }

}
