/* 
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5170
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2004EmbeddedEdgeRouterPolicyList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2004EmbeddedEdgeRouterPolicyListTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2004EmbeddedEdgeRouterPolicyList
        //private InlineResponse2004EmbeddedEdgeRouterPolicyList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2004EmbeddedEdgeRouterPolicyList
            //instance = new InlineResponse2004EmbeddedEdgeRouterPolicyList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2004EmbeddedEdgeRouterPolicyList
        /// </summary>
        [Test]
        public void InlineResponse2004EmbeddedEdgeRouterPolicyListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineResponse2004EmbeddedEdgeRouterPolicyList
            //Assert.IsInstanceOf(typeof(InlineResponse2004EmbeddedEdgeRouterPolicyList), instance);
        }


        /// <summary>
        /// Test the property 'DeletedAt'
        /// </summary>
        [Test]
        public void DeletedAtTest()
        {
            // TODO unit test for the property 'DeletedAt'
        }
        /// <summary>
        /// Test the property 'NetworkId'
        /// </summary>
        [Test]
        public void NetworkIdTest()
        {
            // TODO unit test for the property 'NetworkId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'EdgeRouterAttributes'
        /// </summary>
        [Test]
        public void EdgeRouterAttributesTest()
        {
            // TODO unit test for the property 'EdgeRouterAttributes'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'ZitiId'
        /// </summary>
        [Test]
        public void ZitiIdTest()
        {
            // TODO unit test for the property 'ZitiId'
        }
        /// <summary>
        /// Test the property 'OwnerIdentityId'
        /// </summary>
        [Test]
        public void OwnerIdentityIdTest()
        {
            // TODO unit test for the property 'OwnerIdentityId'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Test]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'DeletedBy'
        /// </summary>
        [Test]
        public void DeletedByTest()
        {
            // TODO unit test for the property 'DeletedBy'
        }
        /// <summary>
        /// Test the property 'EndpointAttributes'
        /// </summary>
        [Test]
        public void EndpointAttributesTest()
        {
            // TODO unit test for the property 'EndpointAttributes'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
