/* 
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5229
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// InlineResponse20011Links
    /// </summary>
    [DataContract]
    public partial class InlineResponse20011Links :  IEquatable<InlineResponse20011Links>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20011Links" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InlineResponse20011Links() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20011Links" /> class.
        /// </summary>
        /// <param name="azureSubscription">azureSubscription (required).</param>
        /// <param name="networks">networks (required).</param>
        /// <param name="self">self (required).</param>
        public InlineResponse20011Links(InlineResponse200LinksSelf azureSubscription = default(InlineResponse200LinksSelf), InlineResponse200LinksSelf networks = default(InlineResponse200LinksSelf), InlineResponse200LinksSelf self = default(InlineResponse200LinksSelf))
        {
            // to ensure "azureSubscription" is required (not null)
            if (azureSubscription == null)
            {
                throw new InvalidDataException("azureSubscription is a required property for InlineResponse20011Links and cannot be null");
            }
            else
            {
                this.AzureSubscription = azureSubscription;
            }
            
            // to ensure "networks" is required (not null)
            if (networks == null)
            {
                throw new InvalidDataException("networks is a required property for InlineResponse20011Links and cannot be null");
            }
            else
            {
                this.Networks = networks;
            }
            
            // to ensure "self" is required (not null)
            if (self == null)
            {
                throw new InvalidDataException("self is a required property for InlineResponse20011Links and cannot be null");
            }
            else
            {
                this.Self = self;
            }
            
        }
        
        /// <summary>
        /// Gets or Sets AzureSubscription
        /// </summary>
        [DataMember(Name="azureSubscription", EmitDefaultValue=true)]
        public InlineResponse200LinksSelf AzureSubscription { get; set; }

        /// <summary>
        /// Gets or Sets Networks
        /// </summary>
        [DataMember(Name="networks", EmitDefaultValue=true)]
        public InlineResponse200LinksSelf Networks { get; set; }

        /// <summary>
        /// Gets or Sets Self
        /// </summary>
        [DataMember(Name="self", EmitDefaultValue=true)]
        public InlineResponse200LinksSelf Self { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse20011Links {\n");
            sb.Append("  AzureSubscription: ").Append(AzureSubscription).Append("\n");
            sb.Append("  Networks: ").Append(Networks).Append("\n");
            sb.Append("  Self: ").Append(Self).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse20011Links);
        }

        /// <summary>
        /// Returns true if InlineResponse20011Links instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse20011Links to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse20011Links input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AzureSubscription == input.AzureSubscription ||
                    (this.AzureSubscription != null &&
                    this.AzureSubscription.Equals(input.AzureSubscription))
                ) && 
                (
                    this.Networks == input.Networks ||
                    (this.Networks != null &&
                    this.Networks.Equals(input.Networks))
                ) && 
                (
                    this.Self == input.Self ||
                    (this.Self != null &&
                    this.Self.Equals(input.Self))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AzureSubscription != null)
                    hashCode = hashCode * 59 + this.AzureSubscription.GetHashCode();
                if (this.Networks != null)
                    hashCode = hashCode * 59 + this.Networks.GetHashCode();
                if (this.Self != null)
                    hashCode = hashCode * 59 + this.Self.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
