/* 
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5229
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// InlineObject4
    /// </summary>
    [DataContract]
    public partial class InlineObject4 :  IEquatable<InlineObject4>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineObject4" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InlineObject4() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineObject4" /> class.
        /// </summary>
        /// <param name="serviceAttributes">serviceAttributes (required).</param>
        /// <param name="networkId">networkId (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="postureCheckAttributes">postureCheckAttributes (required).</param>
        /// <param name="endpointAttributes">endpointAttributes (required).</param>
        public InlineObject4(List<string> serviceAttributes = default(List<string>), string networkId = default(string), string name = default(string), List<AnyType> postureCheckAttributes = default(List<AnyType>), List<string> endpointAttributes = default(List<string>))
        {
            // to ensure "serviceAttributes" is required (not null)
            if (serviceAttributes == null)
            {
                throw new InvalidDataException("serviceAttributes is a required property for InlineObject4 and cannot be null");
            }
            else
            {
                this.ServiceAttributes = serviceAttributes;
            }
            
            // to ensure "networkId" is required (not null)
            if (networkId == null)
            {
                throw new InvalidDataException("networkId is a required property for InlineObject4 and cannot be null");
            }
            else
            {
                this.NetworkId = networkId;
            }
            
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for InlineObject4 and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            
            // to ensure "postureCheckAttributes" is required (not null)
            if (postureCheckAttributes == null)
            {
                throw new InvalidDataException("postureCheckAttributes is a required property for InlineObject4 and cannot be null");
            }
            else
            {
                this.PostureCheckAttributes = postureCheckAttributes;
            }
            
            // to ensure "endpointAttributes" is required (not null)
            if (endpointAttributes == null)
            {
                throw new InvalidDataException("endpointAttributes is a required property for InlineObject4 and cannot be null");
            }
            else
            {
                this.EndpointAttributes = endpointAttributes;
            }
            
        }
        
        /// <summary>
        /// Gets or Sets ServiceAttributes
        /// </summary>
        [DataMember(Name="serviceAttributes", EmitDefaultValue=true)]
        public List<string> ServiceAttributes { get; set; }

        /// <summary>
        /// Gets or Sets NetworkId
        /// </summary>
        [DataMember(Name="networkId", EmitDefaultValue=true)]
        public string NetworkId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets PostureCheckAttributes
        /// </summary>
        [DataMember(Name="postureCheckAttributes", EmitDefaultValue=true)]
        public List<AnyType> PostureCheckAttributes { get; set; }

        /// <summary>
        /// Gets or Sets EndpointAttributes
        /// </summary>
        [DataMember(Name="endpointAttributes", EmitDefaultValue=true)]
        public List<string> EndpointAttributes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineObject4 {\n");
            sb.Append("  ServiceAttributes: ").Append(ServiceAttributes).Append("\n");
            sb.Append("  NetworkId: ").Append(NetworkId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  PostureCheckAttributes: ").Append(PostureCheckAttributes).Append("\n");
            sb.Append("  EndpointAttributes: ").Append(EndpointAttributes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineObject4);
        }

        /// <summary>
        /// Returns true if InlineObject4 instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineObject4 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineObject4 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ServiceAttributes == input.ServiceAttributes ||
                    this.ServiceAttributes != null &&
                    input.ServiceAttributes != null &&
                    this.ServiceAttributes.SequenceEqual(input.ServiceAttributes)
                ) && 
                (
                    this.NetworkId == input.NetworkId ||
                    (this.NetworkId != null &&
                    this.NetworkId.Equals(input.NetworkId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.PostureCheckAttributes == input.PostureCheckAttributes ||
                    this.PostureCheckAttributes != null &&
                    input.PostureCheckAttributes != null &&
                    this.PostureCheckAttributes.SequenceEqual(input.PostureCheckAttributes)
                ) && 
                (
                    this.EndpointAttributes == input.EndpointAttributes ||
                    this.EndpointAttributes != null &&
                    input.EndpointAttributes != null &&
                    this.EndpointAttributes.SequenceEqual(input.EndpointAttributes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ServiceAttributes != null)
                    hashCode = hashCode * 59 + this.ServiceAttributes.GetHashCode();
                if (this.NetworkId != null)
                    hashCode = hashCode * 59 + this.NetworkId.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.PostureCheckAttributes != null)
                    hashCode = hashCode * 59 + this.PostureCheckAttributes.GetHashCode();
                if (this.EndpointAttributes != null)
                    hashCode = hashCode * 59 + this.EndpointAttributes.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
