---

  # declare entities from a vars dict "embedded" containing the data structure
  # exported / downloaded from the NF console's "manage networks" list of
  # networks
- hosts: localhost
  gather_facts: False
  roles:
    - { role: network_from_download, tags: ['netfoundry'] }
  collections:
      - netfoundry.platform
  vars:
    # download as YAML from NF web console
    # downloaded_network_file: /netfoundry/downloaded_network.yml
    # netfoundry_credentials: /netfoundry/credentials.json
