<?php
/**
 * InlineResponse2023ConfigIdByConfigTypeId
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5170
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * InlineResponse2023ConfigIdByConfigTypeId Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InlineResponse2023ConfigIdByConfigTypeId implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'inline_response_202_3_configIdByConfigTypeId';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        '_714a918a_7935_4b4f_82c3_afbadcd9e59b' => 'string',
        '_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc' => 'string',
        'd75e27f0_ebab_4567_8440_c24f02f2eca5' => 'string',
        'ea6e632b_d8e1_420f_bd8f_ad50b067bad6' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        '_714a918a_7935_4b4f_82c3_afbadcd9e59b' => null,
        '_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc' => null,
        'd75e27f0_ebab_4567_8440_c24f02f2eca5' => null,
        'ea6e632b_d8e1_420f_bd8f_ad50b067bad6' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        '_714a918a_7935_4b4f_82c3_afbadcd9e59b' => '714a918a-7935-4b4f-82c3-afbadcd9e59b',
        '_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc' => '7cafedc5-17b8-4c1e-8b6f-0d9bc1b4b7bc',
        'd75e27f0_ebab_4567_8440_c24f02f2eca5' => 'd75e27f0-ebab-4567-8440-c24f02f2eca5',
        'ea6e632b_d8e1_420f_bd8f_ad50b067bad6' => 'ea6e632b-d8e1-420f-bd8f-ad50b067bad6'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        '_714a918a_7935_4b4f_82c3_afbadcd9e59b' => 'set714a918a79354b4f82c3Afbadcd9e59b',
        '_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc' => 'set7cafedc517b84c1e8b6f0d9bc1b4b7bc',
        'd75e27f0_ebab_4567_8440_c24f02f2eca5' => 'setD75e27f0Ebab45678440C24f02f2eca5',
        'ea6e632b_d8e1_420f_bd8f_ad50b067bad6' => 'setEa6e632bD8e1420fBd8fAd50b067bad6'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        '_714a918a_7935_4b4f_82c3_afbadcd9e59b' => 'get714a918a79354b4f82c3Afbadcd9e59b',
        '_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc' => 'get7cafedc517b84c1e8b6f0d9bc1b4b7bc',
        'd75e27f0_ebab_4567_8440_c24f02f2eca5' => 'getD75e27f0Ebab45678440C24f02f2eca5',
        'ea6e632b_d8e1_420f_bd8f_ad50b067bad6' => 'getEa6e632bD8e1420fBd8fAd50b067bad6'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['_714a918a_7935_4b4f_82c3_afbadcd9e59b'] = isset($data['_714a918a_7935_4b4f_82c3_afbadcd9e59b']) ? $data['_714a918a_7935_4b4f_82c3_afbadcd9e59b'] : null;
        $this->container['_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc'] = isset($data['_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc']) ? $data['_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc'] : null;
        $this->container['d75e27f0_ebab_4567_8440_c24f02f2eca5'] = isset($data['d75e27f0_ebab_4567_8440_c24f02f2eca5']) ? $data['d75e27f0_ebab_4567_8440_c24f02f2eca5'] : null;
        $this->container['ea6e632b_d8e1_420f_bd8f_ad50b067bad6'] = isset($data['ea6e632b_d8e1_420f_bd8f_ad50b067bad6']) ? $data['ea6e632b_d8e1_420f_bd8f_ad50b067bad6'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets _714a918a_7935_4b4f_82c3_afbadcd9e59b
     *
     * @return string|null
     */
    public function get714a918a79354b4f82c3Afbadcd9e59b()
    {
        return $this->container['_714a918a_7935_4b4f_82c3_afbadcd9e59b'];
    }

    /**
     * Sets _714a918a_7935_4b4f_82c3_afbadcd9e59b
     *
     * @param string|null $_714a918a_7935_4b4f_82c3_afbadcd9e59b _714a918a_7935_4b4f_82c3_afbadcd9e59b
     *
     * @return $this
     */
    public function set714a918a79354b4f82c3Afbadcd9e59b($_714a918a_7935_4b4f_82c3_afbadcd9e59b)
    {
        $this->container['_714a918a_7935_4b4f_82c3_afbadcd9e59b'] = $_714a918a_7935_4b4f_82c3_afbadcd9e59b;

        return $this;
    }

    /**
     * Gets _7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc
     *
     * @return string|null
     */
    public function get7cafedc517b84c1e8b6f0d9bc1b4b7bc()
    {
        return $this->container['_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc'];
    }

    /**
     * Sets _7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc
     *
     * @param string|null $_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc _7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc
     *
     * @return $this
     */
    public function set7cafedc517b84c1e8b6f0d9bc1b4b7bc($_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc)
    {
        $this->container['_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc'] = $_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc;

        return $this;
    }

    /**
     * Gets d75e27f0_ebab_4567_8440_c24f02f2eca5
     *
     * @return string|null
     */
    public function getD75e27f0Ebab45678440C24f02f2eca5()
    {
        return $this->container['d75e27f0_ebab_4567_8440_c24f02f2eca5'];
    }

    /**
     * Sets d75e27f0_ebab_4567_8440_c24f02f2eca5
     *
     * @param string|null $d75e27f0_ebab_4567_8440_c24f02f2eca5 d75e27f0_ebab_4567_8440_c24f02f2eca5
     *
     * @return $this
     */
    public function setD75e27f0Ebab45678440C24f02f2eca5($d75e27f0_ebab_4567_8440_c24f02f2eca5)
    {
        $this->container['d75e27f0_ebab_4567_8440_c24f02f2eca5'] = $d75e27f0_ebab_4567_8440_c24f02f2eca5;

        return $this;
    }

    /**
     * Gets ea6e632b_d8e1_420f_bd8f_ad50b067bad6
     *
     * @return string|null
     */
    public function getEa6e632bD8e1420fBd8fAd50b067bad6()
    {
        return $this->container['ea6e632b_d8e1_420f_bd8f_ad50b067bad6'];
    }

    /**
     * Sets ea6e632b_d8e1_420f_bd8f_ad50b067bad6
     *
     * @param string|null $ea6e632b_d8e1_420f_bd8f_ad50b067bad6 ea6e632b_d8e1_420f_bd8f_ad50b067bad6
     *
     * @return $this
     */
    public function setEa6e632bD8e1420fBd8fAd50b067bad6($ea6e632b_d8e1_420f_bd8f_ad50b067bad6)
    {
        $this->container['ea6e632b_d8e1_420f_bd8f_ad50b067bad6'] = $ea6e632b_d8e1_420f_bd8f_ad50b067bad6;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


