<?php
/**
 * InlineResponse2003EmbeddedConfigIdByConfigTypeId
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5170
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * InlineResponse2003EmbeddedConfigIdByConfigTypeId Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InlineResponse2003EmbeddedConfigIdByConfigTypeId implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'inline_response_200_3__embedded_configIdByConfigTypeId';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'd75e27f0_ebab_4567_8440_c24f02f2eca5' => 'string',
        '_2c1998a1_32e2_4084_b20a_b580570f4fbf' => 'string',
        '_4c42c4db_f039_4a57_8264_5f57af512614' => 'string',
        '_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc' => 'string',
        '_714a918a_7935_4b4f_82c3_afbadcd9e59b' => 'string',
        'b1582680_ab7b_45d0_ac36_b00f82df8e79' => 'string',
        '_6fa5c2bc_b7f7_47f8_9229_e927722adb27' => 'string',
        '_170c6b9b_f010_46a1_a2ee_cd6729e1f5dc' => 'string',
        'ea6e632b_d8e1_420f_bd8f_ad50b067bad6' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'd75e27f0_ebab_4567_8440_c24f02f2eca5' => null,
        '_2c1998a1_32e2_4084_b20a_b580570f4fbf' => null,
        '_4c42c4db_f039_4a57_8264_5f57af512614' => null,
        '_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc' => null,
        '_714a918a_7935_4b4f_82c3_afbadcd9e59b' => null,
        'b1582680_ab7b_45d0_ac36_b00f82df8e79' => null,
        '_6fa5c2bc_b7f7_47f8_9229_e927722adb27' => null,
        '_170c6b9b_f010_46a1_a2ee_cd6729e1f5dc' => null,
        'ea6e632b_d8e1_420f_bd8f_ad50b067bad6' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'd75e27f0_ebab_4567_8440_c24f02f2eca5' => 'd75e27f0-ebab-4567-8440-c24f02f2eca5',
        '_2c1998a1_32e2_4084_b20a_b580570f4fbf' => '2c1998a1-32e2-4084-b20a-b580570f4fbf',
        '_4c42c4db_f039_4a57_8264_5f57af512614' => '4c42c4db-f039-4a57-8264-5f57af512614',
        '_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc' => '7cafedc5-17b8-4c1e-8b6f-0d9bc1b4b7bc',
        '_714a918a_7935_4b4f_82c3_afbadcd9e59b' => '714a918a-7935-4b4f-82c3-afbadcd9e59b',
        'b1582680_ab7b_45d0_ac36_b00f82df8e79' => 'b1582680-ab7b-45d0-ac36-b00f82df8e79',
        '_6fa5c2bc_b7f7_47f8_9229_e927722adb27' => '6fa5c2bc-b7f7-47f8-9229-e927722adb27',
        '_170c6b9b_f010_46a1_a2ee_cd6729e1f5dc' => '170c6b9b-f010-46a1-a2ee-cd6729e1f5dc',
        'ea6e632b_d8e1_420f_bd8f_ad50b067bad6' => 'ea6e632b-d8e1-420f-bd8f-ad50b067bad6'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'd75e27f0_ebab_4567_8440_c24f02f2eca5' => 'setD75e27f0Ebab45678440C24f02f2eca5',
        '_2c1998a1_32e2_4084_b20a_b580570f4fbf' => 'set2c1998a132e24084B20aB580570f4fbf',
        '_4c42c4db_f039_4a57_8264_5f57af512614' => 'set4c42c4dbF0394a5782645f57af512614',
        '_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc' => 'set7cafedc517b84c1e8b6f0d9bc1b4b7bc',
        '_714a918a_7935_4b4f_82c3_afbadcd9e59b' => 'set714a918a79354b4f82c3Afbadcd9e59b',
        'b1582680_ab7b_45d0_ac36_b00f82df8e79' => 'setB1582680Ab7b45d0Ac36B00f82df8e79',
        '_6fa5c2bc_b7f7_47f8_9229_e927722adb27' => 'set6fa5c2bcB7f747f89229E927722adb27',
        '_170c6b9b_f010_46a1_a2ee_cd6729e1f5dc' => 'set170c6b9bF01046a1A2eeCd6729e1f5dc',
        'ea6e632b_d8e1_420f_bd8f_ad50b067bad6' => 'setEa6e632bD8e1420fBd8fAd50b067bad6'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'd75e27f0_ebab_4567_8440_c24f02f2eca5' => 'getD75e27f0Ebab45678440C24f02f2eca5',
        '_2c1998a1_32e2_4084_b20a_b580570f4fbf' => 'get2c1998a132e24084B20aB580570f4fbf',
        '_4c42c4db_f039_4a57_8264_5f57af512614' => 'get4c42c4dbF0394a5782645f57af512614',
        '_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc' => 'get7cafedc517b84c1e8b6f0d9bc1b4b7bc',
        '_714a918a_7935_4b4f_82c3_afbadcd9e59b' => 'get714a918a79354b4f82c3Afbadcd9e59b',
        'b1582680_ab7b_45d0_ac36_b00f82df8e79' => 'getB1582680Ab7b45d0Ac36B00f82df8e79',
        '_6fa5c2bc_b7f7_47f8_9229_e927722adb27' => 'get6fa5c2bcB7f747f89229E927722adb27',
        '_170c6b9b_f010_46a1_a2ee_cd6729e1f5dc' => 'get170c6b9bF01046a1A2eeCd6729e1f5dc',
        'ea6e632b_d8e1_420f_bd8f_ad50b067bad6' => 'getEa6e632bD8e1420fBd8fAd50b067bad6'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['d75e27f0_ebab_4567_8440_c24f02f2eca5'] = isset($data['d75e27f0_ebab_4567_8440_c24f02f2eca5']) ? $data['d75e27f0_ebab_4567_8440_c24f02f2eca5'] : null;
        $this->container['_2c1998a1_32e2_4084_b20a_b580570f4fbf'] = isset($data['_2c1998a1_32e2_4084_b20a_b580570f4fbf']) ? $data['_2c1998a1_32e2_4084_b20a_b580570f4fbf'] : null;
        $this->container['_4c42c4db_f039_4a57_8264_5f57af512614'] = isset($data['_4c42c4db_f039_4a57_8264_5f57af512614']) ? $data['_4c42c4db_f039_4a57_8264_5f57af512614'] : null;
        $this->container['_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc'] = isset($data['_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc']) ? $data['_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc'] : null;
        $this->container['_714a918a_7935_4b4f_82c3_afbadcd9e59b'] = isset($data['_714a918a_7935_4b4f_82c3_afbadcd9e59b']) ? $data['_714a918a_7935_4b4f_82c3_afbadcd9e59b'] : null;
        $this->container['b1582680_ab7b_45d0_ac36_b00f82df8e79'] = isset($data['b1582680_ab7b_45d0_ac36_b00f82df8e79']) ? $data['b1582680_ab7b_45d0_ac36_b00f82df8e79'] : null;
        $this->container['_6fa5c2bc_b7f7_47f8_9229_e927722adb27'] = isset($data['_6fa5c2bc_b7f7_47f8_9229_e927722adb27']) ? $data['_6fa5c2bc_b7f7_47f8_9229_e927722adb27'] : null;
        $this->container['_170c6b9b_f010_46a1_a2ee_cd6729e1f5dc'] = isset($data['_170c6b9b_f010_46a1_a2ee_cd6729e1f5dc']) ? $data['_170c6b9b_f010_46a1_a2ee_cd6729e1f5dc'] : null;
        $this->container['ea6e632b_d8e1_420f_bd8f_ad50b067bad6'] = isset($data['ea6e632b_d8e1_420f_bd8f_ad50b067bad6']) ? $data['ea6e632b_d8e1_420f_bd8f_ad50b067bad6'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets d75e27f0_ebab_4567_8440_c24f02f2eca5
     *
     * @return string|null
     */
    public function getD75e27f0Ebab45678440C24f02f2eca5()
    {
        return $this->container['d75e27f0_ebab_4567_8440_c24f02f2eca5'];
    }

    /**
     * Sets d75e27f0_ebab_4567_8440_c24f02f2eca5
     *
     * @param string|null $d75e27f0_ebab_4567_8440_c24f02f2eca5 d75e27f0_ebab_4567_8440_c24f02f2eca5
     *
     * @return $this
     */
    public function setD75e27f0Ebab45678440C24f02f2eca5($d75e27f0_ebab_4567_8440_c24f02f2eca5)
    {
        $this->container['d75e27f0_ebab_4567_8440_c24f02f2eca5'] = $d75e27f0_ebab_4567_8440_c24f02f2eca5;

        return $this;
    }

    /**
     * Gets _2c1998a1_32e2_4084_b20a_b580570f4fbf
     *
     * @return string|null
     */
    public function get2c1998a132e24084B20aB580570f4fbf()
    {
        return $this->container['_2c1998a1_32e2_4084_b20a_b580570f4fbf'];
    }

    /**
     * Sets _2c1998a1_32e2_4084_b20a_b580570f4fbf
     *
     * @param string|null $_2c1998a1_32e2_4084_b20a_b580570f4fbf _2c1998a1_32e2_4084_b20a_b580570f4fbf
     *
     * @return $this
     */
    public function set2c1998a132e24084B20aB580570f4fbf($_2c1998a1_32e2_4084_b20a_b580570f4fbf)
    {
        $this->container['_2c1998a1_32e2_4084_b20a_b580570f4fbf'] = $_2c1998a1_32e2_4084_b20a_b580570f4fbf;

        return $this;
    }

    /**
     * Gets _4c42c4db_f039_4a57_8264_5f57af512614
     *
     * @return string|null
     */
    public function get4c42c4dbF0394a5782645f57af512614()
    {
        return $this->container['_4c42c4db_f039_4a57_8264_5f57af512614'];
    }

    /**
     * Sets _4c42c4db_f039_4a57_8264_5f57af512614
     *
     * @param string|null $_4c42c4db_f039_4a57_8264_5f57af512614 _4c42c4db_f039_4a57_8264_5f57af512614
     *
     * @return $this
     */
    public function set4c42c4dbF0394a5782645f57af512614($_4c42c4db_f039_4a57_8264_5f57af512614)
    {
        $this->container['_4c42c4db_f039_4a57_8264_5f57af512614'] = $_4c42c4db_f039_4a57_8264_5f57af512614;

        return $this;
    }

    /**
     * Gets _7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc
     *
     * @return string|null
     */
    public function get7cafedc517b84c1e8b6f0d9bc1b4b7bc()
    {
        return $this->container['_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc'];
    }

    /**
     * Sets _7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc
     *
     * @param string|null $_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc _7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc
     *
     * @return $this
     */
    public function set7cafedc517b84c1e8b6f0d9bc1b4b7bc($_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc)
    {
        $this->container['_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc'] = $_7cafedc5_17b8_4c1e_8b6f_0d9bc1b4b7bc;

        return $this;
    }

    /**
     * Gets _714a918a_7935_4b4f_82c3_afbadcd9e59b
     *
     * @return string|null
     */
    public function get714a918a79354b4f82c3Afbadcd9e59b()
    {
        return $this->container['_714a918a_7935_4b4f_82c3_afbadcd9e59b'];
    }

    /**
     * Sets _714a918a_7935_4b4f_82c3_afbadcd9e59b
     *
     * @param string|null $_714a918a_7935_4b4f_82c3_afbadcd9e59b _714a918a_7935_4b4f_82c3_afbadcd9e59b
     *
     * @return $this
     */
    public function set714a918a79354b4f82c3Afbadcd9e59b($_714a918a_7935_4b4f_82c3_afbadcd9e59b)
    {
        $this->container['_714a918a_7935_4b4f_82c3_afbadcd9e59b'] = $_714a918a_7935_4b4f_82c3_afbadcd9e59b;

        return $this;
    }

    /**
     * Gets b1582680_ab7b_45d0_ac36_b00f82df8e79
     *
     * @return string|null
     */
    public function getB1582680Ab7b45d0Ac36B00f82df8e79()
    {
        return $this->container['b1582680_ab7b_45d0_ac36_b00f82df8e79'];
    }

    /**
     * Sets b1582680_ab7b_45d0_ac36_b00f82df8e79
     *
     * @param string|null $b1582680_ab7b_45d0_ac36_b00f82df8e79 b1582680_ab7b_45d0_ac36_b00f82df8e79
     *
     * @return $this
     */
    public function setB1582680Ab7b45d0Ac36B00f82df8e79($b1582680_ab7b_45d0_ac36_b00f82df8e79)
    {
        $this->container['b1582680_ab7b_45d0_ac36_b00f82df8e79'] = $b1582680_ab7b_45d0_ac36_b00f82df8e79;

        return $this;
    }

    /**
     * Gets _6fa5c2bc_b7f7_47f8_9229_e927722adb27
     *
     * @return string|null
     */
    public function get6fa5c2bcB7f747f89229E927722adb27()
    {
        return $this->container['_6fa5c2bc_b7f7_47f8_9229_e927722adb27'];
    }

    /**
     * Sets _6fa5c2bc_b7f7_47f8_9229_e927722adb27
     *
     * @param string|null $_6fa5c2bc_b7f7_47f8_9229_e927722adb27 _6fa5c2bc_b7f7_47f8_9229_e927722adb27
     *
     * @return $this
     */
    public function set6fa5c2bcB7f747f89229E927722adb27($_6fa5c2bc_b7f7_47f8_9229_e927722adb27)
    {
        $this->container['_6fa5c2bc_b7f7_47f8_9229_e927722adb27'] = $_6fa5c2bc_b7f7_47f8_9229_e927722adb27;

        return $this;
    }

    /**
     * Gets _170c6b9b_f010_46a1_a2ee_cd6729e1f5dc
     *
     * @return string|null
     */
    public function get170c6b9bF01046a1A2eeCd6729e1f5dc()
    {
        return $this->container['_170c6b9b_f010_46a1_a2ee_cd6729e1f5dc'];
    }

    /**
     * Sets _170c6b9b_f010_46a1_a2ee_cd6729e1f5dc
     *
     * @param string|null $_170c6b9b_f010_46a1_a2ee_cd6729e1f5dc _170c6b9b_f010_46a1_a2ee_cd6729e1f5dc
     *
     * @return $this
     */
    public function set170c6b9bF01046a1A2eeCd6729e1f5dc($_170c6b9b_f010_46a1_a2ee_cd6729e1f5dc)
    {
        $this->container['_170c6b9b_f010_46a1_a2ee_cd6729e1f5dc'] = $_170c6b9b_f010_46a1_a2ee_cd6729e1f5dc;

        return $this;
    }

    /**
     * Gets ea6e632b_d8e1_420f_bd8f_ad50b067bad6
     *
     * @return string|null
     */
    public function getEa6e632bD8e1420fBd8fAd50b067bad6()
    {
        return $this->container['ea6e632b_d8e1_420f_bd8f_ad50b067bad6'];
    }

    /**
     * Sets ea6e632b_d8e1_420f_bd8f_ad50b067bad6
     *
     * @param string|null $ea6e632b_d8e1_420f_bd8f_ad50b067bad6 ea6e632b_d8e1_420f_bd8f_ad50b067bad6
     *
     * @return $this
     */
    public function setEa6e632bD8e1420fBd8fAd50b067bad6($ea6e632b_d8e1_420f_bd8f_ad50b067bad6)
    {
        $this->container['ea6e632b_d8e1_420f_bd8f_ad50b067bad6'] = $ea6e632b_d8e1_420f_bd8f_ad50b067bad6;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


