//
// InlineResponse2001Links.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse2001Links: Codable { 


    public var _self: InlineResponse2001LinksSelf

    public init(_self: InlineResponse2001LinksSelf) {
        self._self = _self
    }

    public enum CodingKeys: String, CodingKey { 
        case _self = "self"
    }

}
