//
// InlineResponse20018Embedded.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20018Embedded: Codable { 


    public var edgeRouterList: [InlineResponse20012]

    public init(edgeRouterList: [InlineResponse20012]) {
        self.edgeRouterList = edgeRouterList
    }

}
