//
// InlineResponse2007Embedded.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse2007Embedded: Codable { 


    public var endpointList: [InlineResponse2007EmbeddedEndpointList]

    public init(endpointList: [InlineResponse2007EmbeddedEndpointList]) {
        self.endpointList = endpointList
    }

}
