# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse20015EmbeddedNetworkConfigMetadataList")

model.instance <- InlineResponse20015EmbeddedNetworkConfigMetadataList$new()

test_that("networkControllerVolumeSize", {
  # tests for the property `networkControllerVolumeSize` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`networkControllerVolumeSize`, "EXPECTED_RESULT")
})

test_that("gatewayVolumeSize", {
  # tests for the property `gatewayVolumeSize` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`gatewayVolumeSize`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("gcpTransferNodeSize", {
  # tests for the property `gcpTransferNodeSize` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`gcpTransferNodeSize`, "EXPECTED_RESULT")
})

test_that("awsNetworkControllerSize", {
  # tests for the property `awsNetworkControllerSize` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`awsNetworkControllerSize`, "EXPECTED_RESULT")
})

test_that("transferNodeVolumeSize", {
  # tests for the property `transferNodeVolumeSize` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`transferNodeVolumeSize`, "EXPECTED_RESULT")
})

test_that("awsGatewaySize", {
  # tests for the property `awsGatewaySize` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`awsGatewaySize`, "EXPECTED_RESULT")
})

test_that("ocpTransferNodeSize", {
  # tests for the property `ocpTransferNodeSize` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`ocpTransferNodeSize`, "EXPECTED_RESULT")
})

test_that("awsTransferNodeSize", {
  # tests for the property `awsTransferNodeSize` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`awsTransferNodeSize`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("azureTransferNodeSize", {
  # tests for the property `azureTransferNodeSize` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`azureTransferNodeSize`, "EXPECTED_RESULT")
})

test_that("alicloudTransferNodeSize", {
  # tests for the property `alicloudTransferNodeSize` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`alicloudTransferNodeSize`, "EXPECTED_RESULT")
})

test_that("_links", {
  # tests for the property `_links` (InlineResponse2002EmbeddedLinks)

  # uncomment below to test the property 
  #expect_equal(model.instance$`_links`, "EXPECTED_RESULT")
})

