# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse2001LinksSelf")

model.instance <- InlineResponse2001LinksSelf$new()

test_that("href", {
  # tests for the property `href` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`href`, "EXPECTED_RESULT")
})

test_that("templated", {
  # tests for the property `templated` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`templated`, "EXPECTED_RESULT")
})

