# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse20015")

model.instance <- InlineResponse20015$new()

test_that("_embedded", {
  # tests for the property `_embedded` (InlineResponse20015Embedded)

  # uncomment below to test the property 
  #expect_equal(model.instance$`_embedded`, "EXPECTED_RESULT")
})

test_that("_links", {
  # tests for the property `_links` (InlineResponse2002EmbeddedLinks)

  # uncomment below to test the property 
  #expect_equal(model.instance$`_links`, "EXPECTED_RESULT")
})

test_that("page", {
  # tests for the property `page` (InlineResponse2001Page)

  # uncomment below to test the property 
  #expect_equal(model.instance$`page`, "EXPECTED_RESULT")
})

