# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CoreV2EndpointsEnrollmentMethod")

model.instance <- CoreV2EndpointsEnrollmentMethod$new()

test_that("ott", {
  # tests for the property `ott` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`ott`, "EXPECTED_RESULT")
})

