# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse5001")

model.instance <- InlineResponse5001$new()

test_that("errors", {
  # tests for the property `errors` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`errors`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (InlineResponse5001Status)

  # uncomment below to test the property 
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("traceId", {
  # tests for the property `traceId` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`traceId`, "EXPECTED_RESULT")
})

