# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse2022ConfigIdByConfigTypeId")

model.instance <- InlineResponse2022ConfigIdByConfigTypeId$new()

test_that("aca7f705-9f00-4ff6-8b86-63a4d44bde8a", {
  # tests for the property `aca7f705-9f00-4ff6-8b86-63a4d44bde8a` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`aca7f705-9f00-4ff6-8b86-63a4d44bde8a`, "EXPECTED_RESULT")
})

test_that("6cd51ae0-cfe4-499d-88d8-d02a9e18b25f", {
  # tests for the property `6cd51ae0-cfe4-499d-88d8-d02a9e18b25f` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`6cd51ae0-cfe4-499d-88d8-d02a9e18b25f`, "EXPECTED_RESULT")
})

test_that("d28725c0-9771-47d7-a9da-e408bd0adf4e", {
  # tests for the property `d28725c0-9771-47d7-a9da-e408bd0adf4e` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`d28725c0-9771-47d7-a9da-e408bd0adf4e`, "EXPECTED_RESULT")
})

test_that("888d6565-4359-4d91-b38d-0a24124e4456", {
  # tests for the property `888d6565-4359-4d91-b38d-0a24124e4456` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`888d6565-4359-4d91-b38d-0a24124e4456`, "EXPECTED_RESULT")
})

test_that("feb075cd-dd2b-47c5-922c-86ef3b06fb16", {
  # tests for the property `feb075cd-dd2b-47c5-922c-86ef3b06fb16` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`feb075cd-dd2b-47c5-922c-86ef3b06fb16`, "EXPECTED_RESULT")
})

