# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse2002EmbeddedLinks")

model.instance <- InlineResponse2002EmbeddedLinks$new()

test_that("self", {
  # tests for the property `self` (InlineResponse200LinksSelf)

  # uncomment below to test the property 
  #expect_equal(model.instance$`self`, "EXPECTED_RESULT")
})

