# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CoreV2ServicesModelServerEgress")

model.instance <- CoreV2ServicesModelServerEgress$new()

test_that("host", {
  # tests for the property `host` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`host`, "EXPECTED_RESULT")
})

test_that("port", {
  # tests for the property `port` (AnyType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`port`, "EXPECTED_RESULT")
})

test_that("protocol", {
  # tests for the property `protocol` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`protocol`, "EXPECTED_RESULT")
})

