# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse200Links")

model.instance <- InlineResponse200Links$new()

test_that("network", {
  # tests for the property `network` (InlineResponse200LinksNetwork)

  # uncomment below to test the property 
  #expect_equal(model.instance$`network`, "EXPECTED_RESULT")
})

test_that("self", {
  # tests for the property `self` (InlineResponse200LinksSelf)

  # uncomment below to test the property 
  #expect_equal(model.instance$`self`, "EXPECTED_RESULT")
})

