# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse2001EmbeddedLinks")

model.instance <- InlineResponse2001EmbeddedLinks$new()

test_that("services", {
  # tests for the property `services` (InlineResponse200LinksSelf)

  # uncomment below to test the property 
  #expect_equal(model.instance$`services`, "EXPECTED_RESULT")
})

test_that("networks", {
  # tests for the property `networks` (InlineResponse200LinksNetwork)

  # uncomment below to test the property 
  #expect_equal(model.instance$`networks`, "EXPECTED_RESULT")
})

test_that("app-wans", {
  # tests for the property `app-wans` (InlineResponse200LinksSelf)

  # uncomment below to test the property 
  #expect_equal(model.instance$`app-wans`, "EXPECTED_RESULT")
})

test_that("endpoints", {
  # tests for the property `endpoints` (InlineResponse200LinksSelf)

  # uncomment below to test the property 
  #expect_equal(model.instance$`endpoints`, "EXPECTED_RESULT")
})

test_that("certificate-authorities", {
  # tests for the property `certificate-authorities` (InlineResponse200LinksSelf)

  # uncomment below to test the property 
  #expect_equal(model.instance$`certificate-authorities`, "EXPECTED_RESULT")
})

test_that("self", {
  # tests for the property `self` (InlineResponse200LinksSelf)

  # uncomment below to test the property 
  #expect_equal(model.instance$`self`, "EXPECTED_RESULT")
})

test_that("process-executions", {
  # tests for the property `process-executions` (InlineResponse200LinksNetwork)

  # uncomment below to test the property 
  #expect_equal(model.instance$`process-executions`, "EXPECTED_RESULT")
})

test_that("network-controllers", {
  # tests for the property `network-controllers` (InlineResponse200LinksSelf)

  # uncomment below to test the property 
  #expect_equal(model.instance$`network-controllers`, "EXPECTED_RESULT")
})

test_that("posture-checks", {
  # tests for the property `posture-checks` (InlineResponse200LinksSelf)

  # uncomment below to test the property 
  #expect_equal(model.instance$`posture-checks`, "EXPECTED_RESULT")
})

test_that("edge-routers", {
  # tests for the property `edge-routers` (InlineResponse200LinksSelf)

  # uncomment below to test the property 
  #expect_equal(model.instance$`edge-routers`, "EXPECTED_RESULT")
})

test_that("edge-router-policies", {
  # tests for the property `edge-router-policies` (InlineResponse200LinksSelf)

  # uncomment below to test the property 
  #expect_equal(model.instance$`edge-router-policies`, "EXPECTED_RESULT")
})

