=begin comment

untitled API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5170

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::DefaultApi');

my $api = WWW::OpenAPIClient::DefaultApi->new();
isa_ok($api, 'WWW::OpenAPIClient::DefaultApi');

#
# request4_q1q_u3c4dk test
#
{
    my $edge_router_id = undef; # replace NULL with a proper value
    my $result = $api->request4_q1q_u3c4dk(edge_router_id => $edge_router_id);
}

#
# request9s_du_piz_ciu test
#
{
    my $inline_object5 = undef; # replace NULL with a proper value
    my $result = $api->request9s_du_piz_ciu(inline_object5 => $inline_object5);
}

#
# request_a8syya_p_znw test
#
{
    my $result = $api->request_a8syya_p_znw();
}

#
# request_auar_cs_ihk_j test
#
{
    my $edge_router_id = undef; # replace NULL with a proper value
    my $result = $api->request_auar_cs_ihk_j(edge_router_id => $edge_router_id);
}

#
# request_ay_fh_a_qd5pn test
#
{
    my $result = $api->request_ay_fh_a_qd5pn();
}

#
# request_btgg9_zl_c0e test
#
{
    my $edge_router_policy_id = undef; # replace NULL with a proper value
    my $result = $api->request_btgg9_zl_c0e(edge_router_policy_id => $edge_router_policy_id);
}

#
# request_e1_iex_rfv_zg test
#
{
    my $result = $api->request_e1_iex_rfv_zg();
}

#
# request_f_wl_fmqidpx test
#
{
    my $inline_object = undef; # replace NULL with a proper value
    my $result = $api->request_f_wl_fmqidpx(inline_object => $inline_object);
}

#
# request_gij_vc_eo_ml_m test
#
{
    my $result = $api->request_gij_vc_eo_ml_m();
}

#
# request_hp1b9_gi_lax test
#
{
    my $result = $api->request_hp1b9_gi_lax();
}

#
# request_iaj_vi_y_lviu test
#
{
    my $network_id = undef; # replace NULL with a proper value
    my $result = $api->request_iaj_vi_y_lviu(network_id => $network_id);
}

#
# request_k9aj_dj8v_us test
#
{
    my $result = $api->request_k9aj_dj8v_us();
}

#
# request_kke_r9g_ny25 test
#
{
    my $app_wan_id = undef; # replace NULL with a proper value
    my $result = $api->request_kke_r9g_ny25(app_wan_id => $app_wan_id);
}

#
# request_lg_kx_u4ph9t test
#
{
    my $inline_object2 = undef; # replace NULL with a proper value
    my $result = $api->request_lg_kx_u4ph9t(inline_object2 => $inline_object2);
}

#
# request_lo_xf_q_ss8_ge test
#
{
    my $result = $api->request_lo_xf_q_ss8_ge();
}

#
# request_lopo_ftq4ih test
#
{
    my $inline_object1 = undef; # replace NULL with a proper value
    my $result = $api->request_lopo_ftq4ih(inline_object1 => $inline_object1);
}

#
# request_mpy_yt_ii_s6x test
#
{
    my $result = $api->request_mpy_yt_ii_s6x();
}

#
# request_n6_gjg_plo4v test
#
{
    my $organization_id = undef; # replace NULL with a proper value
    my $result = $api->request_n6_gjg_plo4v(organization_id => $organization_id);
}

#
# request_n_xo_v6_k2f0_q test
#
{
    my $inline_object4 = undef; # replace NULL with a proper value
    my $result = $api->request_n_xo_v6_k2f0_q(inline_object4 => $inline_object4);
}

#
# request_oi_i_af_x2_v_us test
#
{
    my $result = $api->request_oi_i_af_x2_v_us();
}

#
# request_p_baai_o3_b0d test
#
{
    my $service_id = undef; # replace NULL with a proper value
    my $result = $api->request_p_baai_o3_b0d(service_id => $service_id);
}

#
# request_py_r6a_up5mi test
#
{
    my $inline_object6 = undef; # replace NULL with a proper value
    my $result = $api->request_py_r6a_up5mi(inline_object6 => $inline_object6);
}

#
# request_q0b3cb_dw8_s test
#
{
    my $result = $api->request_q0b3cb_dw8_s();
}

#
# request_teq_m_ge_er5_f test
#
{
    my $network_id = undef; # replace NULL with a proper value
    my $result = $api->request_teq_m_ge_er5_f(network_id => $network_id);
}

#
# request_tsyuwl_aej_k test
#
{
    my $endpoint_id = undef; # replace NULL with a proper value
    my $result = $api->request_tsyuwl_aej_k(endpoint_id => $endpoint_id);
}

#
# request_v_iz_b1k6_uqb test
#
{
    my $service_id = undef; # replace NULL with a proper value
    my $inline_object3 = undef; # replace NULL with a proper value
    my $result = $api->request_v_iz_b1k6_uqb(service_id => $service_id, inline_object3 => $inline_object3);
}

#
# request_ve_jcbur9i_o test
#
{
    my $network_group_id = undef; # replace NULL with a proper value
    my $result = $api->request_ve_jcbur9i_o(network_group_id => $network_group_id);
}

#
# request_vfua_d_me_trp test
#
{
    my $result = $api->request_vfua_d_me_trp();
}

#
# request_y_lsf4m9_ttt test
#
{
    my $service_id = undef; # replace NULL with a proper value
    my $result = $api->request_y_lsf4m9_ttt(service_id => $service_id);
}

#
# request_yhz_d_aw1_ks4 test
#
{
    my $result = $api->request_yhz_d_aw1_ks4();
}


1;
